# -*- coding: utf-8 -*-
"""9SkinMod.exe

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uNXJ5H7RIRjD6CO5nidpSxjfh9u5zIUn
"""

import numpy as np
import colorsys
import os
import matplotlib.pyplot as plt
from PIL import Image, ImageFilter
from collections import Counter
import configparser
import shutil

GOLD = (231, 174, 51)
SHADE_GOLD = (178, 129, 21)
DARK_GOLD = (115, 87, 27)
GOLD_BROWN = (165, 121, 33)

GREEN = (134, 255, 186)

BLACK = (0, 0, 0)
WHITE = (255, 255, 255)

def recolor_by_rgb_distance(img, source_rgb, target_rgb, threshold):
    img = img.convert("RGBA")
    arr = np.array(img)

    rgb = arr[:, :, :3].astype(np.int16)

    dist = np.linalg.norm(rgb - source_rgb, axis=2)
    mask = dist <= threshold

    lum = (
        0.299 * rgb[:, :, 0] +
        0.587 * rgb[:, :, 1] +
        0.114 * rgb[:, :, 2]
    ) / 255.0
    lum = lum ** 0.5
    lum = np.clip(lum * 1.1, 0.0, 1.0)

    target = np.array(target_rgb) / 255.0
    new_rgb = (target * lum[..., None] * 255).clip(0, 255)

    arr[mask, :3] = new_rgb[mask]
    return Image.fromarray(arr.astype(np.uint8), "RGBA")

def process_batch(input_dir, output_dir, transformations, threshold):
    os.makedirs(output_dir, exist_ok=True)
    files = [f for f in os.listdir(input_dir) if f.lower().endswith(".png")]

    for i, filename in enumerate(files, start=1):
        in_path = os.path.join(input_dir, filename)
        out_path = os.path.join(output_dir, filename)

        img = Image.open(in_path)

        for source, target in transformations:
            img = recolor_by_rgb_distance(img, source, target, threshold)

        img.save(out_path)

def is_yellow(rgb):
    r, g, b = [x / 255.0 for x in rgb]
    h, s, v = colorsys.rgb_to_hsv(r, g, b)

    if v <= 0.60:
        if 0.04 <= h <= 0.25 and s > 0.35 and v > 0.25:
            return True
    else:
        if 0.08 <= h <= 0.22 and s > 0.25:
            return True
    return False

def find_top_yellows(image_path, num_scan=50):
    try:
        img = Image.open(image_path).convert("RGBA")
    except Exception:
        return []

    pixels = list(img.getdata())
    visible_pixels = [p[:3] for p in pixels if p[3] > 0]

    if not visible_pixels: return []

    counts = Counter(visible_pixels)
    yellow_palette = []

    for color, count in counts.most_common(num_scan):
        if is_yellow(color):
            yellow_palette.append(color)

    return yellow_palette

def simple_expand_mask(base_mask):
    up = np.roll(base_mask, -1, axis=0)
    down = np.roll(base_mask, 1, axis=0)
    left = np.roll(base_mask, -1, axis=1)
    right = np.roll(base_mask, 1, axis=1)
    return base_mask | up | down | left | right

def apply_texture(sprite_path, texture_path, output_path, target_colors, always_include_colors, excluded_colors, tolerance=30, exclusion_tolerance=10):
    sprite_img = Image.open(sprite_path).convert("RGBA")
    texture_img = Image.open(texture_path).convert("RGBA")
    texture_img = texture_img.resize(sprite_img.size)

    sprite_data = np.array(sprite_img)
    texture_data = np.array(texture_img)

    r = sprite_data[:,:,0].astype(np.int16)
    g = sprite_data[:,:,1].astype(np.int16)
    b = sprite_data[:,:,2].astype(np.int16)

    target_mask = np.zeros_like(r, dtype=bool)

    for color in target_colors:
        tr, tg, tb = color
        current_mask = (
            (np.abs(r - tr) <= tolerance) &
            (np.abs(g - tg) <= tolerance) &
            (np.abs(b - tb) <= tolerance)
        )
        target_mask = target_mask | current_mask

    if always_include_colors:
        for color in always_include_colors:
            tr, tg, tb = color
            include_mask = (
                (np.abs(r - tr) <= tolerance) &
                (np.abs(g - tg) <= tolerance) &
                (np.abs(b - tb) <= tolerance)
            )
            target_mask = target_mask | include_mask

    final_mask = simple_expand_mask(target_mask)

    if excluded_colors:
        for ex_color in excluded_colors:
            er, eg, eb = ex_color
            shield_mask = (
                (np.abs(r - er) <= exclusion_tolerance) &
                (np.abs(g - eg) <= exclusion_tolerance) &
                (np.abs(b - eb) <= exclusion_tolerance)
            )
            final_mask = final_mask & (~shield_mask)

    sprite_data[final_mask, :3] = texture_data[final_mask, :3]
    result_img = Image.fromarray(sprite_data)
    result_img.save(output_path)

def batch_process_texture(input_dir, output_dir, texture_file, always_include_colors=[], excluded_colors=[], tolerance=10, exclusion_tolerance=10, limit=-1):
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    all_files = os.listdir(input_dir)
    files = [f for f in all_files if f.lower().endswith(('.png', '.jpg', '.jpeg'))]

    processed_count = 0

    for filename in files:
        if limit != -1 and processed_count >= limit:
            break

        input_path = os.path.join(input_dir, filename)
        output_path = os.path.join(output_dir, filename)

        palette = find_top_yellows(input_path, num_scan=50)

        if palette or always_include_colors:
            apply_texture(
                input_path,
                texture_file,
                output_path,
                palette,
                always_include_colors,
                excluded_colors,
                tolerance=tolerance,
                exclusion_tolerance=exclusion_tolerance
            )
            processed_count += 1
        else:
            pass

def add_outline_to_image(image_path, output_path, outline_color=(255, 255, 255), thickness=3):
    try:
        img = Image.open(image_path).convert("RGBA")
        alpha = img.getchannel("A")
        outline_mask = alpha.filter(ImageFilter.MaxFilter(thickness * 2 + 1))
        outline_layer = Image.new("RGBA", img.size, outline_color)
        outline_layer.putalpha(outline_mask)
        final_image = Image.alpha_composite(outline_layer, img)
        final_image.save(output_path)
    except Exception as e:
        pass

def batch_process_outlines(input_folder, output_folder, color, thickness):
    if not os.path.exists(output_folder):
        os.makedirs(output_folder)

    valid_extensions = ('.png', '.jpg', '.jpeg', '.bmp', '.gif')
    files = [f for f in os.listdir(input_folder) if f.lower().endswith(valid_extensions)]

    if not files:
        return

    for filename in files:
        in_path = os.path.join(input_folder, filename)
        out_path = os.path.join(output_folder, filename)
        add_outline_to_image(in_path, out_path, color, thickness)

def texture_process_wrapper(input_dir, output_dir, texture_file, always_include_colors=[], excluded_colors=[], tolerance=50, exclusion_tolerance=80):
    excluded_list = [ WHITE, BLACK ]
    always_include_list = [ GOLD_BROWN, DARK_GOLD ]

    try:
      batch_process_texture(input_dir, output_dir, texture_file, always_include_colors, excluded_colors, tolerance, exclusion_tolerance, limit = -1)
    except Exception as e:
      print(f"Encountered an error while applying texture {texture_file} on {input_dir}: {e}")


def recolor_process_wrapper(input_dir, output_dir, source_rgb, target_rgb, threshold=50):
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    files = [f for f in os.listdir(input_dir) if f.lower().endswith('.png')]

    for i, filename in enumerate(files, start=1):
        in_path = os.path.join(input_dir, filename)
        out_path = os.path.join(output_dir, filename)

        try:
            img = Image.open(in_path)
            new_img = recolor_by_rgb_distance(img, source_rgb, target_rgb, threshold)
            new_img.save(out_path)
        except Exception as e:
            print(f"Encountered an error while recoloring {filename} in {input_dir}: {e}")

def outline_process_wrapper(input_dir, output_dir, outline_color, thickness=3):
    try:
      batch_process_outlines(input_dir, output_dir, outline_color, thickness)
    except Exception as e:
      print(f"Encountered an error while outlining images in {input_dir}: {e}")

def parse_color(val):
    if isinstance(val, str):
        val = val.strip()
        if val.startswith("#"):
            val = val.lstrip("#")
            try:
                return tuple(int(val[i:i+2], 16) for i in (0, 2, 4))
            except:
                return None
        try:
            return eval(val)
        except:
            return None
    return val

if __name__ == "__main__":
    config = configparser.ConfigParser()
    config.read("skinmodder.cfg")

    sprites_folder = config["sprites_folder"]["sprites_folder"]
    output_folder = config["output_folder"]["output_folder"]

    cloak_customize_mode = config["cloak"]["cloak_customize_mode"]
    cloak_texture_img = config["cloak"]["cloak_texture_img"]
    cloak_recolor_color = config["cloak"]["cloak_recolor_color"]

    dash_customize_mode = config["dash"]["dash_customize_mode"]
    dash_texture_img = config["dash"]["dash_texture_img"]
    dash_recolor_color = config["dash"]["dash_recolor_color"]

    sword_customize_mode = config["sword"]["sword_customize_mode"]
    sword_texture_img = config["sword"]["sword_texture_img"]
    sword_recolor_color = config["sword"]["sword_recolor_color"]

    talismanball_customize_mode = config["talismanball"]["talismanball_customize_mode"]
    talismanball_texture_img = config["talismanball"]["talismanball_texture_img"]
    talismanball_recolor_color = parse_color(config["talismanball"]["talismanball_recolor_color"])

    parry_customize_mode = config["parry"]["parry_customize_mode"]
    parry_texture_img = config["parry"]["parry_texture_img"]
    parry_recolor_color = parse_color(config["parry"]["parry_recolor_color"])

    uc_customize_mode = config["uc"]["uc_customize_mode"]
    uc_texture_img = config["uc"]["uc_texture_img"]
    uc_recolor_color = parse_color(config["uc"]["uc_recolor_color"])

    talisman_customize_mode = config["talisman"]["talisman_customize_mode"]
    talisman_texture_img = config["talisman"]["talisman_texture_img"]
    talisman_recolor_color = parse_color(config["talisman"]["talisman_recolor_color"])

    uiparryball_customize_mode = config["uiparryball"]["uiparryball_customize_mode"]
    uiparryball_texture_img = config["uiparryball"]["uiparryball_texture_img"]
    uiparryball_recolor_color = parse_color(config["uiparryball"]["uiparryball_recolor_color"])

    outlined_recolor_parries = config.getboolean("parry_outline", "outlined_recolor_parries")
    parry_outline_color = parse_color(config["parry_outline"]["parry_outline_color"])
    outlined_texture_parries = config.getboolean("parry_outline", "outlined_texture_parries")
    parry_outline_texture_img = config["parry_outline"]["parry_outline_texture_img"]
    parry_outline_thickness = config.getint("parry_outline", "parry_outline_thickness")

    outlined_recolor_uc = config.getboolean("uc_outline", "outlined_recolor_UC")
    uc_outline_color = parse_color(config["uc_outline"]["uc_outline_color"])
    outlined_texture_uc = config.getboolean("uc_outline", "outlined_texture_UC")
    uc_outline_texture_img = config["uc_outline"]["uc_outline_texture_img"]
    uc_outline_thickness = config.getint("uc_outline", "uc_outline_thickness")

    for item in os.listdir(sprites_folder):
      s = os.path.join(sprites_folder, item)
      d = os.path.join(output_folder, item)

      if os.path.isdir(s):
          shutil.copytree(s, d, dirs_exist_ok=True)
      else:
          shutil.copy2(s, d)

    ##CLOAK CUSTOMIZATION
    if cloak_customize_mode != "off":
        if cloak_customize_mode == "texture":
            texture_process_wrapper(os.path.join(sprites_folder, "Player"), os.path.join(output_folder, "Player"), cloak_texture_img)
        if cloak_customize_mode == "recolor":
            recolor_process_wrapper(os.path.join(sprites_folder, "Player"), os.path.join(output_folder, "Player"), GOLD, cloak_recolor_color)
            recolor_process_wrapper(os.path.join(output_folder, "Player"), os.path.join(output_folder, "Player"), SHADE_GOLD, cloak_recolor_color)
            recolor_process_wrapper(os.path.join(output_folder, "Player"), os.path.join(output_folder, "Player"), DARK_GOLD, cloak_recolor_color)
            recolor_process_wrapper(os.path.join(output_folder, "Player"), os.path.join(output_folder, "Player"), GOLD_BROWN, cloak_recolor_color, threshold = 30)

    #DASH CUSTOMIZATION
    if dash_customize_mode != "off":
        if dash_customize_mode == "texture":
            texture_process_wrapper(os.path.join(sprites_folder, "Player"), os.path.join(output_folder, "Player"), dash_texture_img)
        if dash_customize_mode == "recolor":
            recolor_process_wrapper(os.path.join(sprites_folder, "Player"), os.path.join(output_folder, "Player"), GREEN, dash_recolor_color)

    #SWORD CUSTOMIZATION
    if sword_customize_mode != "off":
        if sword_customize_mode == "texture":
            texture_process_wrapper(os.path.join(sprites_folder, "Sword"), os.path.join(output_folder, "Sword"), sword_texture_img)
        if sword_customize_mode == "recolor":
            recolor_process_wrapper(os.path.join(sprites_folder, "Sword"), os.path.join(output_folder, "Sword"), GREEN, sword_recolor_color)

    #TALISMANBALL CUSTOMIZATION
    if talismanball_customize_mode != "off":
        if talismanball_customize_mode == "texture":
            texture_process_wrapper(os.path.join(sprites_folder, "TalismanBall"), os.path.join(output_folder, "TalismanBall"), talismanball_texture_img)
        if talismanball_customize_mode == "recolor":
            recolor_process_wrapper(os.path.join(sprites_folder, "TalismanBall"), os.path.join(output_folder, "TalismanBall"), GREEN, talismanball_recolor_color)

    #PARRY CUSTOMIZATION
    if parry_customize_mode != "off":
        if parry_customize_mode == "texture":
            texture_process_wrapper(os.path.join(sprites_folder, "Parry"), os.path.join(output_folder, "Parry"), parry_texture_img)
        if parry_customize_mode == "recolor":
            recolor_process_wrapper(os.path.join(sprites_folder, "Parry"), os.path.join(output_folder, "Parry"), GREEN, parry_recolor_color)

    #UC CUSTOMIZATION
    if uc_customize_mode != "off":
        if uc_customize_mode == "texture":
            texture_process_wrapper(os.path.join(sprites_folder, "UC"), os.path.join(output_folder, "Parry"), uc_texture_img)
        if uc_customize_mode == "recolor":
            recolor_process_wrapper(os.path.join(sprites_folder, "UC"), os.path.join(output_folder, "Parry"), GREEN, uc_recolor_color)

    #TALISMAN CUSTOMIZATION
    if talisman_customize_mode != "off":
        if talisman_customize_mode == "texture":
            texture_process_wrapper(os.path.join(sprites_folder, "Foo"), os.path.join(output_folder, "Foo"), talisman_texture_img)
        if talisman_customize_mode == "recolor":
            recolor_process_wrapper(os.path.join(sprites_folder, "Foo"), os.path.join(output_folder, "Foo"), WHITE, talisman_recolor_color, threshold = 200)

    #UI PARRY BALL CUSTOMIZATION
    if uiparryball_customize_mode != "off":
        if uiparryball_customize_mode == "texture":
            texture_process_wrapper(os.path.join(sprites_folder, "UIParryBall"), os.path.join(output_folder, "UIParryBall"), uiparryball_texture_img)
        if uiparryball_customize_mode == "recolor":
            recolor_process_wrapper(os.path.join(sprites_folder, "UIParryBall"), os.path.join(output_folder, "UIParryBall"), WHITE, uiparryball_recolor_color)

    #PARRY OUTLINES
    if outlined_recolor_parries:
        outline_process_wrapper(os.path.join(sprites_folder, "Parry"), os.path.join(output_folder, "Parry"), parry_outline_color, parry_outline_thickness)
    if outlined_texture_parries:
        texture_process_wrapper(os.path.join(sprites_folder, "Parry"), os.path.join(output_folder, "Parry"), parry_outline_texture_img)

    if outlined_recolor_uc:
        outline_process_wrapper(os.path.join(sprites_folder, "UC"), os.path.join(output_folder, "Parry"), uc_outline_color, uc_outline_thickness)
    if outlined_texture_uc:
        texture_process_wrapper(os.path.join(sprites_folder, "UC"), os.path.join(output_folder, "Parry"), uc_outline_texture_img)

    print("Operation complete.")

    pass

