# -*- coding: utf-8 -*-
"""IT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18wcHQ6vkl2E_bA4wkRkWW6CP4vT_QFYQ
"""

print("Welcome to the AI-Based Employee Wellbeing Advisor\n")

def get_score(question):
    while True:
        try:
            value = float(input(question))
            if 1 <= value <= 10:
                return value
            else:
                print("⚠️ Please enter a number between 1 and 10.")
        except ValueError:
            print("⚠️ Invalid input. Please enter a numeric value.")

# --- Data Collection ---
stress = get_score("On a scale of 1–10, how stressed is the employee? ")
workload = get_score("On a scale of 1–10, how heavy is their workload? ")
job_satisfaction = get_score("On a scale of 1–10, how satisfied is the employee with their job? ")
sleep = get_score("On a scale of 1–10, how well does the employee sleep? ")
motivation = get_score("On a scale of 1–10, how motivated is the employee? ")

role_clarity = get_score(
    "On a scale of 1–10, how clear is the employee about their role and responsibilities? "
)

autonomy = get_score(
    "On a scale of 1–10, how much control does the employee have over how they do their work? "
)

team_relationships = get_score(
    "On a scale of 1–10, how positive are the employee’s relationships with colleagues? "
)

# --- Wellbeing Index ---
wellbeing_index = (
    job_satisfaction +
    sleep +
    motivation +
    role_clarity +
    autonomy +
    team_relationships
) - (stress + workload)

print("\n--- Wellbeing Analysis ---")

recommendations = []

# --- Expert System Rules ---

# Stress & workload
if stress >= 7 and workload >= 7:
    print("⚠️ High stress and workload detected.")
    recommendations.append("Review workload distribution and deadlines.")
    recommendations.append("Offer flexible working hours or remote work options.")

# Sleep
if sleep <= 4:
    recommendations.append("Encourage work-life balance and healthy sleep habits.")

# Motivation & satisfaction
if motivation <= 5 and job_satisfaction <= 5:
    recommendations.append("Discuss career development and growth opportunities.")
    recommendations.append("Implement recognition or reward initiatives.")

# Role clarity
if role_clarity <= 4:
    recommendations.append("Clarify role expectations and performance objectives.")

# Autonomy
if autonomy <= 4:
    recommendations.append("Increase employee autonomy and involvement in decision-making.")

# Team relationships
if team_relationships <= 4:
    recommendations.append("Address team dynamics through mediation or team-building activities.")

# Overall wellbeing assessment
if wellbeing_index >= 8:
    print("✅ Overall employee wellbeing appears strong.")
    recommendations.append("Maintain current management and wellbeing practices.")
elif wellbeing_index >= 2:
    print("⚠️ Moderate wellbeing risk identified.")
    recommendations.append("Monitor wellbeing closely and schedule regular check-ins.")
else:
    print("🚨 Low wellbeing detected. Immediate managerial action recommended.")
    recommendations.append("Refer employee to HR or wellbeing support services.")

# --- Output ---
print("\nSuggested Management Actions:")
for r in recommendations:
    print(f"- {r}")

print(
    "\nThis advice was generated using a rule-based AI expert system "
    "designed to support managerial decision-making related to employee wellbeing."
)