# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RBXY5DClHmhFm0K49_iX9Lb_XfrODylJ
"""

import subprocess
import sys
import re
import pandas as pd
from PyPDF2 import PdfReader
from PIL import Image
import pytesseract
from pdf2image import convert_from_path
import numpy as np

# --- 1. Installation Functions ---
def install_package(package):
    try:
        __import__(package)
        print(f"{package} is already installed.")
    except ImportError:
        print(f"Installing {package}...")
        subprocess.check_call([sys.executable, "-m", "pip", "install", package])
        print(f"{package} installed successfully.")

# Install core PDF libraries
install_package('PyPDF2')
install_package('pdfminer.six') # Though not used in final code, kept for initial context

# Install Tesseract-OCR and Spanish language pack
print("Installing Tesseract-OCR and Spanish language data...")
subprocess.run(['apt-get', 'update'], check=True)
subprocess.run(['apt-get', 'install', '-y', 'tesseract-ocr', 'tesseract-ocr-spa'], check=True)
print("Tesseract-OCR installed successfully.")

# Install pytesseract and pdf2image
install_package('pytesseract')
print("Installing poppler-utils...")
subprocess.run(['apt-get', 'install', '-y', 'poppler-utils'], check=True)
print("poppler-utils installed successfully.")
install_package('pdf2image')
print("All necessary packages and dependencies are configured and ready.")

# --- 2. PDF Text Extraction Functions ---
def extract_text_from_pdf(pdf_path):
    """Extracts text from a given PDF file using PyPDF2."""
    try:
        reader = PdfReader(pdf_path)
        text = ""
        for page in reader.pages:
            text += page.extract_text() or ""
        return text
    except Exception as e:
        print(f"Error processing {pdf_path}: {e}")
        return None

def extract_text_with_ocr(pdf_path, page_number=None, lang='spa', area=None):
    """Extracts text from a specific page or entire PDF using OCR."""
    try:
        text = ""
        if page_number is None:
            pages = convert_from_path(pdf_path)
            for i, image in enumerate(pages):
                if area:
                    image = image.crop(area)
                text += pytesseract.image_to_string(image, lang=lang)
        else:
            pages = convert_from_path(pdf_path, first_page=page_number + 1, last_page=page_number + 1)
            if not pages:
                print(f"Error: No page found for page_number {page_number} in {pdf_path}")
                return None
            image = pages[0]
            if area:
                image = image.crop(area)
            text = pytesseract.image_to_string(image, lang=lang)

        return text.strip()
    except Exception as e:
        print(f"Error during OCR extraction from {pdf_path} (page {page_number if page_number is not None else 'all'}): {e}")
        return None

# --- 3. Field Extraction Logic ---
# Regex patterns for PyPDF2 extracted text (original text)
extraction_patterns_pypdf2 = {
    'Ejercicio': r'(\d{4})\s+\d+\s+Expediente N[\xbaº]:',
    'ORDEN DE COMPRA Nº': r'Referencia:\s*OC(\d+)\s*-',
    'Expediente Nº': r'(\d+)\s+Expediente N[\xbaº]:',
    'Comp.de origen': r'CUIT\.{5}:Comp\.de origen:\s*(\d+)',
    'Proveedor': r'Expediente N[\xbaº]:.*?([A-Z\s.,-]+?)(?=\s*\d{6,}\s+\d{5,}\s+\w{5,}|\nProveedor:\d{4}|\n|$)',
    'CUIT': r'(\d{1,2}-\s*\d{8}-\d{1,2})(?=CUIT\.{5}:)',
    'Total': r'([\d\.,]+)\s+Total',
    'FECHA_EMISION': r'(\d{2}/\d{2}/\d{2})\s+Fecha/Hora de emisi[oó]n:',
    'FIRMA_1': r'FIRMA_1:\s*([^\n]+)', # Placeholder for now
    'FIRMA_2': r'FIRMA_2:\s*([^\n]+)', # Placeholder for now
    'FIRMA_3': r'FIRMA_3:\s*([^\n]+)'  # Placeholder for now
}

# Regex patterns for OCR extracted text
extraction_patterns_ocr = {
    'Ejercicio': r'Ejercicio:\s*(\d{4})',
    'ORDEN DE COMPRA Nº': r'ORDEN DE COMPRA N[^\]+:\s*(\d+)',
    'Expediente Nº': r'Expediente N[\xba%º]:\s*—?(\d+)',
    'Comp.de origen': r'Comp\.de origen:\s*(\d+)',
    'Proveedor': r'Proveedor:\s*(?:\d+\s*)?([A-Z\s.,-]+?)(?=\s*Comp\.de origen|\n|Domicilio|$)',
    'CUIT': r'[Cc]UIT\.{5}:\s*(\d{1,2}\s*-\s*\d{8}\s*-\s*\d{1,2})',
    'Total': r'Son Pesos:.*?Total\s*([\d\.,\s]+)',
    'FECHA_EMISION': r'Fecha/Hora de emisi[oó]n:\s*(\d{2}/\d{2}/\d{2})',
    'FIRMA_1': r'(Maria Agustina Vergara\s*Administrativo)',
    'FIRMA_2': r'(NATALIA BAREA\s*Jefa de Departamento)',
    'FIRMA_3': r'(SANDRA TENNERINI\s*Director)'
}

def extract_fields(text, patterns):
    """Extracts fields from text using a dictionary of regex patterns."""
    extracted_data = {}
    for field, pattern in patterns.items():
        match = re.search(pattern, text, re.IGNORECASE | re.DOTALL)
        if match:
            value = match.group(1)
            if value is not None:
                extracted_data[field] = value.strip()
            else:
                extracted_data[field] = None
        else:
            extracted_data[field] = None
    return extracted_data

# --- 4. Main Processing Logic ---
pdf_files = [
    '/content/DOCFI-2026-01598534-GDEMZA-ATM.pdf',
    '/content/DOCFI-2026-01624694-GDEMZA-ATM.pdf'
]

# Extract text using PyPDF2 (for initial extraction verification)
extracted_texts = {}
for pdf_file in pdf_files:
    text = extract_text_from_pdf(pdf_file)
    if text:
        extracted_texts[pdf_file] = text

# Extract fields using PyPDF2 patterns (as per initial task)
all_extracted_data_pypdf2 = []
for pdf_file, text in extracted_texts.items():
    extracted_info = extract_fields(text, extraction_patterns_pypdf2)
    all_extracted_data_pypdf2.append(extracted_info)
df_extracted_data = pd.DataFrame(all_extracted_data_pypdf2)

# Extract full OCR text for all PDFs
full_ocr_texts = {}
for pdf_file in pdf_files:
    text = extract_text_with_ocr(pdf_file, page_number=None) # Extract text from all pages
    if text:
        full_ocr_texts[pdf_file] = text

# Apply OCR-specific refined patterns
ocr_extracted_data = []
for pdf_file, text in full_ocr_texts.items():
    extracted_info = extract_fields(text, extraction_patterns_ocr)
    ocr_extracted_data.append(extracted_info)
df_ocr_extracted_data = pd.DataFrame(ocr_extracted_data)

# --- 5. Data Cleaning and Formatting ---
# Create a copy to perform cleaning operations
df_ocr_extracted_data_cleaned = df_ocr_extracted_data.copy()

# Clean signatory fields
roles_to_remove_patterns = [
    r'\s*Administrativo',
    r'\s*Jefa de Departamento',
    r'\s*Director'
]
signatory_columns = ['FIRMA_1', 'FIRMA_2', 'FIRMA_3']

for col in signatory_columns:
    df_ocr_extracted_data_cleaned[col] = df_ocr_extracted_data_cleaned[col].astype(str)
    for pattern in roles_to_remove_patterns:
        df_ocr_extracted_data_cleaned[col] = df_ocr_extracted_data_cleaned[col].str.replace(
            pattern, '', regex=True, flags=re.IGNORECASE
        )
    df_ocr_extracted_data_cleaned[col] = df_ocr_extracted_data_cleaned[col].str.replace(
        r'\n+', ' ', regex=True
    )
    df_ocr_extracted_data_cleaned[col] = df_ocr_extracted_data_cleaned[col].str.strip()
    df_ocr_extracted_data_cleaned[col] = df_ocr_extracted_data_cleaned[col].replace('None', None)

# Format 'Expediente Nº' field
def format_expediente_no(row):
    expediente_no = str(row['Expediente Nº']).strip()
    ejercicio = str(row['Ejercicio']).strip()

    if expediente_no and expediente_no != 'None' and ejercicio and ejercicio != 'None':
        expediente_no_cleaned = re.sub(r'-\s*\d{4}$', '', expediente_no).strip()
        return f"{expediente_no_cleaned}-{ejercicio}"
    elif expediente_no and expediente_no != 'None':
        return expediente_no
    else:
        return None

df_ocr_extracted_data_cleaned['Expediente Nº'] = df_ocr_extracted_data_cleaned.apply(format_expediente_no, axis=1)

# --- 6. Export to Excel ---
df_extracted_data.to_excel('extracted_data.xlsx', index=False) # Original extraction export
df_ocr_extracted_data.to_excel('ocr_extracted_data.xlsx', index=False) # OCR extraction export
df_ocr_extracted_data_cleaned.to_excel('ocr_extracted_data_cleaned.xlsx', index=False) # Cleaned OCR extraction export

print("All data processing, cleaning, and exports complete.")

"""# Task
Process `DOCFI-2026-01598534-GDEMZA-ATM.pdf` and `DOCFI-2026-01624694-GDEMZA-ATM.pdf` by extracting text using PyPDF2 and OCR, applying predefined extraction patterns, cleaning the extracted data, exporting the results to Excel files, and finally displaying the contents of `ocr_extracted_data_cleaned.xlsx`.

## Corregir el orden de importación y ejecución

### Subtask:
Corregir la `ModuleNotFoundError` para `PyPDF2` reordenando las declaraciones de importación para que ocurran después de que sus respectivos paquetes hayan sido instalados.

**Reasoning**:
The previous code failed due to `ModuleNotFoundError` because import statements were placed before their respective packages were installed. I will fix this by reordering the import statements to occur after their installation calls, as specified in the instructions.
"""

import subprocess
import sys
import re
import pandas as pd
from PIL import Image
import numpy as np

# --- 1. Installation Functions ---
def install_package(package):
    try:
        __import__(package)
        print(f"{package} is already installed.")
    except ImportError:
        print(f"Installing {package}...")
        subprocess.check_call([sys.executable, "-m", "pip", "install", package])
        print(f"{package} installed successfully.")

# Install core PDF libraries
install_package('PyPDF2')
from PyPDF2 import PdfReader
install_package('pdfminer.six') # Though not used in final code, kept for initial context

# Install Tesseract-OCR and Spanish language pack
print("Installing Tesseract-OCR and Spanish language data...")
subprocess.run(['apt-get', 'update'], check=True)
subprocess.run(['apt-get', 'install', '-y', 'tesseract-ocr', 'tesseract-ocr-spa'], check=True)
print("Tesseract-OCR installed successfully.")

# Install pytesseract and pdf2image
install_package('pytesseract')
import pytesseract
print("Installing poppler-utils...")
subprocess.run(['apt-get', 'install', '-y', 'poppler-utils'], check=True)
print("poppler-utils installed successfully.")
install_package('pdf2image')
from pdf2image import convert_from_path
print("All necessary packages and dependencies are configured and ready.")

# --- 2. PDF Text Extraction Functions ---
def extract_text_from_pdf(pdf_path):
    """Extracts text from a given PDF file using PyPDF2."""
    try:
        reader = PdfReader(pdf_path)
        text = ""
        for page in reader.pages:
            text += page.extract_text() or ""
        return text
    except Exception as e:
        print(f"Error processing {pdf_path}: {e}")
        return None

def extract_text_with_ocr(pdf_path, page_number=None, lang='spa', area=None):
    """Extracts text from a specific page or entire PDF using OCR."""
    try:
        text = ""
        if page_number is None:
            pages = convert_from_path(pdf_path)
            for i, image in enumerate(pages):
                if area:
                    image = image.crop(area)
                text += pytesseract.image_to_string(image, lang=lang)
        else:
            pages = convert_from_path(pdf_path, first_page=page_number + 1, last_page=page_number + 1)
            if not pages:
                print(f"Error: No page found for page_number {page_number} in {pdf_path}")
                return None
            image = pages[0]
            if area:
                image = image.crop(area)
            text = pytesseract.image_to_string(image, lang=lang)

        return text.strip()
    except Exception as e:
        print(f"Error during OCR extraction from {pdf_path} (page {page_number if page_number is not None else 'all'}): {e}")
        return None

# --- 3. Field Extraction Logic ---
# Regex patterns for PyPDF2 extracted text (original text)
extraction_patterns_pypdf2 = {
    'Ejercicio': r'(\d{4})\s+\d+\s+Expediente N[\xbaº]:',
    'ORDEN DE COMPRA Nº': r'Referencia:\s*OC(\d+)\s*-',
    'Expediente Nº': r'(\d+)\s+Expediente N[\xbaº]:',
    'Comp.de origen': r'CUIT\.{{5}}:Comp\.de origen:\s*(\d+)',
    'Proveedor': r'Expediente N[\xbaº]:.*?([A-Z\s.,-]+?)(?=\s*\d{6,}\s+\d{5,}\s+\w{5,}|\nProveedor:\d{4}|\n|$)',
    'CUIT': r'(\d{1,2}-\s*\d{8}-\d{1,2})(?=CUIT\.{{5}}:{1})',
    'Total': r'([\d\.,]+)\s+Total',
    'FECHA_EMISION': r'(\d{2}/\d{2}/\d{2})\s+Fecha/Hora de emisi[oó]n:',
    'FIRMA_1': r'FIRMA_1:\s*([^\n]+)', # Placeholder for now
    'FIRMA_2': r'FIRMA_2:\s*([^\n]+)', # Placeholder for now
    'FIRMA_3': r'FIRMA_3:\s*([^\n]+)'  # Placeholder for now
}

# Regex patterns for OCR extracted text
extraction_patterns_ocr = {
    'Ejercicio': r'Ejercicio:\s*(\d{4})',
    'ORDEN DE COMPRA Nº': r'ORDEN DE COMPRA N[^\]+:\s*(\d+)',
    'Expediente Nº': r'Expediente N[\xba%º]:\s*—?(\d+)',
    'Comp.de origen': r'Comp\.de origen:\s*(\d+)',
    'Proveedor': r'Proveedor:\s*(?:\d+\s*)?([A-Z\s.,-]+?)(?=\s*Comp\.de origen|\n|Domicilio|$)',
    'CUIT': r'[Cc]UIT\.{{5}}:\s*(\d{1,2}\s*-\s*\d{8}\s*-\s*\d{1,2})',
    'Total': r'Son Pesos:.*?Total\s*([\d\.,\s]+)',
    'FECHA_EMISION': r'Fecha/Hora de emisi[oó]n:\s*(\d{2}/\d{2}/\d{2})',
    'FIRMA_1': r'(Maria Agustina Vergara\s*Administrativo)',
    'FIRMA_2': r'(NATALIA BAREA\s*Jefa de Departamento)',
    'FIRMA_3': r'(SANDRA TENNERINI\s*Director)'
}

def extract_fields(text, patterns):
    """Extracts fields from text using a dictionary of regex patterns."""
    extracted_data = {}
    for field, pattern in patterns.items():
        match = re.search(pattern, text, re.IGNORECASE | re.DOTALL)
        if match:
            value = match.group(1)
            if value is not None:
                extracted_data[field] = value.strip()
            else:
                extracted_data[field] = None
        else:
            extracted_data[field] = None
    return extracted_data

# --- 4. Main Processing Logic ---
pdf_files = [
    '/content/DOCFI-2026-01598534-GDEMZA-ATM.pdf',
    '/content/DOCFI-2026-01624694-GDEMZA-ATM.pdf'
]

# Extract text using PyPDF2 (for initial extraction verification)
extracted_texts = {}
for pdf_file in pdf_files:
    text = extract_text_from_pdf(pdf_file)
    if text:
        extracted_texts[pdf_file] = text

# Extract fields using PyPDF2 patterns (as per initial task)
all_extracted_data_pypdf2 = []
for pdf_file, text in extracted_texts.items():
    extracted_info = extract_fields(text, extraction_patterns_pypdf2)
    all_extracted_data_pypdf2.append(extracted_info)
df_extracted_data = pd.DataFrame(all_extracted_data_pypdf2)

# Extract full OCR text for all PDFs
full_ocr_texts = {}
for pdf_file in pdf_files:
    text = extract_text_with_ocr(pdf_file, page_number=None) # Extract text from all pages
    if text:
        full_ocr_texts[pdf_file] = text

# Apply OCR-specific refined patterns
ocr_extracted_data = []
for pdf_file, text in full_ocr_texts.items():
    extracted_info = extract_fields(text, extraction_patterns_ocr)
    ocr_extracted_data.append(extracted_info)
df_ocr_extracted_data = pd.DataFrame(ocr_extracted_data)

# --- 5. Data Cleaning and Formatting ---
# Create a copy to perform cleaning operations
df_ocr_extracted_data_cleaned = df_ocr_extracted_data.copy()

# Clean signatory fields
roles_to_remove_patterns = [
    r'\s*Administrativo',
    r'\s*Jefa de Departamento',
    r'\s*Director'
]
signatory_columns = ['FIRMA_1', 'FIRMA_2', 'FIRMA_3']

for col in signatory_columns:
    df_ocr_extracted_data_cleaned[col] = df_ocr_extracted_data_cleaned[col].astype(str)
    for pattern in roles_to_remove_patterns:
        df_ocr_extracted_data_cleaned[col] = df_ocr_extracted_data_cleaned[col].str.replace(
            pattern, '', regex=True, flags=re.IGNORECASE
        )
    df_ocr_extracted_data_cleaned[col] = df_ocr_extracted_data_cleaned[col].str.replace(
        r'\n+', ' ', regex=True
    )
    df_ocr_extracted_data_cleaned[col] = df_ocr_extracted_data_cleaned[col].str.strip()
    df_ocr_extracted_data_cleaned[col] = df_ocr_extracted_data_cleaned[col].replace('None', None)

# Format 'Expediente Nº' field
def format_expediente_no(row):
    expediente_no = str(row['Expediente Nº']).strip()
    ejercicio = str(row['Ejercicio']).strip()

    if expediente_no and expediente_no != 'None' and ejercicio and ejercicio != 'None':
        expediente_no_cleaned = re.sub(r'-\s*\d{4}$', '', expediente_no).strip()
        return f"{expediente_no_cleaned}-{ejercicio}"
    elif expediente_no and expediente_no != 'None':
        return expediente_no
    else:
        return None

df_ocr_extracted_data_cleaned['Expediente Nº'] = df_ocr_extracted_data_cleaned.apply(format_expediente_no, axis=1)

# --- 6. Export to Excel ---
df_extracted_data.to_excel('extracted_data.xlsx', index=False) # Original extraction export
df_ocr_extracted_data.to_excel('ocr_extracted_data.xlsx', index=False) # OCR extraction export
df_ocr_extracted_data_cleaned.to_excel('ocr_extracted_data_cleaned.xlsx', index=False) # Cleaned OCR extraction export

print("All data processing, cleaning, and exports complete.")

"""**Reasoning**:
The previous step successfully resolved the `ModuleNotFoundError` by reordering imports, but a new error 'unterminated character set' occurred because the `]` character was improperly escaped within a regex character set in the `extraction_patterns_ocr` dictionary. I will fix this by correcting the `ORDEN DE COMPRA Nº` pattern to properly handle the `]` within the character set.


"""

import subprocess
import sys
import re
import pandas as pd
from PIL import Image
import numpy as np

# --- 1. Installation Functions ---
def install_package(package):
    try:
        __import__(package)
        print(f"{package} is already installed.")
    except ImportError:
        print(f"Installing {package}...")
        subprocess.check_call([sys.executable, "-m", "pip", "install", package])
        print(f"{package} installed successfully.")

# Install core PDF libraries
install_package('PyPDF2')
from PyPDF2 import PdfReader
install_package('pdfminer.six') # Though not used in final code, kept for initial context

# Install Tesseract-OCR and Spanish language pack
print("Installing Tesseract-OCR and Spanish language data...")
subprocess.run(['apt-get', 'update'], check=True)
subprocess.run(['apt-get', 'install', '-y', 'tesseract-ocr', 'tesseract-ocr-spa'], check=True)
print("Tesseract-OCR installed successfully.")

# Install pytesseract and pdf2image
install_package('pytesseract')
import pytesseract
print("Installing poppler-utils...")
subprocess.run(['apt-get', 'install', '-y', 'poppler-utils'], check=True)
print("poppler-utils installed successfully.")
install_package('pdf2image')
from pdf2image import convert_from_path
print("All necessary packages and dependencies are configured and ready.")

# --- 2. PDF Text Extraction Functions ---
def extract_text_from_pdf(pdf_path):
    """Extracts text from a given PDF file using PyPDF2."""
    try:
        reader = PdfReader(pdf_path)
        text = ""
        for page in reader.pages:
            text += page.extract_text() or ""
        return text
    except Exception as e:
        print(f"Error processing {pdf_path}: {e}")
        return None

def extract_text_with_ocr(pdf_path, page_number=None, lang='spa', area=None):
    """Extracts text from a specific page or entire PDF using OCR."""
    try:
        text = ""
        if page_number is None:
            pages = convert_from_path(pdf_path)
            for i, image in enumerate(pages):
                if area:
                    image = image.crop(area)
                text += pytesseract.image_to_string(image, lang=lang)
        else:
            pages = convert_from_path(pdf_path, first_page=page_number + 1, last_page=page_number + 1)
            if not pages:
                print(f"Error: No page found for page_number {page_number} in {pdf_path}")
                return None
            image = pages[0]
            if area:
                image = image.crop(area)
            text = pytesseract.image_to_string(image, lang=lang)

        return text.strip()
    except Exception as e:
        print(f"Error during OCR extraction from {pdf_path} (page {page_number if page_number is not None else 'all'}): {e}")
        return None

# --- 3. Field Extraction Logic ---
# Regex patterns for PyPDF2 extracted text (original text)
extraction_patterns_pypdf2 = {
    'Ejercicio': r'(\d{4})\s+\d+\s+Expediente N[\xbaº]:',
    'ORDEN DE COMPRA Nº': r'Referencia:\s*OC(\d+)\s*-',
    'Expediente Nº': r'(\d+)\s+Expediente N[\xbaº]:',
    'Comp.de origen': r'CUIT\.{{5}}:Comp\.de origen:\s*(\d+)',
    'Proveedor': r'Expediente N[\xbaº]:.*?([A-Z\s.,-]+?)(?=\s*\d{6,}\s+\d{5,}\s+\w{5,}|\nProveedor:\d{4}|\n|$)',
    'CUIT': r'(\d{1,2}-\s*\d{8}-\d{1,2})(?=CUIT\.{{5}}:{1})',
    'Total': r'([\d\.,]+)\s+Total',
    'FECHA_EMISION': r'(\d{2}/\d{2}/\d{2})\s+Fecha/Hora de emisi[oó]n:',
    'FIRMA_1': r'FIRMA_1:\s*([^\n]+)', # Placeholder for now
    'FIRMA_2': r'FIRMA_2:\s*([^\n]+)', # Placeholder for now
    'FIRMA_3': r'FIRMA_3:\s*([^\n]+)'  # Placeholder for now
}

# Regex patterns for OCR extracted text
extraction_patterns_ocr = {
    'Ejercicio': r'Ejercicio:\s*(\d{4})',
    'ORDEN DE COMPRA Nº': r'ORDEN DE COMPRA N[^]]+:\s*(\d+)',
    'Expediente Nº': r'Expediente N[\xba%º]:\s*—?(\d+)',
    'Comp.de origen': r'Comp\.de origen:\s*(\d+)',
    'Proveedor': r'Proveedor:\s*(?:\d+\s*)?([A-Z\s.,-]+?)(?=\s*Comp\.de origen|\n|Domicilio|$)',
    'CUIT': r'[Cc]UIT[^\d\n]*?(\d{1,2}\s*-\s*\d{8}\s*-\s*\d{1,2})', # Corrected for more flexibility
    'Total': r'Son Pesos:.*?Total\s*([\d\.,\s]+)',
    'FECHA_EMISION': r'Fecha/Hora de emisi[oó]n:\s*(\d{2}/\d{2}/\d{2})',
    'FIRMA_1': r'(Maria Agustina Vergara\s*Administrativo)',
    'FIRMA_2': r'(NATALIA BAREA\s*Jefa de Departamento)',
    'FIRMA_3': r'(SANDRA TENNERINI\s*Director)'
}

def extract_fields(text, patterns):
    """Extracts fields from text using a dictionary of regex patterns."""
    extracted_data = {}
    for field, pattern in patterns.items():
        match = re.search(pattern, text, re.IGNORECASE | re.DOTALL)
        if match:
            value = match.group(1)
            if value is not None:
                extracted_data[field] = value.strip()
            else:
                extracted_data[field] = None
        else:
            extracted_data[field] = None
    return extracted_data

# --- 4. Main Processing Logic ---
pdf_files = [
    '/content/DOCFI-2026-01598534-GDEMZA-ATM.pdf',
    '/content/DOCFI-2026-01624694-GDEMZA-ATM.pdf'
]

# Extract text using PyPDF2 (for initial extraction verification)
extracted_texts = {}
for pdf_file in pdf_files:
    text = extract_text_from_pdf(pdf_file)
    if text:
        extracted_texts[pdf_file] = text

# Extract fields using PyPDF2 patterns (as per initial task)
all_extracted_data_pypdf2 = []
for pdf_file, text in extracted_texts.items():
    extracted_info = extract_fields(text, extraction_patterns_pypdf2)
    all_extracted_data_pypdf2.append(extracted_info)
df_extracted_data = pd.DataFrame(all_extracted_data_pypdf2)

# Extract full OCR text for all PDFs
full_ocr_texts = {}
for pdf_file in pdf_files:
    text = extract_text_with_ocr(pdf_file, page_number=None) # Extract text from all pages
    if text:
        full_ocr_texts[pdf_file] = text

# Apply OCR-specific refined patterns
ocr_extracted_data = []
for pdf_file, text in full_ocr_texts.items():
    extracted_info = extract_fields(text, extraction_patterns_ocr)
    ocr_extracted_data.append(extracted_info)
df_ocr_extracted_data = pd.DataFrame(ocr_extracted_data)

# --- 5. Data Cleaning and Formatting ---
# Create a copy to perform cleaning operations
df_ocr_extracted_data_cleaned = df_ocr_extracted_data.copy()

# Clean signatory fields
roles_to_remove_patterns = [
    r'\s*Administrativo',
    r'\s*Jefa de Departamento',
    r'\s*Director'
]
signatory_columns = ['FIRMA_1', 'FIRMA_2', 'FIRMA_3']

for col in signatory_columns:
    df_ocr_extracted_data_cleaned[col] = df_ocr_extracted_data_cleaned[col].astype(str)
    for pattern in roles_to_remove_patterns:
        df_ocr_extracted_data_cleaned[col] = df_ocr_extracted_data_cleaned[col].str.replace(
            pattern, '', regex=True, flags=re.IGNORECASE
        )
    df_ocr_extracted_data_cleaned[col] = df_ocr_extracted_data_cleaned[col].str.replace(
        r'\n+', ' ', regex=True
    )
    df_ocr_extracted_data_cleaned[col] = df_ocr_extracted_data_cleaned[col].str.strip()
    df_ocr_extracted_data_cleaned[col] = df_ocr_extracted_data_cleaned[col].replace('None', None)

# Format 'Expediente Nº' field
def format_expediente_no(row):
    expediente_no = str(row['Expediente Nº']).strip()
    ejercicio = str(row['Ejercicio']).strip()

    if expediente_no and expediente_no != 'None' and ejercicio and ejercicio != 'None':
        expediente_no_cleaned = re.sub(r'-\s*\d{4}$', '', expediente_no).strip()
        return f"{expediente_no_cleaned}-{ejercicio}"
    elif expediente_no and expediente_no != 'None':
        return expediente_no
    else:
        return None

df_ocr_extracted_data_cleaned['Expediente Nº'] = df_ocr_extracted_data_cleaned.apply(format_expediente_no, axis=1)

# --- 6. Export to Excel ---
df_extracted_data.to_excel('extracted_data.xlsx', index=False) # Original extraction export
df_ocr_extracted_data.to_excel('ocr_extracted_data.xlsx', index=False) # OCR extraction export
df_ocr_extracted_data_cleaned.to_excel('ocr_extracted_data_cleaned.xlsx', index=False) # Cleaned OCR extraction export

print("All data processing, cleaning, and exports complete.")

"""**Reasoning**:
The previous steps have successfully installed dependencies, extracted data using both PyPDF2 and OCR, cleaned the data, and exported it to Excel files. The final instruction of the subtask is to display the contents of the `ocr_extracted_data_cleaned.xlsx` file. I will read this Excel file into a pandas DataFrame and display its contents.


"""

df_cleaned_output = pd.read_excel('ocr_extracted_data_cleaned.xlsx')
print(df_cleaned_output)

import os

# List all files in the current directory
files_in_directory = os.listdir('.')

# Check for the presence of the Excel files
expected_files = [
    'extracted_data.xlsx',
    'ocr_extracted_data.xlsx',
    'ocr_extracted_data_cleaned.xlsx'
]

print("Verificación de archivos Excel:")
for file_name in expected_files:
    if file_name in files_in_directory:
        print(f"- '{file_name}' se encontró correctamente.")
    else:
        print(f"- ¡Advertencia! '{file_name}' no se encontró.")

"""## Tarea final

### Subtask:
Confirmar la finalización exitosa del proceso de extracción, limpieza y exportación de datos de los archivos PDF.

## Summary:

### Data Analysis Key Findings

*   **Dependency Resolution**: The initial `ModuleNotFoundError` for `PyPDF2` and other libraries was resolved by correctly sequencing package installations before their import statements, ensuring all necessary components were available when called.
*   **Regex Correction**: An error, specifically `unterminated character set`, was identified and fixed in the `ORDEN DE COMPRA Nº` regex pattern for OCR extraction. The problematic `\]` within a character set was corrected to `]`, demonstrating the sensitivity of regular expressions.
*   **Successful Package Configuration**: All required packages, including `PyPDF2`, `pdfminer.six`, `tesseract-ocr`, `pytesseract`, and `pdf2image`, along with their dependencies like `poppler-utils` and `tesseract-ocr-spa`, were successfully installed or confirmed to be present.
*   **Complete Data Processing Pipeline Execution**: The entire data processing workflow, encompassing text extraction via both PyPDF2 and OCR, application of extraction patterns, data cleaning (e.g., standardizing signatory names and formatting the 'Expediente Nº' field), and export to Excel, was executed without further errors.
*   **Final Data Output**: The cleaned data was successfully exported to `ocr_extracted_data_cleaned.xlsx` and its contents displayed, confirming the successful completion of the task.

### Insights or Next Steps

*   Establish a robust dependency management strategy at the beginning of the project to avoid `ModuleNotFoundError` issues and ensure consistent environments.
*   Implement comprehensive unit tests for regex patterns to catch syntax errors early and validate their behavior against diverse text samples, especially when dealing with varied OCR outputs.
"""

df_cleaned_output = pd.read_excel('ocr_extracted_data_cleaned.xlsx')
print(df_cleaned_output)

code_to_save = """
import subprocess
import sys
import re
import pandas as pd
from PIL import Image
import numpy as np

# --- 1. Installation Functions ---
def install_package(package):
    try:
        __import__(package)
        print(f"{package} is already installed.")
    except ImportError:
        print(f"Installing {package}...")
        subprocess.check_call([sys.executable, "-m", "pip", "install", package])
        print(f"{package} installed successfully.")

# Install core PDF libraries
install_package('PyPDF2')
from PyPDF2 import PdfReader
install_package('pdfminer.six') # Though not used in final code, kept for initial context

# Install Tesseract-OCR and Spanish language pack
print("Installing Tesseract-OCR and Spanish language data...")
subprocess.run(['apt-get', 'update'], check=True)
subprocess.run(['apt-get', 'install', '-y', 'tesseract-ocr', 'tesseract-ocr-spa'], check=True)
print("Tesseract-OCR installed successfully.")

# Install pytesseract and pdf2image
install_package('pytesseract')
import pytesseract
print("Installing poppler-utils...")
subprocess.run(['apt-get', 'install', '-y', 'poppler-utils'], check=True)
print("poppler-utils installed successfully.")
install_package('pdf2image')
from pdf2image import convert_from_path
print("All necessary packages and dependencies are configured and ready.")

# --- 2. PDF Text Extraction Functions ---
def extract_text_from_pdf(pdf_path):
    """Extracts text from a given PDF file using PyPDF2."""
    try:
        reader = PdfReader(pdf_path)
        text = ""
        for page in reader.pages:
            text += page.extract_text() or ""
        return text
    except Exception as e:
        print(f"Error processing {pdf_path}: {e}")
        return None

def extract_text_with_ocr(pdf_path, page_number=None, lang='spa', area=None):
    """Extracts text from a specific page or entire PDF using OCR."""
    try:
        text = ""
        if page_number is None:
            pages = convert_from_path(pdf_path)
            for i, image in enumerate(pages):
                if area:
                    image = image.crop(area)
                text += pytesseract.image_to_string(image, lang=lang)
        else:
            pages = convert_from_path(pdf_path, first_page=page_number + 1, last_page=page_number + 1)
            if not pages:
                print(f"Error: No page found for page_number {page_number} in {pdf_path}")
                return None
            image = pages[0]
            if area:
                image = image.crop(area)
            text = pytesseract.image_to_string(image, lang=lang)

        return text.strip()
    except Exception as e:
        print(f"Error during OCR extraction from {pdf_path} (page {page_number if page_number is not None else 'all'}): {e}")
        return None

# --- 3. Field Extraction Logic ---
# Regex patterns for PyPDF2 extracted text (original text)
extraction_patterns_pypdf2 = {
    'Ejercicio': r'(\d{4})\s+\d+\s+Expediente N[\xbaº]:',
    'ORDEN DE COMPRA Nº': r'Referencia:\s*OC(\d+)\s*-',
    'Expediente Nº': r'(\d+)\s+Expediente N[\xbaº]:',
    'Comp.de origen': r'CUIT\.{{5}}:Comp\.de origen:\s*(\d+)',
    'Proveedor': r'Expediente N[\xbaº]:.*?([A-Z\s.,-]+?)(?=\s*\d{6,}\s+\d{5,}\s+\w{5,}|\nProveedor:\d{4}|\n|$)',
    'CUIT': r'(\d{1,2}-\s*\d{8}-\d{1,2})(?=CUIT\.{{5}}:{1})',
    'Total': r'([\d\.,]+)\s+Total',
    'FECHA_EMISION': r'(\d{2}/\d{2}/\d{2})\s+Fecha/Hora de emisi[oó]n:',
    'FIRMA_1': r'FIRMA_1:\s*([^\n]+)', # Placeholder for now
    'FIRMA_2': r'FIRMA_2:\s*([^\n]+)', # Placeholder for now
    'FIRMA_3': r'FIRMA_3:\s*([^\n]+)'  # Placeholder for now
}

# Regex patterns for OCR extracted text
extraction_patterns_ocr = {
    'Ejercicio': r'Ejercicio:\s*(\d{4})',
    'ORDEN DE COMPRA Nº': r'ORDEN DE COMPRA N[^]]+:\s*(\d+)',
    'Expediente Nº': r'Expediente N[\xba%º]:\s*—?(\d+)',
    'Comp.de origen': r'Comp\.de origen:\s*(\d+)',
    'Proveedor': r'Proveedor:\s*(?:\d+\s*)?([A-Z\s.,-]+?)(?=\s*Comp\.de origen|\n|Domicilio|$)',
    'CUIT': r'[Cc]UIT[^\d\n]*?(\d{1,2}\s*-\s*\d{8}\s*-\s*\d{1,2})', # Corrected for more flexibility
    'Total': r'Son Pesos:.*?Total\s*([\d\.,\s]+)',
    'FECHA_EMISION': r'Fecha/Hora de emisi[oó]n:\s*(\d{2}/\d{2}/\d{2})',
    'FIRMA_1': r'(Maria Agustina Vergara\s*Administrativo)',
    'FIRMA_2': r'(NATALIA BAREA\s*Jefa de Departamento)',
    'FIRMA_3': r'(SANDRA TENNERINI\s*Director)'
}

def extract_fields(text, patterns):
    """Extracts fields from text using a dictionary of regex patterns."""
    extracted_data = {}
    for field, pattern in patterns.items():
        match = re.search(pattern, text, re.IGNORECASE | re.DOTALL)
        if match:
            value = match.group(1)
            if value is not None:
                extracted_data[field] = value.strip()
            else:
                extracted_data[field] = None
        else:
            extracted_data[field] = None
    return extracted_data

# --- 4. Main Processing Logic ---
pdf_files = [
    '/content/DOCFI-2026-01598534-GDEMZA-ATM.pdf',
    '/content/DOCFI-2026-01624694-GDEMZA-ATM.pdf'
]

# Extract text using PyPDF2 (for initial extraction verification)
extracted_texts = {}
for pdf_file in pdf_files:
    text = extract_text_from_pdf(pdf_file)
    if text:
        extracted_texts[pdf_file] = text

# Extract fields using PyPDF2 patterns (as per initial task)
all_extracted_data_pypdf2 = []
for pdf_file, text in extracted_texts.items():
    extracted_info = extract_fields(text, extraction_patterns_pypdf2)
    all_extracted_data_pypdf2.append(extracted_info)
df_extracted_data = pd.DataFrame(all_extracted_data_pypdf2)

# Extract full OCR text for all PDFs
full_ocr_texts = {}
for pdf_file in pdf_files:
    text = extract_text_with_ocr(pdf_file, page_number=None) # Extract text from all pages
    if text:
        full_ocr_texts[pdf_file] = text

# Apply OCR-specific refined patterns
ocr_extracted_data = []
for pdf_file, text in full_ocr_texts.items():
    extracted_info = extract_fields(text, extraction_patterns_ocr)
    ocr_extracted_data.append(extracted_info)
df_ocr_extracted_data = pd.DataFrame(ocr_extracted_data)

# --- 5. Data Cleaning and Formatting ---
# Create a copy to perform cleaning operations
df_ocr_extracted_data_cleaned = df_ocr_extracted_data.copy()

# Clean signatory fields
roles_to_remove_patterns = [
    r'\s*Administrativo',
    r'\s*Jefa de Departamento',
    r'\s*Director'
]
signatory_columns = ['FIRMA_1', 'FIRMA_2', 'FIRMA_3']

for col in signatory_columns:
    df_ocr_extracted_data_cleaned[col] = df_ocr_extracted_data_cleaned[col].astype(str)
    for pattern in roles_to_remove_patterns:
        df_ocr_extracted_data_cleaned[col] = df_ocr_extracted_data_cleaned[col].str.replace(
            pattern, '', regex=True, flags=re.IGNORECASE
        )
    df_ocr_extracted_data_cleaned[col] = df_ocr_extracted_data_cleaned[col].str.replace(
        r'\n+', ' ', regex=True
    )
    df_ocr_extracted_data_cleaned[col] = df_ocr_extracted_data_cleaned[col].str.strip()
    df_ocr_extracted_data_cleaned[col] = df_ocr_extracted_data_cleaned[col].replace('None', None)

# Format 'Expediente Nº' field
def format_expediente_no(row):
    expediente_no = str(row['Expediente Nº']).strip()
    ejercicio = str(row['Ejercicio']).strip()

    if expediente_no and expediente_no != 'None' and ejercicio and ejercicio != 'None':
        expediente_no_cleaned = re.sub(r'-\s*\d{4}$', '', expediente_no).strip()
        return f"{expediente_no_cleaned}-{ejercicio}"
    elif expediente_no and expediente_no != 'None':
        return expediente_no
    else:
        return None

df_ocr_extracted_data_cleaned['Expediente Nº'] = df_ocr_extracted_data_cleaned.apply(format_expediente_no, axis=1)

# --- 6. Export to Excel ---
df_extracted_data.to_excel('extracted_data.xlsx', index=False) # Original extraction export
df_ocr_extracted_data.to_excel('ocr_extracted_data.xlsx', index=False) # OCR extraction export
df_ocr_extracted_data_cleaned.to_excel('ocr_extracted_data_cleaned.xlsx', index=False) # Cleaned OCR extraction export

print("All data processing, cleaning, and exports complete.")
"""

with open("procesador_pdfs.py", "w") as f:
    f.write(code_to_save)

print("El código se ha guardado en 'procesador_pdfs.py'.")

# Instalar PyInstaller en tu entorno (en Colab solo para demostración, pero necesitarás hacerlo en tu máquina local si no usas Colab para la compilación)
!pip install pyinstaller

"""### 3. Generar el ejecutable

Una vez que tengas tu archivo `procesador_pdfs.py` y `PyInstaller` instalado, abre una terminal (preferiblemente en Windows si quieres el ejecutable para Windows) y navega al directorio donde guardaste tu archivo `.py`. Luego, ejecuta el siguiente comando:

```bash
pyinstaller --onefile procesador_pdfs.py
```

**Explicación del comando:**

*   `pyinstaller`: Invoca la herramienta PyInstaller.
*   `--onefile`: Indica a PyInstaller que cree un solo archivo ejecutable (portable).
*   `procesador_pdfs.py`: Es el nombre de tu archivo de código Python.

### 4. Ubicación del ejecutable

Después de ejecutar el comando, PyInstaller creará varias carpetas: `build/`, `dist/`, y un archivo `.spec`. El archivo ejecutable que necesitas estará dentro de la carpeta `dist/`. Tendrá el mismo nombre que tu script Python (por ejemplo, `procesador_pdfs.exe`).

Este archivo `procesador_pdfs.exe` será un ejecutable portable que podrás llevar y ejecutar en cualquier máquina Windows sin necesidad de tener Python instalado.

### Consideraciones importantes:

*   **Dependencias:** PyInstaller intentará incluir todas las librerías de Python de las que depende tu script. Asegúrate de que todas las librerías necesarias estén instaladas en el entorno donde ejecutas `pyinstaller`.
*   **Archivos externos:** Si tu script depende de archivos externos (como los PDF que procesa o los archivos Excel que genera), el ejecutable por sí solo no los incluirá. Tendrás que distribuir esos archivos junto con el ejecutable o modificar tu código para que los busque en una ubicación relativa al ejecutable o en una ruta específica.
*   **Tesseract y Poppler:** Tu código utiliza `tesseract` y `poppler-utils` que son programas externos y no librerías de Python. PyInstaller **no** los incluirá automáticamente. Para que tu ejecutable funcione en otra máquina, esa máquina también necesitará tener `Tesseract-OCR` y `poppler-utils` instalados y configurados en su PATH.
    *   Puedes considerar distribuirlos junto con tu ejecutable e indicarle a tu programa dónde encontrarlos si no están en el PATH del sistema, usando `pytesseract.pytesseract.tesseract_cmd = r'C:\Program Files\Tesseract-OCR\tesseract.exe'` y asegurándote de que `pdf2image` pueda encontrar `poppler`.
*   **Tamaño del archivo:** El ejecutable será más grande que tu script original, ya que contiene el intérprete de Python y todas las librerías empaquetadas.
"""

df_cleaned_output = pd.read_excel('ocr_extracted_data_cleaned.xlsx')
print(df_cleaned_output)