# -*- coding: utf-8 -*-
"""Copie de CRM EXTREM

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vluTpb5YPWiQ2s1X2gwck2kALrvF3CxF
"""

# @title ⚡ Installation des dépendances (à exécuter en premier)
!pip install -q pandas numpy matplotlib seaborn plotly ipywidgets ipython openpyxl xlsxwriter reportlab fpdf
!apt-get -q install -y python3-tk
!pip install -q ipympl

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from datetime import datetime, timedelta
import ipywidgets as widgets
from IPython.display import display, HTML, clear_output
import base64
from io import BytesIO
import warnings
warnings.filterwarnings('ignore')

# Configuration du style
plt.style.use('seaborn-v0_8-darkgrid')
sns.set_palette("husl")

print("✅ Toutes les dépendances installées avec succès!")

# @title 🚀 Initialisation du CRM SNEP Extreme
# ============================================
# CRM SNEP - VERSION EXTREME POUR SERVICE COMMERCIAL
# ============================================

class SNEP_CRM_Extreme:
    """
    CRM SNEP - Solution complète pour service commercial
    Version 3.0 - Extreme Edition
    """

    def __init__(self):
        self.name = "SNEP CRM EXTREME"
        self.version = "3.0"

        # Initialisation des données
        self.clients_df = pd.DataFrame()
        self.contacts_df = pd.DataFrame()
        self.transactions_df = pd.DataFrame()
        self.produits_df = pd.DataFrame()
        self.opportunites_df = pd.DataFrame()
        self.taches_df = pd.DataFrame()

        self.init_dataframes()
        self.init_produits()

        print(f"""
╔{'═'*60}╗
║  ⚡ {self.name} - Version {self.version} ⚡
║  Service Commercial Professionnel
║  Société Nationale d'Électrolyse et de Pétrochimie
╚{'═'*60}╝
        """)

    def init_dataframes(self):
        """Initialise les structures de données"""

        # Clients
        self.clients_df = pd.DataFrame(columns=[
            'ID', 'Société', 'Secteur', 'Email', 'Téléphone', 'Adresse',
            'Ville', 'Pays', 'Code Postal', 'Site Web', 'Date Création',
            'Statut', 'Source', 'CA Annuel', 'Notes'
        ])

        # Contacts
        self.contacts_df = pd.DataFrame(columns=[
            'ID', 'Client_ID', 'Civilité', 'Nom', 'Prénom', 'Fonction',
            'Service', 'Téléphone', 'Mobile', 'Email', 'Date Naissance',
            'Notes', 'Principal'
        ])

        # Transactions
        self.transactions_df = pd.DataFrame(columns=[
            'ID', 'Date', 'Client_ID', 'Contact_ID', 'Commercial',
            'Produit', 'Catégorie', 'Unité', 'Quantité', 'Prix Unitaire',
            'CA Total', 'Devise', 'Paiement', 'Échéance', 'Statut',
            'Étape Pipeline', 'Probabilité', 'Date Clôture', 'Notes',
            'Alerte', 'Date Relance', 'Priorité'
        ])

        # Produits
        self.produits_df = pd.DataFrame(columns=[
            'ID', 'Code', 'Nom', 'Catégorie', 'Description', 'Unité',
            'Prix Unitaire', 'Devise', 'Stock', 'Seuil Alerte',
            'Fournisseur', 'Délai Livraison', 'Date Création'
        ])

        # Opportunités
        self.opportunites_df = pd.DataFrame(columns=[
            'ID', 'Client_ID', 'Contact_ID', 'Produit', 'Montant Estimé',
            'Probabilité', 'Étape', 'Date Création', 'Date Clôture Estimée',
            'Commercial', 'Concurrent', 'Notes'
        ])

        # Tâches / Relances
        self.taches_df = pd.DataFrame(columns=[
            'ID', 'Date', 'Type', 'Client_ID', 'Contact_ID', 'Sujet',
            'Description', 'Statut', 'Priorité', 'Échéance', 'Commercial'
        ])

    def init_produits(self):
        """Initialise le catalogue produits SNEP"""

        produits_snep = [
            # Chlore
            ['CHL001', 'CHLORE GAZEUX 99.5%', 'Chlore', 'Chlore gazeux haute pureté', 'TONNES', 1500, 'DHS', 1000, 100],
            ['CHL002', 'CHLORE LIQUIDE 99.8%', 'Chlore', 'Chlore liquide qualité industrielle', 'TONNES', 1800, 'DHS', 800, 50],
            ['CHL003', 'CHLORE LIQUIDE 99.9%', 'Chlore', 'Chlore liquide ultra pur', 'TONNES', 2200, 'DHS', 500, 30],

            # Soude caustique
            ['SOU001', 'SOUDE CAUSTIQUE LIQ 30%', 'Soude', 'Solution de soude 30%', 'TONNES', 800, 'DHS', 2000, 200],
            ['SOU002', 'SOUDE CAUSTIQUE LIQ 33%', 'Soude', 'Solution de soude 33%', 'TONNES', 850, 'DHS', 1500, 150],
            ['SOU003', 'SOUDE CAUSTIQUE LIQ 48%', 'Soude', 'Solution de soude 48%', 'TONNES', 950, 'DHS', 1200, 120],
            ['SOU004', 'SOUDE CAUSTIQUE LIQ 50%', 'Soude', 'Solution de soude 50%', 'TONNES', 1000, 'DHS', 1000, 100],
            ['SOU005', 'SOUDE CAUSTIQUE ECAILLES 98%', 'Soude', 'Soude en écailles 98%', 'TONNES', 1200, 'DHS', 500, 50],
            ['SOU006', 'SOUDE CAUSTIQUE ECAILLES 99%', 'Soude', 'Soude en écailles 99%', 'TONNES', 1300, 'DHS', 400, 40],

            # Acides
            ['ACI001', 'ACIDE CHLORHYDRIQUE 31%', 'Acide', 'Acide chlorhydrique 31%', 'TONNES', 600, 'DHS', 1500, 150],
            ['ACI002', 'ACIDE CHLORHYDRIQUE 32%', 'Acide', 'Acide chlorhydrique 32%', 'TONNES', 620, 'DHS', 1400, 140],
            ['ACI003', 'ACIDE CHLORHYDRIQUE 33%', 'Acide', 'Acide chlorhydrique 33%', 'TONNES', 650, 'DHS', 1300, 130],
            ['ACI004', 'ACIDE CHLORHYDRIQUE 35%', 'Acide', 'Acide chlorhydrique 35%', 'TONNES', 700, 'DHS', 1000, 100],
            ['ACI005', 'ACIDE SULFURIQUE 96%', 'Acide', 'Acide sulfurique 96%', 'TONNES', 550, 'DHS', 2000, 200],
            ['ACI006', 'ACIDE SULFURIQUE 98%', 'Acide', 'Acide sulfurique 98%', 'TONNES', 600, 'DHS', 1800, 180],
            ['ACI007', 'ACIDE NITRIQUE 53%', 'Acide', 'Acide nitrique 53%', 'TONNES', 750, 'DHS', 800, 80],
            ['ACI008', 'ACIDE NITRIQUE 56%', 'Acide', 'Acide nitrique 56%', 'TONNES', 800, 'DHS', 700, 70],

            # Eau de Javel
            ['JAV001', 'EAU DE JAVEL 12°', 'Javel', 'Eau de Javel 12° chl', 'LITRES', 2.5, 'DHS', 5000, 500],
            ['JAV002', 'EAU DE JAVEL 15°', 'Javel', 'Eau de Javel 15° chl', 'LITRES', 3.0, 'DHS', 4000, 400],
            ['JAV003', 'EAU DE JAVEL 24°', 'Javel', 'Eau de Javel 24° chl', 'LITRES', 3.8, 'DHS', 3000, 300],
            ['JAV004', 'EAU DE JAVEL 36°', 'Javel', 'Eau de Javel 36° chl', 'LITRES', 4.2, 'DHS', 2000, 200],
            ['JAV005', 'EAU DE JAVEL 48°', 'Javel', 'Eau de Javel 48° chl', 'LITRES', 4.8, 'DHS', 1500, 150],
            ['JAV006', 'EAU DE JAVEL 50°', 'Javel', 'Eau de Javel 50° chl', 'LITRES', 5.2, 'DHS', 1000, 100],

            # PVC
            ['PVC001', 'PVC SUSPENSION S60', 'PVC', 'PVC suspension S60', 'TONNES', 1100, 'DHS', 800, 80],
            ['PVC002', 'PVC SUSPENSION S65', 'PVC', 'PVC suspension S65', 'TONNES', 1150, 'DHS', 750, 75],
            ['PVC003', 'PVC SUSPENSION S67', 'PVC', 'PVC suspension S67', 'TONNES', 1200, 'DHS', 700, 70],
            ['PVC004', 'PVC EMULSION', 'PVC', 'PVC émulsion', 'TONNES', 1300, 'DHS', 600, 60],
            ['PVC005', 'PVC COMPOUND', 'PVC', 'PVC compound', 'TONNES', 1400, 'DHS', 500, 50],

            # Autres
            ['AUT001', 'HYPOPHOSPHITE DE SODIUM', 'Autre', 'Hypophosphite de sodium', 'TONNES', 2000, 'DHS', 300, 30],
            ['AUT002', 'PHOSPHATE TRISODIQUE', 'Autre', 'Phosphate trisodique', 'TONNES', 1800, 'DHS', 400, 40],
            ['AUT003', 'CHLORURE FERRIQUE', 'Autre', 'Chlorure ferrique', 'TONNES', 1600, 'DHS', 500, 50],
            ['AUT004', 'SULFATE DALUMINIUM', 'Autre', 'Sulfate d\'aluminium', 'TONNES', 1400, 'DHS', 600, 60],
            ['AUT005', 'CHLORURE DE CALCIUM', 'Autre', 'Chlorure de calcium', 'TONNES', 1200, 'DHS', 700, 70],
            ['AUT006', 'EAU OXYGÉNÉE 35%', 'Autre', 'Eau oxygénée 35%', 'LITRES', 8.5, 'DHS', 2000, 200],
            ['AUT007', 'EAU OXYGÉNÉE 50%', 'Autre', 'Eau oxygénée 50%', 'LITRES', 12.0, 'DHS', 1500, 150]
        ]

        df = pd.DataFrame(produits_snep, columns=[
            'Code', 'Nom', 'Catégorie', 'Description', 'Unité',
            'Prix Unitaire', 'Devise', 'Stock', 'Seuil Alerte'
        ])
        df.insert(0, 'ID', range(1, len(df) + 1))
        df['Date Création'] = datetime.now().strftime('%Y-%m-%d')

        self.produits_df = df

        print(f"📦 {len(self.produits_df)} produits SNEP chargés")

    def ajouter_client(self, societe, secteur='', email='', telephone='',
                       ville='Casablanca', pays='Maroc', statut='Prospect'):
        """Ajoute un nouveau client"""

        id_client = len(self.clients_df) + 1
        date_creation = datetime.now().strftime('%Y-%m-%d')

        nouveau_client = pd.DataFrame([{
            'ID': id_client,
            'Société': societe,
            'Secteur': secteur,
            'Email': email,
            'Téléphone': telephone,
            'Adresse': '',
            'Ville': ville,
            'Pays': pays,
            'Code Postal': '',
            'Site Web': '',
            'Date Création': date_creation,
            'Statut': statut,
            'Source': '',
            'CA Annuel': 0,
            'Notes': ''
        }])

        self.clients_df = pd.concat([self.clients_df, nouveau_client], ignore_index=True)
        return id_client

    def ajouter_transaction(self, client_id, produit, quantite, prix_unitaire,
                             paiement='', echeance='', commercial='OUSSAMA RAMZI'):
        """Ajoute une nouvelle transaction"""

        id_transaction = len(self.transactions_df) + 1
        date = datetime.now().strftime('%Y-%m-%d')
        ca_total = quantite * prix_unitaire

        # Trouver la catégorie du produit
        produit_info = self.produits_df[self.produits_df['Nom'] == produit]
        if len(produit_info) > 0:
            categorie = produit_info.iloc[0]['Catégorie']
            unite = produit_info.iloc[0]['Unité']
        else:
            categorie = 'Autre'
            unite = 'Unité'

        # Déterminer l'alerte
        alerte = self._determiner_alerte(paiement)

        # Date de relance
        date_relance = ''
        if 'CHÈQUE' in paiement.upper() or 'CHEQUE' in paiement.upper():
            date_relance = (datetime.now() + timedelta(days=21)).strftime('%Y-%m-%d')

        nouvelle_transaction = pd.DataFrame([{
            'ID': id_transaction,
            'Date': date,
            'Client_ID': client_id,
            'Contact_ID': '',
            'Commercial': commercial,
            'Produit': produit,
            'Catégorie': categorie,
            'Unité': unite,
            'Quantité': quantite,
            'Prix Unitaire': prix_unitaire,
            'CA Total': ca_total,
            'Devise': 'DHS',
            'Paiement': paiement,
            'Échéance': echeance,
            'Statut': 'En cours',
            'Étape Pipeline': 'Prospection',
            'Probabilité': 50,
            'Date Clôture': '',
            'Notes': '',
            'Alerte': alerte,
            'Date Relance': date_relance,
            'Priorité': 'Moyenne'
        }])

        self.transactions_df = pd.concat([self.transactions_df, nouvelle_transaction], ignore_index=True)

        # Mettre à jour le CA du client
        client_idx = self.clients_df[self.clients_df['ID'] == client_id].index
        if len(client_idx) > 0:
            self.clients_df.loc[client_idx, 'CA Annuel'] += ca_total
            if self.clients_df.loc[client_idx, 'Statut'].values[0] == 'Prospect':
                self.clients_df.loc[client_idx, 'Statut'] = 'Client actif'

        return id_transaction

    def _determiner_alerte(self, paiement):
        """Détermine l'alerte en fonction du paiement"""
        paiement_upper = paiement.upper()

        if 'RETARD' in paiement_upper:
            return '🔴 URGENT'
        elif 'CHÈQUE' in paiement_upper or 'CHEQUE' in paiement_upper:
            return '🟡 À SURVEILLER'
        elif 'LITIGE' in paiement_upper:
            return '🔴 LITIGE'
        elif 'COMPTANT' in paiement_upper:
            return '🟢 OK'
        else:
            return '✓ SUIVI'

    def generer_donnees_test(self, nb_clients=20, nb_transactions=50):
        """Génère des données de test pour démonstration"""

        import random

        # Liste de clients types
        clients_liste = [
            ('ONEE', 'Énergie'), ('LYDEC', 'Eau'), ('OCP GROUP', 'Mines'),
            ('COSUMAR', 'Agroalimentaire'), ('LESIEUR CRISTAL', 'Agroalimentaire'),
            ('MAGHREB STEEL', 'Métallurgie'), ('DIMATIT', 'BTP'), ('AQUAPLAST', 'Plastique'),
            ('MAROC PVC', 'Plastique'), ('BATIGLOB', 'BTP'), ('NEXANS MAROC', 'Câblerie'),
            ('TGCC', 'BTP'), ('JET CONTRACTORS', 'BTP'), ('SGTM', 'BTP'),
            ('SONASID', 'Métallurgie'), ('MANAGEM', 'Mines'), ('SNEP', 'Industrie'),
            ('SNRT', 'Média'), ('ONCF', 'Transport'), ('BMCE', 'Banque'),
            ('BANQUE POPULAIRE', 'Banque'), ('ATTIJARIWAFA BANK', 'Banque'),
            ('CIH', 'Banque'), ('CDG', 'Finance'), ('MUTUELLE', 'Assurance'),
            ('CNSS', 'Social'), ('TOTAL MAROC', 'Énergie'), ('SHELL MAROC', 'Énergie'),
            ('AFRIQUIA', 'Énergie'), ('HOLCIM', 'Ciment'), ('LAFARGE', 'Ciment'),
            ('CIMENTS DU MAROC', 'Ciment'), ('YAZAKI', 'Automobile'), ('LEONI', 'Automobile')
        ]

        # Produits disponibles
        produits_disponibles = self.produits_df['Nom'].tolist()

        # Modes de paiement
        paiements = ['COMPTANT', 'CHÈQUE 30j', 'CHÈQUE 45j', 'CHÈQUE 60j',
                     'VIREMENT', 'EFFET', 'LCR', 'CRÉDIT DOC']

        # Ajouter des clients
        for i in range(min(nb_clients, len(clients_liste))):
            societe, secteur = clients_liste[i]
            self.ajouter_client(societe, secteur,
                                f'contact@{societe.lower().replace(" ", "")}.ma',
                                f'05{random.randint(10, 99)}-{random.randint(10, 99)}-{random.randint(10, 99)}',
                                statut=random.choice(['Prospect', 'Client actif', 'Client inactif']))

        # Ajouter des transactions
        for _ in range(nb_transactions):
            client_id = random.randint(1, min(nb_clients, len(clients_liste)))
            produit = random.choice(produits_disponibles)

            # Trouver le prix du produit
            prix_info = self.produits_df[self.produits_df['Nom'] == produit]
            if len(prix_info) > 0:
                prix = prix_info.iloc[0]['Prix Unitaire']
            else:
                prix = random.uniform(500, 2000)

            quantite = random.randint(1, 100)
            paiement = random.choice(paiements)
            echeance = random.choice(['Comptant', '30j', '45j', '60j', '90j'])

            self.ajouter_transaction(client_id, produit, quantite, prix, paiement, echeance)

        print(f"✅ {min(nb_clients, len(clients_liste))} clients de test créés")
        print(f"✅ {nb_transactions} transactions de test créées")

# Création de l'instance CRM
crm = SNEP_CRM_Extreme()

# Génération de données de test
crm.generer_donnees_test(nb_clients=30, nb_transactions=100)

# @title ⚡ ÉTAPE 1 - Installation des dépendances
!pip install -q pandas numpy matplotlib seaborn plotly ipywidgets ipython openpyxl xlsxwriter
!apt-get -q install -y python3-tk

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime, timedelta
import ipywidgets as widgets
from IPython.display import display, HTML, clear_output

print("✅ Environnement prêt")

# @title 🚀 ÉTAPE 2 - Initialisation du CRM
class SNEP_CRM_Extreme:
    def __init__(self):
        self.name = "SNEP CRM EXTREME"
        self.version = "3.0"
        self.clients_df = pd.DataFrame()
        self.transactions_df = pd.DataFrame()
        self.produits_df = pd.DataFrame()
        self.init_produits()
        print(f"\n╔{'═'*50}╗")
        print(f"║  ⚡ {self.name} - Version {self.version} ⚡".ljust(51) + "║")
        print(f"╚{'═'*50}╝\n")

    def init_produits(self):
        produits = [
            ['CHLORE GAZEUX 99.5%', 'Chlore', 'TONNES', 1500],
            ['CHLORE LIQUIDE 99.8%', 'Chlore', 'TONNES', 1800],
            ['SOUDE CAUSTIQUE LIQ 30%', 'Soude', 'TONNES', 800],
            ['SOUDE CAUSTIQUE LIQ 48%', 'Soude', 'TONNES', 950],
            ['ACIDE CHLORHYDRIQUE 31%', 'Acide', 'TONNES', 600],
            ['EAU DE JAVEL 12°', 'Javel', 'LITRES', 2.5],
            ['PVC SUSPENSION S60', 'PVC', 'TONNES', 1200],
        ]
        self.produits_df = pd.DataFrame(produits, columns=['Nom', 'Catégorie', 'Unité', 'Prix'])
        print(f"📦 {len(self.produits_df)} produits chargés")

    def ajouter_client(self, societe, secteur='', email='', telephone='', ville='Casablanca'):
        id_client = len(self.clients_df) + 1
        nouveau = pd.DataFrame([{
            'ID': id_client, 'Société': societe, 'Secteur': secteur,
            'Email': email, 'Téléphone': telephone, 'Ville': ville,
            'Date': datetime.now().strftime('%Y-%m-%d')
        }])
        self.clients_df = pd.concat([self.clients_df, nouveau], ignore_index=True)
        return id_client

    def ajouter_transaction(self, client_id, produit, quantite, prix, paiement='COMPTANT'):
        id_trans = len(self.transactions_df) + 1
        ca = quantite * prix
        alerte = '✓ SUIVI'
        if 'CHÈQUE' in paiement.upper() or 'CHEQUE' in paiement.upper():
            alerte = '🟡 À SURVEILLER'

        nouvelle = pd.DataFrame([{
            'ID': id_trans, 'Date': datetime.now().strftime('%Y-%m-%d'),
            'Client_ID': client_id, 'Produit': produit, 'Quantité': quantite,
            'Prix': prix, 'CA': ca, 'Paiement': paiement, 'Alerte': alerte
        }])
        self.transactions_df = pd.concat([self.transactions_df, nouvelle], ignore_index=True)
        return id_trans

    def generer_donnees_test(self):
        clients = ['ONEE', 'LYDEC', 'OCP', 'COSUMAR', 'LESIEUR']
        for c in clients:
            self.ajouter_client(c)

        for _ in range(15):
            client = np.random.randint(1, 6)
            produit = np.random.choice(self.produits_df['Nom'].tolist())
            prix = self.produits_df[self.produits_df['Nom'] == produit]['Prix'].values[0]
            qte = np.random.randint(10, 100)
            paiement = np.random.choice(['COMPTANT', 'CHÈQUE 30j'])
            self.ajouter_transaction(client, produit, qte, prix, paiement)

        print("✅ Données de test générées")

# @title 🏠 ÉTAPE 3 - Interface graphique
class CRMInterface:
    def __init__(self, crm):
        self.crm = crm
        self.create_interface()

    def create_interface(self):
        # Style
        display(HTML("""
        <style>
        .tab { margin: 10px; }
        button { margin: 5px; padding: 10px; }
        </style>
        """))

        # Onglets
        self.tab = widgets.Tab()
        self.tab.children = [
            self.create_dashboard(),
            self.create_clients(),
            self.create_transactions(),
            self.create_alertes()
        ]
        self.tab.set_title(0, '📊 Tableau de bord')
        self.tab.set_title(1, '👥 Clients')
        self.tab.set_title(2, '💰 Transactions')
        self.tab.set_title(3, '⚠️ Alertes')
        display(self.tab)

    def create_dashboard(self):
        container = widgets.VBox()
        children = []

        # KPI
        ca_total = self.crm.transactions_df['CA'].sum() if len(self.crm.transactions_df) > 0 else 0
        nb_trans = len(self.crm.transactions_df)
        nb_clients = len(self.crm.clients_df)

        kpi_html = f"""
        <div style='display:flex; justify-content:space-around; margin:20px;'>
            <div style='background:#667eea; color:white; padding:20px; border-radius:10px; width:200px; text-align:center;'>
                <h2>💰 CA Total</h2>
                <h1>{ca_total:,.0f} DHS</h1>
            </div>
            <div style='background:#764ba2; color:white; padding:20px; border-radius:10px; width:200px; text-align:center;'>
                <h2>📊 Transactions</h2>
                <h1>{nb_trans}</h1>
            </div>
            <div style='background:#f39c12; color:white; padding:20px; border-radius:10px; width:200px; text-align:center;'>
                <h2>👥 Clients</h2>
                <h1>{nb_clients}</h1>
            </div>
        </div>
        """
        children.append(widgets.HTML(kpi_html))

        # Dernières transactions
        if len(self.crm.transactions_df) > 0:
            html = "<h3>📋 Dernières transactions</h3>"
            html += self.crm.transactions_df.tail(5).to_html(index=False)
            children.append(widgets.HTML(html))

        container.children = children
        return container

    def create_clients(self):
        container = widgets.VBox()

        # Bouton ajouter
        btn_add = widgets.Button(description='➕ Nouveau Client', button_style='success')

        def on_add_click(b):
            self.show_add_client_form()
        btn_add.on_click(on_add_click)

        container.children = [btn_add]

        # Liste clients
        if len(self.crm.clients_df) > 0:
            html = "<h3>Liste des clients</h3>"
            html += self.crm.clients_df.to_html(index=False)
            container.children += (widgets.HTML(html),)

        return container

    def show_add_client_form(self):
        form = widgets.VBox()

        societe = widgets.Text(description='Société:')
        secteur = widgets.Text(description='Secteur:')
        email = widgets.Text(description='Email:')
        telephone = widgets.Text(description='Téléphone:')
        ville = widgets.Text(description='Ville:', value='Casablanca')

        def save(b):
            self.crm.ajouter_client(
                societe.value, secteur.value, email.value,
                telephone.value, ville.value
            )
            clear_output(wait=True)
            self.create_interface()

        btn_save = widgets.Button(description='💾 Enregistrer', button_style='success')
        btn_save.on_click(save)

        form.children = [societe, secteur, email, telephone, ville, btn_save]
        display(form)

    def create_transactions(self):
        container = widgets.VBox()

        # Formulaire
        if len(self.crm.clients_df) > 0 and len(self.crm.produits_df) > 0:
            clients = [f"{row['ID']} - {row['Société']}" for _, row in self.crm.clients_df.iterrows()]
            client_select = widgets.Dropdown(options=clients, description='Client:')

            produits = self.crm.produits_df['Nom'].tolist()
            produit_select = widgets.Dropdown(options=produits, description='Produit:')

            quantite = widgets.FloatText(value=1, description='Quantité:')
            prix = widgets.FloatText(description='Prix:')
            paiement = widgets.Dropdown(
                options=['COMPTANT', 'CHÈQUE 30j', 'CHÈQUE 45j', 'VIREMENT'],
                description='Paiement:'
            )

            # Auto-fill prix
            def update_price(change):
                if change['new']:
                    p = self.crm.produits_df[self.crm.produits_df['Nom'] == change['new']]['Prix'].values[0]
                    prix.value = p
            produit_select.observe(update_price, names='value')

            def save_transaction(b):
                client_id = int(client_select.value.split(' - ')[0])
                self.crm.ajouter_transaction(
                    client_id, produit_select.value, quantite.value,
                    prix.value, paiement.value
                )
                clear_output(wait=True)
                self.create_interface()

            btn_save = widgets.Button(description='📥 Enregistrer', button_style='success')
            btn_save.on_click(save_transaction)

            container.children = [
                widgets.HTML("<h3>➕ Nouvelle transaction</h3>"),
                client_select, produit_select, quantite, prix, paiement, btn_save
            ]

        # Liste transactions
        if len(self.crm.transactions_df) > 0:
            html = "<h3>📋 Historique</h3>"
            html += self.crm.transactions_df.to_html(index=False)
            container.children += (widgets.HTML(html),)

        return container

    def create_alertes(self):
        container = widgets.VBox()

        if len(self.crm.transactions_df) > 0:
            # Alertes urgentes
            urgentes = self.crm.transactions_df[
                self.crm.transactions_df['Alerte'].str.contains('🟡', na=False)
            ]
            if len(urgentes) > 0:
                html = "<h3 style='color:red;'>🔴 Alertes à surveiller</h3>"
                html += urgentes.to_html(index=False)
                container.children += (widgets.HTML(html),)

            # Chèques
            cheques = self.crm.transactions_df[
                self.crm.transactions_df['Paiement'].str.contains('CHÈQUE|CHEQUE', na=False)
            ]
            if len(cheques) > 0:
                html = "<h3 style='color:orange;'>🟡 Chèques en cours</h3>"
                html += cheques.to_html(index=False)
                container.children += (widgets.HTML(html),)

        return container

# @title 🎬 ÉTAPE 4 - Démarrer l'application
# Créer l'instance CRM
crm = SNEP_CRM_Extreme()

# Générer des données de test
crm.generer_donnees_test()

# Lancer l'interface
interface = CRMInterface(crm)

print("\n✅ Application prête ! Utilisez les onglets ci-dessus 👆")

# @title 💾 ÉTAPE 5 - Exporter les données
if len(crm.transactions_df) > 0:
    # Export Excel
    filename = f"snep_crm_export_{datetime.now().strftime('%Y%m%d_%H%M%S')}.xlsx"
    with pd.ExcelWriter(filename) as writer:
        crm.clients_df.to_excel(writer, sheet_name='Clients', index=False)
        crm.produits_df.to_excel(writer, sheet_name='Produits', index=False)
        crm.transactions_df.to_excel(writer, sheet_name='Transactions', index=False)

    print(f"✅ Fichier créé : {filename}")
    print("📁 Cliquez sur l'icône dossier à gauche pour télécharger")
else:
    print("❌ Ajoutez d'abord des transactions")

# @title 🏠 Interface Principale du CRM
# ============================================
# INTERFACE PRINCIPALE
# ============================================

from IPython.display import display, HTML, clear_output
import ipywidgets as widgets
from datetime import datetime, timedelta

class CRMInterface:
    """
    Interface utilisateur du CRM SNEP
    """

    def __init__(self, crm):
        self.crm = crm
        self.current_user = "OUSSAMA RAMZI"
        self.create_interface()

    def create_interface(self):
        """Crée l'interface principale avec onglets"""

        # Style CSS
        display(HTML("""
        <style>
        .crm-container {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            max-width: 1400px;
            margin: 0 auto;
        }
        .crm-header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 20px;
            border-radius: 10px;
            margin-bottom: 20px;
            text-align: center;
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        }
        .crm-header h1 {
            margin: 0;
            font-size: 28px;
            font-weight: bold;
        }
        .crm-header p {
            margin: 5px 0 0;
            opacity: 0.9;
        }
        .kpi-card {
            background: white;
            border-radius: 10px;
            padding: 15px;
            margin: 10px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            text-align: center;
            transition: transform 0.3s;
        }
        .kpi-card:hover {
            transform: translateY(-5px);
            box-shadow: 0 4px 8px rgba(0,0,0,0.15);
        }
        .kpi-value {
            font-size: 24px;
            font-weight: bold;
            color: #667eea;
        }
        .kpi-label {
            font-size: 14px;
            color: #666;
            margin-top: 5px;
        }
        .alert-card {
            background: #fee;
            border-left: 4px solid #f00;
        }
        .success-card {
            background: #efe;
            border-left: 4px solid #0f0;
        }
        </style>
        """))

        # Header
        display(HTML(f"""
        <div class="crm-header">
            <h1>⚡ SNEP CRM EXTREME - Service Commercial</h1>
            <p>Société Nationale d'Électrolyse et de Pétrochimie | Commercial: {self.current_user} | {datetime.now().strftime('%d/%m/%Y %H:%M')}</p>
        </div>
        """))

        # Création des onglets
        self.tab = widgets.Tab()

        # Contenu des onglets
        self.tab.children = [
            self.create_dashboard_tab(),
            self.create_clients_tab(),
            self.create_produits_tab(),
            self.create_transactions_tab(),
            self.create_pipeline_tab(),
            self.create_rapports_tab(),
            self.create_alertes_tab()
        ]

        # Titres des onglets
        self.tab.set_title(0, '📊 Tableau de bord')
        self.tab.set_title(1, '👥 Clients')
        self.tab.set_title(2, '📦 Produits')
        self.tab.set_title(3, '💰 Transactions')
        self.tab.set_title(4, '📈 Pipeline')
        self.tab.set_title(5, '📋 Rapports')
        self.tab.set_title(6, '⚠️ Alertes')

        display(self.tab)

    def create_dashboard_tab(self):
        """Crée l'onglet Tableau de bord"""
        container = widgets.VBox()
        children = []

        # Ligne des KPI
        kpi_row = widgets.HBox()
        kpi_children = []

        # Calcul des KPI
        ca_total = self.crm.transactions_df['CA Total'].sum() if len(self.crm.transactions_df) > 0 else 0
        nb_transactions = len(self.crm.transactions_df)
        nb_clients = len(self.crm.clients_df)
        nb_alertes = len(self.crm.transactions_df[self.crm.transactions_df['Alerte'].str.contains('URGENT', na=False)])

        kpi_data = [
            ('💰 CA Total', f"{ca_total:,.0f} DHS", '#667eea'),
            ('📊 Transactions', str(nb_transactions), '#764ba2'),
            ('👥 Clients', str(nb_clients), '#f39c12'),
            ('⚠️ Alertes', str(nb_alertes), '#e74c3c')
        ]

        for label, value, color in kpi_data:
            card = widgets.VBox([
                widgets.HTML(value=f"<div style='font-size:24px; font-weight:bold; color:{color};'>{value}</div>"),
                widgets.HTML(value=f"<div style='font-size:14px; color:#666;'>{label}</div>")
            ])
            card.layout = widgets.Layout(
                border='1px solid #ddd',
                border_radius='10px',
                padding='15px',
                margin='5px',
                width='200px',
                align_items='center'
            )
            kpi_children.append(card)

        kpi_row.children = kpi_children
        kpi_row.layout.justify_content = 'center'
        children.append(kpi_row)

        # Graphiques
        graph_row = widgets.HBox()

        # Graphique 1: Évolution du CA
        fig1, ax1 = plt.subplots(figsize=(8, 4))
        if len(self.crm.transactions_df) > 0:
            self.crm.transactions_df.groupby('Date')['CA Total'].sum().plot(
                kind='line', marker='o', ax=ax1, color='#667eea'
            )
            ax1.set_title('Évolution du Chiffre d\'Affaires')
            ax1.set_xlabel('Date')
            ax1.set_ylabel('CA (DHS)')
            plt.xticks(rotation=45)
        else:
            ax1.text(0.5, 0.5, 'Aucune donnée disponible', ha='center', va='center')

        # Graphique 2: Répartition par catégorie
        fig2, ax2 = plt.subplots(figsize=(8, 4))
        if len(self.crm.transactions_df) > 0:
            self.crm.transactions_df.groupby('Catégorie')['CA Total'].sum().plot(
                kind='pie', autopct='%1.1f%%', ax=ax2, colors=sns.color_palette('husl', 8)
            )
            ax2.set_title('Répartition du CA par Catégorie')
            ax2.set_ylabel('')
        else:
            ax2.text(0.5, 0.5, 'Aucune donnée disponible', ha='center', va='center')

        graph_row.children = [
            widgets.Output(layout=widgets.Layout(width='50%')),
            widgets.Output(layout=widgets.Layout(width='50%'))
        ]

        with graph_row.children[0]:
            plt.show(fig1)
        with graph_row.children[1]:
            plt.show(fig2)

        children.append(graph_row)

        # Tableau des dernières transactions
        children.append(widgets.HTML("<h3>📋 Dernières transactions</h3>"))

        if len(self.crm.transactions_df) > 0:
            last_trans = self.crm.transactions_df.tail(10)[['Date', 'Produit', 'Quantité', 'CA Total', 'Statut', 'Alerte']]
            children.append(widgets.HTML(last_trans.to_html(index=False, escape=False)))

        container.children = children
        return container

    def create_clients_tab(self):
        """Crée l'onglet Clients"""
        container = widgets.VBox()
        children = []

        # Boutons d'action
        button_row = widgets.HBox()

        btn_add = widgets.Button(
            description='➕ Nouveau Client',
            button_style='success',
            layout=widgets.Layout(width='150px', margin='5px')
        )
        btn_add.on_click(self.add_client_click)

        btn_refresh = widgets.Button(
            description='🔄 Actualiser',
            button_style='info',
            layout=widgets.Layout(width='150px', margin='5px')
        )
        btn_refresh.on_click(self.refresh_clients)

        search_input = widgets.Text(
            placeholder='Rechercher un client...',
            layout=widgets.Layout(width='300px', margin='5px')
        )

        button_row.children = [btn_add, btn_refresh, search_input]
        children.append(button_row)

        # Tableau des clients
        children.append(widgets.HTML("<h3>Liste des clients</h3>"))

        if len(self.crm.clients_df) > 0:
            clients_display = self.crm.clients_df[['ID', 'Société', 'Secteur', 'Email', 'Téléphone', 'Ville', 'Statut', 'CA Annuel']]
            children.append(widgets.HTML(clients_display.to_html(index=False, escape=False)))
        else:
            children.append(widgets.HTML("<p>Aucun client enregistré</p>"))

        container.children = children
        return container

    def add_client_click(self, b):
        """Callback pour ajouter un client"""

        dialog = widgets.VBox()

        # Champs du formulaire
        fields = {}
        field_labels = ['Société', 'Secteur', 'Email', 'Téléphone', 'Ville', 'Pays']

        for label in field_labels:
            fields[label] = widgets.Text(description=label + ':', layout=widgets.Layout(width='400px'))

        def save_client(btn):
            self.crm.ajouter_client(
                societe=fields['Société'].value,
                secteur=fields['Secteur'].value,
                email=fields['Email'].value,
                telephone=fields['Téléphone'].value,
                ville=fields['Ville'].value,
                pays=fields['Pays'].value
            )
            self.refresh_clients(None)
            close_dialog(btn)

        def close_dialog(btn):
            for child in dialog.children:
                child.close()

        btn_save = widgets.Button(description='💾 Enregistrer', button_style='success')
        btn_save.on_click(save_client)

        btn_cancel = widgets.Button(description='❌ Annuler', button_style='danger')
        btn_cancel.on_click(close_dialog)

        button_row = widgets.HBox([btn_save, btn_cancel])

        children = list(fields.values()) + [button_row]
        dialog.children = children

        display(dialog)

    def refresh_clients(self, b):
        """Rafraîchit l'affichage des clients"""
        clear_output(wait=True)
        self.create_interface()

    def create_produits_tab(self):
        """Crée l'onglet Produits"""
        container = widgets.VBox()
        children = []

        children.append(widgets.HTML("<h3>📦 Catalogue Produits SNEP</h3>"))

        if len(self.crm.produits_df) > 0:
            produits_display = self.crm.produits_df[['Code', 'Nom', 'Catégorie', 'Unité', 'Prix Unitaire', 'Devise', 'Stock']]
            children.append(widgets.HTML(produits_display.to_html(index=False, escape=False)))
        else:
            children.append(widgets.HTML("<p>Aucun produit enregistré</p>"))

        container.children = children
        return container

    def create_transactions_tab(self):
        """Crée l'onglet Transactions"""
        container = widgets.VBox()
        children = []

        # Formulaire de transaction
        children.append(widgets.HTML("<h3>➕ Nouvelle transaction</h3>"))

        form = widgets.VBox()
        form_fields = []

        # Sélection client
        if len(self.crm.clients_df) > 0:
            clients_list = [f"{row['ID']} - {row['Société']}" for _, row in self.crm.clients_df.iterrows()]
            client_select = widgets.Dropdown(
                options=clients_list,
                description='Client:',
                layout=widgets.Layout(width='400px')
            )
            form_fields.append(client_select)
        else:
            client_select = None

        # Sélection produit
        if len(self.crm.produits_df) > 0:
            produits_list = self.crm.produits_df['Nom'].tolist()
            produit_select = widgets.Dropdown(
                options=produits_list,
                description='Produit:',
                layout=widgets.Layout(width='400px')
            )
            form_fields.append(produit_select)
        else:
            produit_select = None

        # Quantité
        quantite_input = widgets.FloatText(
            value=1.0,
            description='Quantité:',
            layout=widgets.Layout(width='400px')
        )
        form_fields.append(quantite_input)

        # Prix (sera pré-rempli si produit sélectionné)
        prix_input = widgets.FloatText(
            value=0.0,
            description='Prix unitaire:',
            layout=widgets.Layout(width='400px')
        )
        form_fields.append(prix_input)

        # Mise à jour automatique du prix
        def update_price(change):
            if produit_select and change['new']:
                produit_info = self.crm.produits_df[self.crm.produits_df['Nom'] == change['new']]
                if len(produit_info) > 0:
                    prix_input.value = produit_info.iloc[0]['Prix Unitaire']

        if produit_select:
            produit_select.observe(update_price, names='value')

        # Paiement
        paiement_input = widgets.Dropdown(
            options=['COMPTANT', 'CHÈQUE 30j', 'CHÈQUE 45j', 'CHÈQUE 60j', 'VIREMENT', 'EFFET', 'LCR', 'CRÉDIT DOC'],
            description='Paiement:',
            layout=widgets.Layout(width='400px')
        )
        form_fields.append(paiement_input)

        # Échéance
        echeance_input = widgets.Dropdown(
            options=['Comptant', '30j', '45j', '60j', '90j', '120j'],
            description='Échéance:',
            layout=widgets.Layout(width='400px')
        )
        form_fields.append(echeance_input)

        form.children = form_fields
        children.append(form)

        # Bouton d'enregistrement
        def save_transaction(btn):
            if not client_select or not produit_select:
                print("❌ Données insuffisantes")
                return

            client_id = int(client_select.value.split(' - ')[0])
            self.crm.ajouter_transaction(
                client_id=client_id,
                produit=produit_select.value,
                quantite=quantite_input.value,
                prix_unitaire=prix_input.value,
                paiement=paiement_input.value,
                echeance=echeance_input.value
            )
            print("✅ Transaction enregistrée avec succès!")

        btn_save = widgets.Button(
            description='📥 Enregistrer transaction',
            button_style='success',
            layout=widgets.Layout(width='200px', margin='10px')
        )
        btn_save.on_click(save_transaction)
        children.append(btn_save)

        # Tableau des transactions
        children.append(widgets.HTML("<h3>📋 Historique des transactions</h3>"))

        if len(self.crm.transactions_df) > 0:
            trans_display = self.crm.transactions_df[['Date', 'Produit', 'Quantité', 'CA Total', 'Paiement', 'Statut', 'Alerte']]
            children.append(widgets.HTML(trans_display.to_html(index=False, escape=False)))
        else:
            children.append(widgets.HTML("<p>Aucune transaction enregistrée</p>"))

        container.children = children
        return container

    def create_pipeline_tab(self):
        """Crée l'onglet Pipeline commercial"""
        container = widgets.VBox()
        children = []

        children.append(widgets.HTML("<h3>📈 Pipeline des opportunités</h3>"))

        if len(self.crm.transactions_df) > 0:
            # Créer un tableau Kanban simplifié
            etapes = ['Prospection', 'Contact', 'RDV', 'Devis', 'Négociation', 'Gagné', 'Perdu']

            for etape in etapes:
                etape_trans = self.crm.transactions_df[
                    (self.crm.transactions_df['Étape Pipeline'] == etape) |
                    (self.crm.transactions_df['Statut'] == etape)
                ]

                if len(etape_trans) > 0:
                    montant_total = etape_trans['CA Total'].sum()
                    children.append(widgets.HTML(f"<h4>{etape} - {len(etape_trans)} opp. - {montant_total:,.0f} DHS</h4>"))

                    for _, trans in etape_trans.iterrows():
                        card = widgets.VBox([
                            widgets.HTML(f"<b>{trans['Produit']}</b>"),
                            widgets.HTML(f"Montant: {trans['CA Total']:,.0f} DHS"),
                            widgets.HTML(f"Client: {trans['Client_ID']}"),
                            widgets.HTML(f"Probabilité: {trans['Probabilité']}%")
                        ])
                        card.layout = widgets.Layout(
                            border='1px solid #ddd',
                            border_radius='5px',
                            padding='10px',
                            margin='5px',
                            width='200px',
                            background_color='#f9f9f9'
                        )
                        children.append(card)
        else:
            children.append(widgets.HTML("<p>Aucune opportunité en cours</p>"))

        container.children = children
        return container

    def create_rapports_tab(self):
        """Crée l'onglet Rapports"""
        container = widgets.VBox()
        children = []

        children.append(widgets.HTML("<h3>📊 Générateur de rapports</h3>"))

        # Sélection du type de rapport
        report_type = widgets.Dropdown(
            options=['Journalier', 'Mensuel', 'Annuel', 'Pipeline', 'Performance commerciale'],
            description='Type de rapport:',
            layout=widgets.Layout(width='400px')
        )
        children.append(report_type)

        # Bouton de génération
        def generate_report(btn):
            clear_output(wait=True)
            self.create_interface()

            print(f"\n{'='*60}")
            print(f"📋 RAPPORT {report_type.value.upper()}")
            print(f"Date: {datetime.now().strftime('%d/%m/%Y %H:%M')}")
            print(f"{'='*60}\n")

            if report_type.value == 'Journalier':
                self.generate_daily_report()
            elif report_type.value == 'Mensuel':
                self.generate_monthly_report()
            elif report_type.value == 'Pipeline':
                self.generate_pipeline_report()
            elif report_type.value == 'Performance commerciale':
                self.generate_performance_report()

        btn_generate = widgets.Button(
            description='📄 Générer le rapport',
            button_style='info',
            layout=widgets.Layout(width='200px', margin='10px')
        )
        btn_generate.on_click(generate_report)
        children.append(btn_generate)

        container.children = children
        return container

    def generate_daily_report(self):
        """Génère un rapport journalier"""
        today = datetime.now().strftime('%Y-%m-%d')
        daily_trans = self.crm.transactions_df[self.crm.transactions_df['Date'] == today]

        print(f"📊 RAPPORT JOURNALIER - {today}\n")

        if len(daily_trans) > 0:
            ca_jour = daily_trans['CA Total'].sum()
            nb_trans = len(daily_trans)

            print(f"💰 CA du jour: {ca_jour:,.2f} DHS")
            print(f"📊 Nombre de transactions: {nb_trans}")
            print(f"📈 CA Moyen: {ca_jour/nb_trans:,.2f} DHS\n")

            print("Détail des transactions:")
            for _, trans in daily_trans.iterrows():
                print(f"  • {trans['Produit']} - {trans['Quantité']} {trans['Unité']} - {trans['CA Total']:,.0f} DHS")
        else:
            print("Aucune transaction aujourd'hui")

    def generate_monthly_report(self):
        """Génère un rapport mensuel"""
        current_month = datetime.now().strftime('%Y-%m')
        monthly_trans = self.crm.transactions_df[
            self.crm.transactions_df['Date'].str.startswith(current_month)
        ]

        print(f"📊 RAPPORT MENSUEL - {datetime.now().strftime('%B %Y')}\n")

        if len(monthly_trans) > 0:
            ca_mois = monthly_trans['CA Total'].sum()
            nb_trans = len(monthly_trans)
            nb_clients_actifs = monthly_trans['Client_ID'].nunique()

            print(f"💰 CA du mois: {ca_mois:,.2f} DHS")
            print(f"📊 Nombre de transactions: {nb_trans}")
            print(f"👥 Clients actifs: {nb_clients_actifs}")
            print(f"📈 CA Moyen: {ca_mois/nb_trans:,.2f} DHS\n")

            print("Répartition par catégorie:")
            for cat, montant in monthly_trans.groupby('Catégorie')['CA Total'].sum().items():
                print(f"  • {cat}: {montant:,.0f} DHS ({montant/ca_mois*100:.1f}%)")
        else:
            print("Aucune transaction ce mois-ci")

    def generate_pipeline_report(self):
        """Génère un rapport pipeline"""
        print("📊 RAPPORT PIPELINE COMMERCIAL\n")

        etapes = ['Prospection', 'Contact', 'RDV', 'Devis', 'Négociation', 'Gagné', 'Perdu']

        for etape in etapes:
            etape_trans = self.crm.transactions_df[
                (self.crm.transactions_df['Étape Pipeline'] == etape) |
                (self.crm.transactions_df['Statut'] == etape)
            ]

            if len(etape_trans) > 0:
                montant_total = etape_trans['CA Total'].sum()
                print(f"{etape}:")
                print(f"  • {len(etape_trans)} opportunités")
                print(f"  • Montant total: {montant_total:,.0f} DHS")
                print(f"  • Montant moyen: {montant_total/len(etape_trans):,.0f} DHS\n")

    def generate_performance_report(self):
        """Génère un rapport de performance"""
        print("📊 RAPPORT DE PERFORMANCE COMMERCIALE\n")

        if len(self.crm.transactions_df) > 0:
            # Top clients
            top_clients = self.crm.transactions_df.groupby('Client_ID')['CA Total'].sum().nlargest(5)
            print("🏆 TOP 5 CLIENTS:")
            for client_id, ca in top_clients.items():
                client_name = self.crm.clients_df[self.crm.clients_df['ID'] == client_id]['Société'].values
                if len(client_name) > 0:
                    print(f"  • {client_name[0]}: {ca:,.0f} DHS")

            print()

            # Top produits
            top_produits = self.crm.transactions_df.groupby('Produit')['CA Total'].sum().nlargest(5)
            print("🏆 TOP 5 PRODUITS:")
            for produit, ca in top_produits.items():
                print(f"  • {produit}: {ca:,.0f} DHS")

            print()

            # Statistiques de paiement
            paiements = self.crm.transactions_df.groupby('Paiement')['CA Total'].sum()
            print("💳 RÉPARTITION DES PAIEMENTS:")
            for mode, montant in paiements.items():
                print(f"  • {mode}: {montant:,.0f} DHS")

    def create_alertes_tab(self):
        """Crée l'onglet Alertes"""
        container = widgets.VBox()
        children = []

        children.append(widgets.HTML("<h3>⚠️ Alertes et relances</h3>"))

        # Alertes urgentes
        urgentes = self.crm.transactions_df[self.crm.transactions_df['Alerte'].str.contains('URGENT', na=False)]
        if len(urgentes) > 0:
            children.append(widgets.HTML("<h4 style='color:red;'>🔴 Alertes urgentes</h4>"))
            for _, trans in urgentes.iterrows():
                alert_card = widgets.VBox([
                    widgets.HTML(f"<b>Client ID: {trans['Client_ID']} - {trans['Produit']}</b>"),
                    widgets.HTML(f"Montant: {trans['CA Total']:,.0f} DHS"),
                    widgets.HTML(f"Paiement: {trans['Paiement']}"),
                    widgets.HTML(f"Alerte: {trans['Alerte']}")
                ])
                alert_card.layout = widgets.Layout(
                    border='2px solid red',
                    border_radius='5px',
                    padding='10px',
                    margin='5px',
                    background_color='#ffeeee'
                )
                children.append(alert_card)

        # Relances à faire
        today = datetime.now().strftime('%Y-%m-%d')
        relances = self.crm.transactions_df[
            (self.crm.transactions_df['Date Relance'] != '') &
            (self.crm.transactions_df['Date Relance'] <= today)
        ]

        if len(relances) > 0:
            children.append(widgets.HTML("<h4 style='color:orange;'>🟠 Relances à effectuer</h4>"))
            for _, trans in relances.iterrows():
                relance_card = widgets.VBox([
                    widgets.HTML(f"<b>Client ID: {trans['Client_ID']} - {trans['Produit']}</b>"),
                    widgets.HTML(f"Date relance: {trans['Date Relance']}"),
                    widgets.HTML(f"Montant: {trans['CA Total']:,.0f} DHS")
                ])
                relance_card.layout = widgets.Layout(
                    border='1px solid orange',
                    border_radius='5px',
                    padding='10px',
                    margin='5px',
                    background_color='#fff3e0'
                )
                children.append(relance_card)

        # Chèques en cours
        cheques = self.crm.transactions_df[
            self.crm.transactions_df['Paiement'].str.contains('CHÈQUE|CHEQUE', na=False)
        ]
        if len(cheques) > 0:
            children.append(widgets.HTML("<h4>🟡 Chèques en cours</h4>"))
            for _, trans in cheques.iterrows():
                cheque_card = widgets.VBox([
                    widgets.HTML(f"<b>Client ID: {trans['Client_ID']} - {trans['Produit']}</b>"),
                    widgets.HTML(f"Montant: {trans['CA Total']:,.0f} DHS"),
                    widgets.HTML(f"Échéance: {trans['Échéance']}")
                ])
                cheque_card.layout = widgets.Layout(
                    border='1px solid #ddd',
                    border_radius='5px',
                    padding='10px',
                    margin='5px',
                    background_color='#f9f9f9'
                )
                children.append(cheque_card)

        if len(urgentes) == 0 and len(relances) == 0 and len(cheques) == 0:
            children.append(widgets.HTML("<p>✅ Aucune alerte en cours</p>"))

        container.children = children
        return container

# Lancement de l'interface
interface = CRMInterface(crm)

# @title 📊 Analyses Avancées et Reporting
# ============================================
# ANALYSES AVANCÉES
# ============================================

class AdvancedAnalytics:
    """
    Classe d'analyses avancées pour le CRM
    """

    def __init__(self, crm):
        self.crm = crm

    def analyse_ca_trend(self):
        """Analyse des tendances du CA"""

        if len(self.crm.transactions_df) == 0:
            print("❌ Aucune donnée disponible")
            return

        # CA par mois
        self.crm.transactions_df['Mois'] = pd.to_datetime(self.crm.transactions_df['Date']).dt.to_period('M')
        ca_mensuel = self.crm.transactions_df.groupby('Mois')['CA Total'].sum()

        fig, axes = plt.subplots(2, 2, figsize=(15, 10))

        # Graphique 1: Évolution mensuelle
        ax = axes[0, 0]
        ca_mensuel.plot(kind='line', marker='o', ax=ax, color='#667eea', linewidth=2)
        ax.set_title('Évolution Mensuelle du CA', fontsize=14, fontweight='bold')
        ax.set_xlabel('Mois')
        ax.set_ylabel('CA (DHS)')
        ax.grid(True, alpha=0.3)

        # Graphique 2: Top 10 clients
        ax = axes[0, 1]
        top_clients = self.crm.transactions_df.groupby('Client_ID')['CA Total'].sum().nlargest(10)
        client_names = []
        for client_id in top_clients.index:
            client_name = self.crm.clients_df[self.crm.clients_df['ID'] == client_id]['Société'].values
            client_names.append(client_name[0] if len(client_name) > 0 else f'Client {client_id}')

        bars = ax.bar(range(len(top_clients)), top_clients.values, color=sns.color_palette('husl', 10))
        ax.set_title('Top 10 Clients', fontsize=14, fontweight='bold')
        ax.set_xlabel('Client')
        ax.set_ylabel('CA (DHS)')
        ax.set_xticks(range(len(top_clients)))
        ax.set_xticklabels(client_names, rotation=45, ha='right')

        # Graphique 3: Répartition par catégorie
        ax = axes[1, 0]
        ca_categorie = self.crm.transactions_df.groupby('Catégorie')['CA Total'].sum()
        wedges, texts, autotexts = ax.pie(
            ca_categorie.values,
            labels=ca_categorie.index,
            autopct='%1.1f%%',
            colors=sns.color_palette('Set3', len(ca_categorie))
        )
        ax.set_title('Répartition du CA par Catégorie', fontsize=14, fontweight='bold')

        # Graphique 4: Heatmap des transactions
        ax = axes[1, 1]
        if len(self.crm.transactions_df) > 10:
            # Créer une matrice client-produit
            pivot = self.crm.transactions_df.pivot_table(
                values='CA Total',
                index='Client_ID',
                columns='Catégorie',
                aggfunc='sum',
                fill_value=0
            )
            sns.heatmap(pivot, annot=True, fmt='.0f', cmap='YlOrRd', ax=ax)
            ax.set_title('Matrice Client-Produit', fontsize=14, fontweight='bold')

        plt.tight_layout()
        plt.show()

    def analyse_pipeline(self):
        """Analyse détaillée du pipeline"""

        if len(self.crm.transactions_df) == 0:
            print("❌ Aucune donnée disponible")
            return

        fig, axes = plt.subplots(2, 2, figsize=(15, 10))

        # Graphique 1: Entonnoir de vente
        ax = axes[0, 0]
        etapes = ['Prospection', 'Contact', 'RDV', 'Devis', 'Négociation', 'Gagné']
        valeurs = []

        for etape in etapes:
            count = len(self.crm.transactions_df[
                (self.crm.transactions_df['Étape Pipeline'] == etape) |
                (self.crm.transactions_df['Statut'] == etape)
            ])
            valeurs.append(count)

        ax.bar(etapes, valeurs, color=sns.color_palette('viridis', len(etapes)))
        ax.set_title('Entonnoir de Vente', fontsize=14, fontweight='bold')
        ax.set_xlabel('Étape')
        ax.set_ylabel('Nombre d\'opportunités')

        # Graphique 2: Taux de conversion
        ax = axes[0, 1]
        if valeurs[0] > 0:
            taux = [v/valeurs[0]*100 for v in valeurs]
            ax.plot(etapes, taux, marker='o', linewidth=2, color='#e74c3c')
            ax.set_title('Taux de Conversion (%)', fontsize=14, fontweight='bold')
            ax.set_xlabel('Étape')
            ax.set_ylabel('Taux (%)')
            ax.grid(True, alpha=0.3)

        # Graphique 3: Montant par étape
        ax = axes[1, 0]
        montants = []
        for etape in etapes[:-1]:  # Exclure "Gagné"
            montant = self.crm.transactions_df[
                (self.crm.transactions_df['Étape Pipeline'] == etape) |
                (self.crm.transactions_df['Statut'] == etape)
            ]['CA Total'].sum()
            montants.append(montant)

        ax.bar(etapes[:-1], montants, color=sns.color_palette('plasma', len(etapes)-1))
        ax.set_title('Montant Total par Étape', fontsize=14, fontweight='bold')
        ax.set_xlabel('Étape')
        ax.set_ylabel('Montant (DHS)')
        plt.setp(ax.xaxis.get_majorticklabels(), rotation=45, ha='right')

        # Graphique 4: Probabilités
        ax = axes[1, 1]
        proba_moyenne = self.crm.transactions_df.groupby('Étape Pipeline')['Probabilité'].mean()
        if len(proba_moyenne) > 0:
            proba_moyenne.plot(kind='bar', ax=ax, color='#2ecc71')
            ax.set_title('Probabilité Moyenne par Étape', fontsize=14, fontweight='bold')
            ax.set_xlabel('Étape')
            ax.set_ylabel('Probabilité (%)')

        plt.tight_layout()
        plt.show()

    def analyse_alertes(self):
        """Analyse des alertes et relances"""

        if len(self.crm.transactions_df) == 0:
            print("❌ Aucune donnée disponible")
            return

        fig, axes = plt.subplots(2, 2, figsize=(15, 10))

        # Graphique 1: Répartition des alertes
        ax = axes[0, 0]
        alertes = self.crm.transactions_df['Alerte'].value_counts()
        alertes.plot(kind='pie', autopct='%1.1f%%', ax=ax, colors=['#e74c3c', '#f39c12', '#3498db', '#2ecc71'])
        ax.set_title('Répartition des Alertes', fontsize=14, fontweight='bold')
        ax.set_ylabel('')

        # Graphique 2: Évolution des alertes
        ax = axes[0, 1]
        self.crm.transactions_df.groupby('Date')['Alerte'].count().plot(
            kind='line', marker='o', ax=ax, color='#e74c3c'
        )
        ax.set_title('Évolution du Nombre d\'Alertes', fontsize=14, fontweight='bold')
        ax.set_xlabel('Date')
        ax.set_ylabel('Nombre d\'alertes')
        plt.xticks(rotation=45)

        # Graphique 3: Alertes par client
        ax = axes[1, 0]
        alertes_client = self.crm.transactions_df.groupby('Client_ID')['Alerte'].count().nlargest(10)
        if len(alertes_client) > 0:
            alertes_client.plot(kind='bar', ax=ax, color='#e67e22')
            ax.set_title('Top 10 Clients avec Alertes', fontsize=14, fontweight='bold')
            ax.set_xlabel('Client ID')
            ax.set_ylabel('Nombre d\'alertes')

        # Graphique 4: Relances à venir
        ax = axes[1, 1]
        today = datetime.now()
        dates_relances = []

        for _, trans in self.crm.transactions_df.iterrows():
            if trans['Date Relance']:
                try:
                    date_relance = datetime.strptime(trans['Date Relance'], '%Y-%m-%d')
                    if date_relance > today:
                        dates_relances.append(date_relance)
                except:
                    pass

        if dates_relances:
            dates_series = pd.Series(dates_relances)
            dates_series.value_counts().sort_index().plot(
                kind='bar', ax=ax, color='#9b59b6'
            )
            ax.set_title('Calendrier des Relances', fontsize=14, fontweight='bold')
            ax.set_xlabel('Date')
            ax.set_ylabel('Nombre de relances')
            plt.setp(ax.xaxis.get_majorticklabels(), rotation=45, ha='right')

        plt.tight_layout()
        plt.show()

    def rapport_complet(self):
        """Génère un rapport complet avec toutes les analyses"""

        print(f"\n{'='*70}")
        print(f"📊 RAPPORT COMPLET SNEP CRM")
        print(f"Date: {datetime.now().strftime('%d/%m/%Y %H:%M')}")
        print(f"{'='*70}\n")

        # Statistiques générales
        print("📈 STATISTIQUES GÉNÉRALES")
        print("-" * 40)

        ca_total = self.crm.transactions_df['CA Total'].sum() if len(self.crm.transactions_df) > 0 else 0
        nb_transactions = len(self.crm.transactions_df)
        nb_clients = len(self.crm.clients_df)
        nb_produits = len(self.crm.produits_df)
        nb_alertes = len(self.crm.transactions_df[self.crm.transactions_df['Alerte'].str.contains('URGENT', na=False)])

        print(f"💰 CA Total: {ca_total:,.0f} DHS")
        print(f"📊 Transactions: {nb_transactions}")
        print(f"👥 Clients: {nb_clients}")
        print(f"📦 Produits: {nb_produits}")
        print(f"⚠️ Alertes urgentes: {nb_alertes}\n")

        # Analyse temporelle
        if len(self.crm.transactions_df) > 0:
            self.crm.transactions_df['Date'] = pd.to_datetime(self.crm.transactions_df['Date'])
            premier_mois = self.crm.transactions_df['Date'].min().strftime('%B %Y')
            dernier_mois = self.crm.transactions_df['Date'].max().strftime('%B %Y')

            print("📅 PÉRIODE D'ANALYSE")
            print("-" * 40)
            print(f"Du: {premier_mois}")
            print(f"Au: {dernier_mois}\n")

        # Top clients
        if len(self.crm.transactions_df) > 0:
            print("🏆 TOP 5 CLIENTS")
            print("-" * 40)
            top_clients = self.crm.transactions_df.groupby('Client_ID')['CA Total'].sum().nlargest(5)
            for client_id, ca in top_clients.items():
                client_name = self.crm.clients_df[self.crm.clients_df['ID'] == client_id]['Société'].values
                if len(client_name) > 0:
                    print(f"{client_name[0]}: {ca:,.0f} DHS")
            print()

        # Top produits
        if len(self.crm.transactions_df) > 0:
            print("🏆 TOP 5 PRODUITS")
            print("-" * 40)
            top_produits = self.crm.transactions_df.groupby('Produit')['CA Total'].sum().nlargest(5)
            for produit, ca in top_produits.items():
                print(f"{produit}: {ca:,.0f} DHS")
            print()

        # Analyses avancées
        print("📊 ANALYSES AVANCÉES")
        print("-" * 40)

        self.analyse_ca_trend()
        self.analyse_pipeline()
        self.analyse_alertes()

# Lancement des analyses
analytics = AdvancedAnalytics(crm)
analytics.rapport_complet()

# @title 💾 Export et Sauvegarde des Données
# ============================================
# EXPORT ET SAUVEGARDE
# ============================================

class DataExporter:
    """
    Classe pour l'export et la sauvegarde des données
    """

    def __init__(self, crm):
        self.crm = crm

    def export_excel_complet(self, filename='snep_crm_export.xlsx'):
        """Exporte toutes les données vers Excel"""

        with pd.ExcelWriter(filename, engine='xlsxwriter') as writer:
            # Feuille Résumé
            resume_data = {
                'Métrique': ['CA Total', 'Nombre de transactions', 'Nombre de clients', 'Nombre de produits'],
                'Valeur': [
                    f"{self.crm.transactions_df['CA Total'].sum():,.0f} DHS" if len(self.crm.transactions_df) > 0 else '0 DHS',
                    str(len(self.crm.transactions_df)),
                    str(len(self.crm.clients_df)),
                    str(len(self.crm.produits_df))
                ]
            }
            pd.DataFrame(resume_data).to_excel(writer, sheet_name='Résumé', index=False)

            # Feuille Clients
            if len(self.crm.clients_df) > 0:
                self.crm.clients_df.to_excel(writer, sheet_name='Clients', index=False)

            # Feuille Produits
            if len(self.crm.produits_df) > 0:
                self.crm.produits_df.to_excel(writer, sheet_name='Produits', index=False)

            # Feuille Transactions
            if len(self.crm.transactions_df) > 0:
                self.crm.transactions_df.to_excel(writer, sheet_name='Transactions', index=False)

            # Statistiques
            stats = pd.DataFrame({
                'Catégorie': self.crm.transactions_df.groupby('Catégorie')['CA Total'].sum().index,
                'CA Total': self.crm.transactions_df.groupby('Catégorie')['CA Total'].sum().values
            }) if len(self.crm.transactions_df) > 0 else pd.DataFrame()

            if len(stats) > 0:
                stats.to_excel(writer, sheet_name='Statistiques', index=False)

            # Formatage Excel
            workbook = writer.book

            # Format pour les montants
            money_format = workbook.add_format({'num_format': '#,##0.00 DHS', 'bold': False})

            # Appliquer le format aux colonnes appropriées
            for sheet_name in writer.sheets:
                worksheet = writer.sheets[sheet_name]
                if 'CA' in sheet_name or 'Montant' in sheet_name or 'Prix' in sheet_name:
                    worksheet.set_column('B:B', 15, money_format)

        print(f"✅ Données exportées vers {filename}")
        return filename

    def export_csv(self, prefix='snep_crm'):
        """Exporte les données en CSV"""

        import os

        if not os.path.exists('exports'):
            os.makedirs('exports')

        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')

        if len(self.crm.clients_df) > 0:
            self.crm.clients_df.to_csv(f'exports/{prefix}_clients_{timestamp}.csv', index=False)

        if len(self.crm.produits_df) > 0:
            self.crm.produits_df.to_csv(f'exports/{prefix}_produits_{timestamp}.csv', index=False)

        if len(self.crm.transactions_df) > 0:
            self.crm.transactions_df.to_csv(f'exports/{prefix}_transactions_{timestamp}.csv', index=False)

        print(f"✅ Données exportées dans le dossier 'exports/'")

    def sauvegarder_etat(self, filename='snep_crm_backup.pkl'):
        """Sauvegarde l'état complet du CRM"""

        import pickle

        etat = {
            'clients': self.crm.clients_df,
            'contacts': self.crm.contacts_df,
            'produits': self.crm.produits_df,
            'transactions': self.crm.transactions_df,
            'opportunites': self.crm.opportunites_df,
            'taches': self.crm.taches_df,
            'timestamp': datetime.now()
        }

        with open(filename, 'wb') as f:
            pickle.dump(etat, f)

        print(f"✅ État sauvegardé dans {filename}")

    def charger_etat(self, filename='snep_crm_backup.pkl'):
        """Charge un état sauvegardé"""

        import pickle
        import os

        if not os.path.exists(filename):
            print(f"❌ Fichier {filename} non trouvé")
            return

        with open(filename, 'rb') as f:
            etat = pickle.load(f)

        self.crm.clients_df = etat['clients']
        self.crm.contacts_df = etat['contacts']
        self.crm.produits_df = etat['produits']
        self.crm.transactions_df = etat['transactions']
        self.crm.opportunites_df = etat['opportunites']
        self.crm.taches_df = etat['taches']

        print(f"✅ État chargé depuis {filename}")
        print(f"📅 Sauvegarde du {etat['timestamp'].strftime('%d/%m/%Y %H:%M')}")

# Export des données
exporter = DataExporter(crm)
exporter.export_excel_complet()
exporter.export_csv()
exporter.sauvegarder_etat()