# -*- coding: utf-8 -*-
"""Copie de Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_qhXHm9HCesLRlXXO0Bf6xh76RrcXCDQ
"""

# -*- coding: utf-8 -*-
"""CRM SNEP EXTREME - Version Nettoyée et Corrigée"""

# @title ⚡ INSTALLATION DES DÉPENDANCES
!pip install -q pandas numpy matplotlib seaborn plotly ipywidgets ipython openpyxl xlsxwriter
!apt-get -q install -y python3-tk

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime, timedelta
import ipywidgets as widgets
from IPython.display import display, HTML, clear_output
import warnings
warnings.filterwarnings('ignore')

plt.style.use('seaborn-v0_8-darkgrid')
sns.set_palette("husl")

print("✅ Environnement prêt")

# ============================================
# CLASSE CRM PRINCIPALE
# ============================================

class SNEP_CRM_Extreme:
    def __init__(self):
        self.name = "SNEP CRM EXTREME"
        self.version = "3.0"
        self.clients_df = pd.DataFrame()
        self.transactions_df = pd.DataFrame()
        self.produits_df = pd.DataFrame()
        self.init_produits()
        print(f"\n╔{'═'*50}╗")
        print(f"║  ⚡ {self.name} - Version {self.version} ⚡".ljust(51) + "║")
        print(f"╚{'═'*50}╝\n")

    def init_produits(self):
        produits = [
            ['CHLORE GAZEUX 99.5%', 'Chlore', 'TONNES', 1500],
            ['CHLORE LIQUIDE 99.8%', 'Chlore', 'TONNES', 1800],
            ['SOUDE CAUSTIQUE LIQ 30%', 'Soude', 'TONNES', 800],
            ['SOUDE CAUSTIQUE LIQ 48%', 'Soude', 'TONNES', 950],
            ['ACIDE CHLORHYDRIQUE 31%', 'Acide', 'TONNES', 600],
            ['EAU DE JAVEL 12°', 'Javel', 'LITRES', 2.5],
            ['PVC SUSPENSION S60', 'PVC', 'TONNES', 1200],
        ]
        self.produits_df = pd.DataFrame(produits, columns=['Nom', 'Catégorie', 'Unité', 'Prix'])
        print(f"📦 {len(self.produits_df)} produits chargés")

    def ajouter_client(self, societe, secteur='', email='', telephone='', ville='Casablanca'):
        id_client = len(self.clients_df) + 1
        nouveau = pd.DataFrame([{
            'ID': id_client, 'Société': societe, 'Secteur': secteur,
            'Email': email, 'Téléphone': telephone, 'Ville': ville,
            'Date': datetime.now().strftime('%Y-%m-%d')
        }])
        self.clients_df = pd.concat([self.clients_df, nouveau], ignore_index=True)
        return id_client

    def ajouter_transaction(self, client_id, produit, quantite, prix, paiement='COMPTANT'):
        id_trans = len(self.transactions_df) + 1
        ca = quantite * prix
        alerte = '✓ SUIVI'
        if 'CHÈQUE' in paiement.upper() or 'CHEQUE' in paiement.upper():
            alerte = '🟡 À SURVEILLER'

        nouvelle = pd.DataFrame([{
            'ID': id_trans, 'Date': datetime.now().strftime('%Y-%m-%d'),
            'Client_ID': client_id, 'Produit': produit, 'Quantité': quantite,
            'Prix': prix, 'CA': ca, 'Paiement': paiement, 'Alerte': alerte
        }])
        self.transactions_df = pd.concat([self.transactions_df, nouvelle], ignore_index=True)
        return id_trans

    def generer_donnees_test(self):
        clients = ['ONEE', 'LYDEC', 'OCP', 'COSUMAR', 'LESIEUR']
        for c in clients:
            self.ajouter_client(c)

        for _ in range(15):
            client = np.random.randint(1, 6)
            produit = np.random.choice(self.produits_df['Nom'].tolist())
            prix = self.produits_df[self.produits_df['Nom'] == produit]['Prix'].values[0]
            qte = np.random.randint(10, 100)
            paiement = np.random.choice(['COMPTANT', 'CHÈQUE 30j'])
            self.ajouter_transaction(client, produit, qte, prix, paiement)

        print("✅ Données de test générées")

# ============================================
# INTERFACE UTILISATEUR
# ============================================

class CRMInterface:
    def __init__(self, crm):
        self.crm = crm
        self.create_interface()

    def create_interface(self):
        display(HTML("""
        <style>
        .tab { margin: 10px; }
        button { margin: 5px; padding: 10px; }
        </style>
        """))

        self.tab = widgets.Tab()
        self.tab.children = [
            self.create_dashboard(),
            self.create_clients(),
            self.create_transactions(),
            self.create_alertes()
        ]
        self.tab.set_title(0, '📊 Tableau de bord')
        self.tab.set_title(1, '👥 Clients')
        self.tab.set_title(2, '💰 Transactions')
        self.tab.set_title(3, '⚠️ Alertes')
        display(self.tab)

    def create_dashboard(self):
        container = widgets.VBox()
        ca_total = self.crm.transactions_df['CA'].sum() if len(self.crm.transactions_df) > 0 else 0
        nb_trans = len(self.crm.transactions_df)
        nb_clients = len(self.crm.clients_df)

        kpi_html = f"""
        <div style='display:flex; justify-content:space-around; margin:20px;'>
            <div style='background:#667eea; color:white; padding:20px; border-radius:10px; width:200px; text-align:center;'>
                <h2>💰 CA Total</h2>
                <h1>{ca_total:,.0f} DHS</h1>
            </div>
            <div style='background:#764ba2; color:white; padding:20px; border-radius:10px; width:200px; text-align:center;'>
                <h2>📊 Transactions</h2>
                <h1>{nb_trans}</h1>
            </div>
            <div style='background:#f39c12; color:white; padding:20px; border-radius:10px; width:200px; text-align:center;'>
                <h2>👥 Clients</h2>
                <h1>{nb_clients}</h1>
            </div>
        </div>
        """
        container.children = [widgets.HTML(kpi_html)]

        if len(self.crm.transactions_df) > 0:
            html = "<h3>📋 Dernières transactions</h3>"
            html += self.crm.transactions_df.tail(5).to_html(index=False)
            container.children += (widgets.HTML(html),)

        return container

    def create_clients(self):
        container = widgets.VBox()
        btn_add = widgets.Button(description='➕ Nouveau Client', button_style='success')

        def on_add_click(b):
            self.show_add_client_form()
        btn_add.on_click(on_add_click)

        container.children = [btn_add]

        if len(self.crm.clients_df) > 0:
            html = "<h3>Liste des clients</h3>"
            html += self.crm.clients_df.to_html(index=False)
            container.children += (widgets.HTML(html),)

        return container

    def show_add_client_form(self):
        form = widgets.VBox()
        societe = widgets.Text(description='Société:')
        secteur = widgets.Text(description='Secteur:')
        email = widgets.Text(description='Email:')
        telephone = widgets.Text(description='Téléphone:')
        ville = widgets.Text(description='Ville:', value='Casablanca')

        def save(b):
            self.crm.ajouter_client(societe.value, secteur.value, email.value, telephone.value, ville.value)
            clear_output(wait=True)
            self.create_interface()

        btn_save = widgets.Button(description='💾 Enregistrer', button_style='success')
        btn_save.on_click(save)
        form.children = [societe, secteur, email, telephone, ville, btn_save]
        display(form)

    def create_transactions(self):
        container = widgets.VBox()

        if len(self.crm.clients_df) > 0 and len(self.crm.produits_df) > 0:
            clients = [f"{row['ID']} - {row['Société']}" for _, row in self.crm.clients_df.iterrows()]
            client_select = widgets.Dropdown(options=clients, description='Client:')

            produits = self.crm.produits_df['Nom'].tolist()
            produit_select = widgets.Dropdown(options=produits, description='Produit:')

            quantite = widgets.FloatText(value=1, description='Quantité:')
            prix = widgets.FloatText(description='Prix:')
            paiement = widgets.Dropdown(options=['COMPTANT', 'CHÈQUE 30j', 'VIREMENT'], description='Paiement:')

            def update_price(change):
                if change['new']:
                    p = self.crm.produits_df[self.crm.produits_df['Nom'] == change['new']]['Prix'].values[0]
                    prix.value = p
            produit_select.observe(update_price, names='value')

            def save_transaction(b):
                client_id = int(client_select.value.split(' - ')[0])
                self.crm.ajouter_transaction(client_id, produit_select.value, quantite.value, prix.value, paiement.value)
                clear_output(wait=True)
                self.create_interface()

            btn_save = widgets.Button(description='📥 Enregistrer', button_style='success')
            btn_save.on_click(save_transaction)

            container.children = [
                widgets.HTML("<h3>➕ Nouvelle transaction</h3>"),
                client_select, produit_select, quantite, prix, paiement, btn_save
            ]

        if len(self.crm.transactions_df) > 0:
            html = "<h3>📋 Historique</h3>"
            html += self.crm.transactions_df.to_html(index=False)
            container.children += (widgets.HTML(html),)

        return container

    def create_alertes(self):
        container = widgets.VBox()

        if len(self.crm.transactions_df) > 0:
            cheques = self.crm.transactions_df[
                self.crm.transactions_df['Paiement'].str.contains('CHÈQUE|CHEQUE', na=False)
            ]
            if len(cheques) > 0:
                html = "<h3 style='color:orange;'>🟡 Chèques en cours</h3>"
                html += cheques.to_html(index=False)
                container.children += (widgets.HTML(html),)

        return container

# ============================================
# CONVERSION EN .EXE (OPTIONNEL)
# ============================================

def convertir_en_exe():
    """Fonction pour convertir le script en .exe"""
    import os
    import shutil
    from google.colab import files

    print("📦 Installation de PyInstaller...")
    !pip install pyinstaller > /dev/null

    print("⚙️ Compilation en cours...")
    !pyinstaller --onefile --windowed crm_script.py > /dev/null 2>&1

    exe_path = 'dist/crm_script.exe'
    if os.path.exists(exe_path):
        print("✅ Compilation réussie !")
        shutil.copy(exe_path, 'SNEP_CRM.exe')
        files.download('SNEP_CRM.exe')
        print("📥 Téléchargement automatique...")
    else:
        print("❌ Erreur de compilation")

# ============================================
# LANCEMENT DE L'APPLICATION
# ============================================

print("\n" + "="*60)
print("🚀 LANCEMENT DU CRM SNEP")
print("="*60)

# Création de l'instance
crm = SNEP_CRM_Extreme()

# Génération des données de test
crm.generer_donnees_test()

# Lancement de l'interface
interface = CRMInterface(crm)

print("\n✅ Application prête ! Utilisez les onglets ci-dessus 👆")

# @title 📦 CONVERTIR EN .EXE
convertir_en_exe()

# @title 📦 CONVERTIR EN EXE
!pip install pyinstaller
!pyinstaller --onefile --windowed crm_script.py