# Generated Python code from HTML
def generate_html():
    """Function that returns the HTML content"""
    from html import escape

    return """\
<!DOCTYPE html>\n"
        "<html lang=\"en\">\n"
        "<head>\n"
        "    <meta charset=\"UTF-8\">\n"
        "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
        "    <title>Zenith — Productivity Suite</title>\n"
        "    <script src=\"https://cdn.tailwindcss.com\"></script>\n"
        "    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\">\n"
        "    <link href=\"https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300;400;500;600;700&family=DM+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,400&display=swap\" rel=\"stylesheet\">\n"
        "    <style>\n"
        "        :root {\n"
        "            --bg: #0C0C0C;\n"
        "            --bg2: #111111;\n"
        "            --card: #181818;\n"
        "            --card-hover: #1F1F1F;\n"
        "            --border: #2A2A2A;\n"
        "            --fg: #E8E4DE;\n"
        "            --fg2: #C4BFB6;\n"
        "            --muted: #6B6660;\n"
        "            --accent: #D4943A;\n"
        "            --accent2: #E8A838;\n"
        "            --accent-dim: rgba(212,148,58,0.12);\n"
        "            --danger: #D94848;\n"
        "            --success: #3DB86A;\n"
        "            --info: #4A9BD9;\n"
        "        }\n"
        "\n"
        "        * { box-sizing: border-box; margin: 0; padding: 0; }\n"
        "        html { font-size: 16px; }\n"
        "        body {\n"
        "            font-family: \'DM Sans\', sans-serif;\n"
        "            background: var(--bg);\n"
        "            color: var(--fg);\n"
        "            min-height: 100vh;\n"
        "            overflow-x: hidden;\n"
        "        }\n"
        "        h1, h2, h3, h4, h5 { font-family: \'Space Grotesk\', sans-serif; }\n"
        "\n"
        "        ::-webkit-scrollbar { width: 6px; }\n"
        "        ::-webkit-scrollbar-track { background: transparent; }\n"
        "        ::-webkit-scrollbar-thumb { background: var(--border); border-radius: 3px; }\n"
        "        ::-webkit-scrollbar-thumb:hover { background: var(--muted); }\n"
        "\n"
        "        .ambient-bg { position: fixed; inset: 0; z-index: 0; pointer-events: none; overflow: hidden; }\n"
        "        .ambient-blob { position: absolute; border-radius: 50%; filter: blur(120px); opacity: 0.07; }\n"
        "        .blob-1 { width: 600px; height: 600px; background: var(--accent); top: -200px; right: -100px; animation: blobMove1 20s ease-in-out infinite; }\n"
        "        .blob-2 { width: 400px; height: 400px; background: #9B4DCA; bottom: -100px; left: -100px; animation: blobMove2 25s ease-in-out infinite; }\n"
        "        .blob-3 { width: 300px; height: 300px; background: #3DB86A; top: 50%; left: 50%; animation: blobMove3 18s ease-in-out infinite; }\n"
        "        @keyframes blobMove1 { 0%,100%{transform:translate(0,0)} 50%{transform:translate(-80px,60px)} }\n"
        "        @keyframes blobMove2 { 0%,100%{transform:translate(0,0)} 50%{transform:translate(60px,-80px)} }\n"
        "        @keyframes blobMove3 { 0%,100%{transform:translate(0,0)} 33%{transform:translate(-40px,50px)} 66%{transform:translate(40px,-30px)} }\n"
        "\n"
        "        .sidebar {\n"
        "            position: fixed; left: 0; top: 0; bottom: 0; width: 72px;\n"
        "            background: var(--bg2); border-right: 1px solid var(--border);\n"
        "            display: flex; flex-direction: column; align-items: center;\n"
        "            padding: 20px 0; z-index: 50;\n"
        "        }\n"
        "        .sidebar-logo {\n"
        "            width: 40px; height: 40px; background: var(--accent);\n"
        "            border-radius: 10px; display: flex; align-items: center; justify-content: center;\n"
        "            font-family: \'Space Grotesk\'; font-weight: 700; font-size: 18px; color: #0C0C0C;\n"
        "            margin-bottom: 32px; flex-shrink: 0;\n"
        "        }\n"
        "        .sidebar-nav { display: flex; flex-direction: column; gap: 4px; width: 100%; padding: 0 12px; flex: 1; }\n"
        "        .sidebar-btn {\n"
        "            width: 48px; height: 48px; border-radius: 12px; border: none;\n"
        "            background: transparent; color: var(--muted); cursor: pointer;\n"
        "            display: flex; align-items: center; justify-content: center;\n"
        "            font-size: 18px; transition: all 0.2s ease; position: relative;\n"
        "        }\n"
        "        .sidebar-btn:hover { background: var(--accent-dim); color: var(--fg2); }\n"
        "        .sidebar-btn.active { background: var(--accent-dim); color: var(--accent); }\n"
        "        .sidebar-btn.active::before {\n"
        "            content: \'\'; position: absolute; left: -12px; top: 50%; transform: translateY(-50%);\n"
        "            width: 3px; height: 24px; background: var(--accent); border-radius: 0 3px 3px 0;\n"
        "        }\n"
        "        .sidebar-btn .tooltip {\n"
        "            position: absolute; left: 60px; top: 50%; transform: translateY(-50%);\n"
        "            background: var(--card); color: var(--fg); padding: 6px 12px;\n"
        "            border-radius: 8px; font-size: 13px; white-space: nowrap;\n"
        "            pointer-events: none; opacity: 0; transition: opacity 0.2s;\n"
        "            border: 1px solid var(--border); z-index: 100;\n"
        "        }\n"
        "        .sidebar-btn:hover .tooltip { opacity: 1; }\n"
        "\n"
        "        .main-area { margin-left: 72px; min-height: 100vh; position: relative; z-index: 1; }\n"
        "        .topbar {\n"
        "            position: sticky; top: 0; z-index: 40;\n"
        "            background: rgba(12,12,12,0.8); backdrop-filter: blur(20px);\n"
        "            border-bottom: 1px solid var(--border);\n"
        "            padding: 16px 32px; display: flex; align-items: center; justify-content: space-between;\n"
        "        }\n"
        "        .topbar-greeting h2 { font-size: 20px; font-weight: 600; }\n"
        "        .topbar-greeting p { font-size: 13px; color: var(--muted); margin-top: 2px; }\n"
        "        .topbar-right { display: flex; align-items: center; gap: 16px; }\n"
        "        .topbar-date {\n"
        "            font-size: 13px; color: var(--muted);\n"
        "            background: var(--card); padding: 8px 14px; border-radius: 10px;\n"
        "            border: 1px solid var(--border);\n"
        "        }\n"
        "        .content { padding: 28px 32px; }\n"
        "\n"
        "        .card {\n"
        "            background: var(--card); border: 1px solid var(--border);\n"
        "            border-radius: 16px; padding: 24px; transition: all 0.25s ease;\n"
        "        }\n"
        "        .card:hover { border-color: #333; }\n"
        "        .card-title {\n"
        "            font-family: \'Space Grotesk\'; font-size: 14px; font-weight: 600;\n"
        "            color: var(--muted); text-transform: uppercase; letter-spacing: 0.05em;\n"
        "            margin-bottom: 16px; display: flex; align-items: center; gap: 8px;\n"
        "        }\n"
        "\n"
        "        .stat-card {\n"
        "            background: var(--card); border: 1px solid var(--border);\n"
        "            border-radius: 16px; padding: 20px 24px; position: relative; overflow: hidden;\n"
        "        }\n"
        "        .stat-value { font-family: \'Space Grotesk\'; font-size: 32px; font-weight: 700; }\n"
        "        .stat-label { font-size: 13px; color: var(--muted); margin-top: 4px; }\n"
        "        .stat-icon { font-size: 14px; width: 32px; height: 32px; border-radius: 8px; display: flex; align-items: center; justify-content: center; margin-bottom: 12px; }\n"
        "\n"
        "        .btn {\n"
        "            padding: 10px 20px; border-radius: 10px; border: none; cursor: pointer;\n"
        "            font-family: \'DM Sans\'; font-size: 14px; font-weight: 500;\n"
        "            transition: all 0.2s ease; display: inline-flex; align-items: center; gap: 8px;\n"
        "        }\n"
        "        .btn-primary { background: var(--accent); color: #0C0C0C; }\n"
        "        .btn-primary:hover { background: var(--accent2); transform: translateY(-1px); }\n"
        "        .btn-ghost { background: transparent; color: var(--fg2); border: 1px solid var(--border); }\n"
        "        .btn-ghost:hover { border-color: var(--muted); background: var(--card); }\n"
        "        .btn-danger { background: rgba(217,72,72,0.1); color: var(--danger); }\n"
        "        .btn-danger:hover { background: rgba(217,72,72,0.2); }\n"
        "        .btn-sm { padding: 6px 12px; font-size: 13px; border-radius: 8px; }\n"
        "\n"
        "        .input {\n"
        "            background: var(--bg); border: 1px solid var(--border); border-radius: 10px;\n"
        "            padding: 10px 14px; color: var(--fg); font-family: \'DM Sans\'; font-size: 14px;\n"
        "            outline: none; transition: border-color 0.2s; width: 100%;\n"
        "        }\n"
        "        .input:focus { border-color: var(--accent); }\n"
        "        .input::placeholder { color: var(--muted); }\n"
        "        textarea.input { resize: vertical; min-height: 80px; }\n"
        "        select.input { cursor: pointer; appearance: none; background-image: url(\"data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' width=\'12\' height=\'12\' fill=\'%236B6660\' viewBox=\'0 0 16 16\'%3E%3Cpath d=\'M8 11L3 6h10z\'/%3E%3C/svg%3E\"); background-repeat: no-repeat; background-position: right 12px center; }\n"
        "\n"
        "        .tag { display: inline-flex; align-items: center; gap: 4px; padding: 4px 10px; border-radius: 6px; font-size: 12px; font-weight: 500; }\n"
        "        .tag-work { background: rgba(74,155,217,0.12); color: #4A9BD9; }\n"
        "        .tag-personal { background: rgba(212,148,58,0.12); color: #D4943A; }\n"
        "        .tag-health { background: rgba(61,184,106,0.12); color: #3DB86A; }\n"
        "        .tag-learning { background: rgba(155,77,202,0.12); color: #9B4DCA; }\n"
        "\n"
        "        .priority-high { color: var(--danger); }\n"
        "        .priority-medium { color: var(--accent); }\n"
        "        .priority-low { color: var(--success); }\n"
        "\n"
        "        .task-item { display: flex; align-items: center; gap: 12px; padding: 14px 16px; border-radius: 12px; transition: all 0.2s; border: 1px solid transparent; }\n"
        "        .task-item:hover { background: var(--card-hover); border-color: var(--border); }\n"
        "        .task-check {\n"
        "            width: 20px; height: 20px; border-radius: 6px; border: 2px solid var(--border);\n"
        "            cursor: pointer; display: flex; align-items: center; justify-content: center;\n"
        "            transition: all 0.2s; flex-shrink: 0;\n"
        "        }\n"
        "        .task-check:hover { border-color: var(--accent); }\n"
        "        .task-check.checked { background: var(--accent); border-color: var(--accent); }\n"
        "        .task-check.checked i { color: #0C0C0C; font-size: 11px; }\n"
        "        .task-text.done { text-decoration: line-through; color: var(--muted); }\n"
        "\n"
        "        .note-card {\n"
        "            background: var(--card); border: 1px solid var(--border);\n"
        "            border-radius: 14px; padding: 20px; cursor: pointer; transition: all 0.25s; position: relative;\n"
        "        }\n"
        "        .note-card:hover { border-color: var(--accent); transform: translateY(-2px); }\n"
        "\n"
        "        .habit-day {\n"
        "            width: 28px; height: 28px; border-radius: 6px;\n"
        "            background: var(--bg); border: 1px solid var(--border);\n"
        "            cursor: pointer; transition: all 0.15s;\n"
        "        }\n"
        "        .habit-day.done { background: var(--accent); border-color: var(--accent); }\n"
        "        .habit-day:hover { border-color: var(--muted); }\n"
        "\n"
        "        .pomo-ring { transform: rotate(-90deg); }\n"
        "        .pomo-ring-bg { stroke: var(--border); }\n"
        "        .pomo-ring-progress { stroke: var(--accent); transition: stroke-dashoffset 1s linear; }\n"
        "\n"
        "        .toast-container { position: fixed; bottom: 24px; right: 24px; z-index: 9999; display: flex; flex-direction: column; gap: 8px; }\n"
        "        .toast {\n"
        "            background: var(--card); border: 1px solid var(--border);\n"
        "            padding: 14px 20px; border-radius: 12px; font-size: 14px;\n"
        "            display: flex; align-items: center; gap: 10px;\n"
        "            animation: toastIn 0.3s ease; min-width: 260px;\n"
        "            box-shadow: 0 8px 32px rgba(0,0,0,0.4);\n"
        "        }\n"
        "        .toast.out { animation: toastOut 0.3s ease forwards; }\n"
        "        @keyframes toastIn { from { transform: translateX(100px); opacity: 0; } to { transform: translateX(0); opacity: 1; } }\n"
        "        @keyframes toastOut { from { transform: translateX(0); opacity: 1; } to { transform: translateX(100px); opacity: 0; } }\n"
        "\n"
        "        .modal-overlay {\n"
        "            position: fixed; inset: 0; background: rgba(0,0,0,0.6);\n"
        "            backdrop-filter: blur(4px); z-index: 200;\n"
        "            display: flex; align-items: center; justify-content: center;\n"
        "            animation: fadeIn 0.2s ease;\n"
        "        }\n"
        "        .modal-box {\n"
        "            background: var(--card); border: 1px solid var(--border);\n"
        "            border-radius: 20px; padding: 28px; width: 90%; max-width: 480px;\n"
        "            animation: scaleIn 0.25s ease;\n"
        "        }\n"
        "        @keyframes fadeIn { from { opacity: 0; } to { opacity: 1; } }\n"
        "        @keyframes scaleIn { from { transform: scale(0.95); opacity: 0; } to { transform: scale(1); opacity: 1; } }\n"
        "\n"
        "        .view { display: none; animation: viewIn 0.3s ease; }\n"
        "        .view.active { display: block; }\n"
        "        @keyframes viewIn { from { opacity: 0; transform: translateY(8px); } to { opacity: 1; transform: translateY(0); } }\n"
        "\n"
        "        .chart-bar { border-radius: 4px 4px 0 0; transition: height 0.5s ease; min-height: 4px; }\n"
        "\n"
        "        .particle {\n"
        "            position: fixed; width: 2px; height: 2px; background: var(--accent);\n"
        "            border-radius: 50%; pointer-events: none; opacity: 0;\n"
        "            animation: particleFloat linear infinite;\n"
        "        }\n"
        "        @keyframes particleFloat {\n"
        "            0% { opacity: 0; transform: translateY(0); }\n"
        "            10% { opacity: 0.4; }\n"
        "            90% { opacity: 0.4; }\n"
        "            100% { opacity: 0; transform: translateY(-100vh); }\n"
        "        }\n"
        "\n"
        "        .empty-state {\n"
        "            text-align: center; padding: 64px 16px; color: var(--muted);\n"
        "        }\n"
        "        .empty-state i { font-size: 40px; margin-bottom: 12px; display: block; opacity: 0.3; }\n"
        "        .empty-state p { font-size: 14px; margin-top: 6px; }\n"
        "\n"
        "        @media (max-width: 768px) {\n"
        "            .sidebar { width: 56px; }\n"
        "            .main-area { margin-left: 56px; }\n"
        "            .content { padding: 20px 16px; }\n"
        "            .topbar { padding: 12px 16px; }\n"
        "            .sidebar-btn { width: 40px; height: 40px; }\n"
        "            .sidebar-logo { width: 34px; height: 34px; font-size: 15px; }\n"
        "        }\n"
        "        @media (prefers-reduced-motion: reduce) {\n"
        "            *, *::before, *::after { animation-duration: 0.01ms !important; transition-duration: 0.01ms !important; }\n"
        "        }\n"
        "    </style>\n"
        "</head>\n"
        "<body>\n"
        "    <div class=\"ambient-bg\">\n"
        "        <div class=\"ambient-blob blob-1\"></div>\n"
        "        <div class=\"ambient-blob blob-2\"></div>\n"
        "        <div class=\"ambient-blob blob-3\"></div>\n"
        "    </div>\n"
        "    <div id=\"particles\"></div>\n"
        "\n"
        "    <nav class=\"sidebar\" role=\"navigation\" aria-label=\"Main navigation\">\n"
        "        <div class=\"sidebar-logo\">Z</div>\n"
        "        <div class=\"sidebar-nav\">\n"
        "            <button class=\"sidebar-btn active\" data-view=\"dashboard\" aria-label=\"Dashboard\"><i class=\"fas fa-th-large\"></i><span class=\"tooltip\">Dashboard</span></button>\n"
        "            <button class=\"sidebar-btn\" data-view=\"focus\" aria-label=\"Focus Timer\"><i class=\"fas fa-clock\"></i><span class=\"tooltip\">Focus</span></button>\n"
        "            <button class=\"sidebar-btn\" data-view=\"tasks\" aria-label=\"Tasks\"><i class=\"fas fa-check-circle\"></i><span class=\"tooltip\">Tasks</span></button>\n"
        "            <button class=\"sidebar-btn\" data-view=\"notes\" aria-label=\"Notes\"><i class=\"fas fa-sticky-note\"></i><span class=\"tooltip\">Notes</span></button>\n"
        "            <button class=\"sidebar-btn\" data-view=\"habits\" aria-label=\"Habits\"><i class=\"fas fa-fire\"></i><span class=\"tooltip\">Habits</span></button>\n"
        "        </div>\n"
        "    </nav>\n"
        "\n"
        "    <div class=\"main-area\">\n"
        "        <header class=\"topbar\">\n"
        "            <div class=\"topbar-greeting\">\n"
        "                <h2 id=\"greeting-text\">Good morning</h2>\n"
        "                <p>Let\'s make today count</p>\n"
        "            </div>\n"
        "            <div class=\"topbar-right\">\n"
        "                <div class=\"topbar-date\" id=\"current-date\"></div>\n"
        "            </div>\n"
        "        </header>\n"
        "\n"
        "        <main class=\"content\">\n"
        "            <!-- Dashboard -->\n"
        "            <section class=\"view active\" id=\"view-dashboard\">\n"
        "                <div class=\"grid grid-cols-2 lg:grid-cols-4 gap-4 mb-6\" id=\"stats-row\"></div>\n"
        "                <div class=\"grid grid-cols-1 lg:grid-cols-3 gap-6\">\n"
        "                    <div class=\"card lg:col-span-2\">\n"
        "                        <div class=\"card-title\"><i class=\"fas fa-list-check\" style=\"color:var(--accent)\"></i> Today\'s Tasks</div>\n"
        "                        <div id=\"dashboard-tasks\"></div>\n"
        "                    </div>\n"
        "                    <div class=\"card\">\n"
        "                        <div class=\"card-title\"><i class=\"fas fa-chart-bar\" style=\"color:var(--success)\"></i> Weekly Activity</div>\n"
        "                        <div id=\"activity-chart\" class=\"flex items-end gap-2 justify-between\" style=\"height:160px; padding-top:20px;\"></div>\n"
        "                        <div class=\"flex justify-between mt-3 text-xs\" style=\"color:var(--muted)\"><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span></div>\n"
        "                    </div>\n"
        "                </div>\n"
        "                <div class=\"grid grid-cols-1 lg:grid-cols-2 gap-6 mt-6\">\n"
        "                    <div class=\"card\">\n"
        "                        <div class=\"card-title\"><i class=\"fas fa-sticky-note\" style=\"color:var(--info)\"></i> Recent Notes</div>\n"
        "                        <div id=\"dashboard-notes\"></div>\n"
        "                    </div>\n"
        "                    <div class=\"card\">\n"
        "                        <div class=\"card-title\"><i class=\"fas fa-fire\" style=\"color:var(--danger)\"></i> Habit Streaks</div>\n"
        "                        <div id=\"dashboard-habits\"></div>\n"
        "                    </div>\n"
        "                </div>\n"
        "            </section>\n"
        "\n"
        "            <!-- Focus -->\n"
        "            <section class=\"view\" id=\"view-focus\">\n"
        "                <div class=\"max-w-lg mx-auto text-center\">\n"
        "                    <div class=\"card\" style=\"padding:40px\">\n"
        "                        <div class=\"card-title justify-center\" style=\"margin-bottom:24px\"><i class=\"fas fa-crosshairs\" style=\"color:var(--accent)\"></i> Focus Timer</div>\n"
        "                        <div style=\"position:relative; width:260px; height:260px; margin:0 auto 28px;\">\n"
        "                            <svg width=\"260\" height=\"260\" class=\"pomo-ring\">\n"
        "                                <circle class=\"pomo-ring-bg\" cx=\"130\" cy=\"130\" r=\"115\" fill=\"none\" stroke-width=\"8\"/>\n"
        "                                <circle class=\"pomo-ring-progress\" id=\"pomo-progress\" cx=\"130\" cy=\"130\" r=\"115\" fill=\"none\" stroke-width=\"8\" stroke-linecap=\"round\" stroke-dasharray=\"722.57\" stroke-dashoffset=\"0\"/>\n"
        "                            </svg>\n"
        "                            <div style=\"position:absolute;inset:0;display:flex;flex-direction:column;align-items:center;justify-content:center;\">\n"
        "                                <div id=\"pomo-time\" style=\"font-family:\'Space Grotesk\';font-size:56px;font-weight:700;letter-spacing:-2px;\">25:00</div>\n"
        "                                <div id=\"pomo-mode\" style=\"font-size:13px;color:var(--muted);margin-top:4px;\">Focus</div>\n"
        "                            </div>\n"
        "                        </div>\n"
        "                        <div class=\"flex items-center justify-center gap-4\">\n"
        "                            <button class=\"btn btn-ghost btn-sm\" id=\"pomo-reset\" aria-label=\"Reset\"><i class=\"fas fa-undo\"></i></button>\n"
        "                            <button class=\"btn btn-primary\" id=\"pomo-toggle\" style=\"padding:14px 36px;font-size:16px;\"><i class=\"fas fa-play\"></i> Start</button>\n"
        "                            <button class=\"btn btn-ghost btn-sm\" id=\"pomo-skip\" aria-label=\"Skip\"><i class=\"fas fa-forward\"></i></button>\n"
        "                        </div>\n"
        "                        <div class=\"flex items-center justify-center gap-2 mt-6\">\n"
        "                            <button class=\"btn btn-sm pomo-mode-btn\" data-minutes=\"25\" style=\"background:var(--accent-dim);color:var(--accent);border:1px solid transparent;\">Focus</button>\n"
        "                            <button class=\"btn btn-sm pomo-mode-btn\" data-minutes=\"5\" style=\"background:transparent;color:var(--fg2);border:1px solid var(--border);\">Short Break</button>\n"
        "                            <button class=\"btn btn-sm pomo-mode-btn\" data-minutes=\"15\" style=\"background:transparent;color:var(--fg2);border:1px solid var(--border);\">Long Break</button>\n"
        "                        </div>\n"
        "                    </div>\n"
        "                    <div class=\"card mt-6\">\n"
        "                        <div class=\"card-title\"><i class=\"fas fa-trophy\" style=\"color:var(--accent)\"></i> Sessions Today</div>\n"
        "                        <div id=\"pomo-sessions\" class=\"flex items-center gap-3 flex-wrap\"></div>\n"
        "                    </div>\n"
        "                </div>\n"
        "            </section>\n"
        "\n"
        "            <!-- Tasks -->\n"
        "            <section class=\"view\" id=\"view-tasks\">\n"
        "                <div class=\"flex items-center justify-between mb-6 flex-wrap gap-3\">\n"
        "                    <h2 style=\"font-size:24px;font-weight:700;\">Tasks</h2>\n"
        "                    <div class=\"flex items-center gap-3\">\n"
        "                        <div class=\"flex items-center gap-1\" id=\"task-filters\">\n"
        "                            <button class=\"btn btn-sm filter-btn\" data-filter=\"all\" style=\"background:var(--accent-dim);color:var(--accent);border:1px solid transparent;\">All</button>\n"
        "                            <button class=\"btn btn-sm filter-btn\" data-filter=\"active\" style=\"background:transparent;color:var(--fg2);border:1px solid var(--border);\">Active</button>\n"
        "                            <button class=\"btn btn-sm filter-btn\" data-filter=\"completed\" style=\"background:transparent;color:var(--fg2);border:1px solid var(--border);\">Done</button>\n"
        "                        </div>\n"
        "                        <button class=\"btn btn-primary\" id=\"add-task-btn\"><i class=\"fas fa-plus\"></i> Add Task</button>\n"
        "                    </div>\n"
        "                </div>\n"
        "                <div id=\"tasks-list\"></div>\n"
        "            </section>\n"
        "\n"
        "            <!-- Notes -->\n"
        "            <section class=\"view\" id=\"view-notes\">\n"
        "                <div class=\"flex items-center justify-between mb-6\">\n"
        "                    <h2 style=\"font-size:24px;font-weight:700;\">Notes</h2>\n"
        "                    <button class=\"btn btn-primary\" id=\"add-note-btn\"><i class=\"fas fa-plus\"></i> New Note</button>\n"
        "                </div>\n"
        "                <div id=\"notes-grid\" class=\"grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4\"></div>\n"
        "                <div id=\"notes-empty\" class=\"empty-state\"><i class=\"fas fa-sticky-note\"></i><p>No notes yet. Create one to get started.</p></div>\n"
        "            </section>\n"
        "\n"
        "            <!-- Habits -->\n"
        "            <section class=\"view\" id=\"view-habits\">\n"
        "                <div class=\"flex items-center justify-between mb-6\">\n"
        "                    <h2 style=\"font-size:24px;font-weight:700;\">Habits</h2>\n"
        "                    <button class=\"btn btn-primary\" id=\"add-habit-btn\"><i class=\"fas fa-plus\"></i> Add Habit</button>\n"
        "                </div>\n"
        "                <div id=\"habits-list\"></div>\n"
        "                <div id=\"habits-empty\" class=\"empty-state\"><i class=\"fas fa-fire\"></i><p>No habits tracked yet. Start building good routines.</p></div>\n"
        "            </section>\n"
        "        </main>\n"
        "    </div>\n"
        "\n"
        "    <div id=\"modal-root\"></div>\n"
        "    <div class=\"toast-container\" id=\"toast-container\"></div>\n"
        "\n"
        "    <script>\n"
        "    const STORAGE_KEY = \'zenith_fresh_v1\';\n"
        "\n"
        "    /* Generate a completely blank slate */\n"
        "    function createFreshState() {\n"
        "        const now = Date.now();\n"
        "        return {\n"
        "            tasks: [],\n"
        "            notes: [],\n"
        "            habits: [],\n"
        "            pomodoro: { sessionsToday: 0, totalMinutes: 0 },\n"
        "            activity: [0, 0, 0, 0, 0, 0, 0],\n"
        "            nextId: 1,\n"
        "            createdAt: now\n"
        "        };\n"
        "    }\n"
        "\n"
        "    function loadState() {\n"
        "        try {\n"
        "            const raw = localStorage.getItem(STORAGE_KEY);\n"
        "            if (raw) return JSON.parse(raw);\n"
        "        } catch(e) {}\n"
        "        return createFreshState();\n"
        "    }\n"
        "\n"
        "    function saveState() {\n"
        "        localStorage.setItem(STORAGE_KEY, JSON.stringify(state));\n"
        "    }\n"
        "\n"
        "    let state = loadState();\n"
        "\n"
        "    /* Utility */\n"
        "    function genId() { return state.nextId++; }\n"
        "\n"
        "    function toast(msg, type=\'info\') {\n"
        "        const ct = document.getElementById(\'toast-container\');\n"
        "        const icons = { info:\'fa-circle-info\', success:\'fa-circle-check\', error:\'fa-circle-xmark\', warning:\'fa-triangle-exclamation\' };\n"
        "        const colors = { info:\'var(--info)\', success:\'var(--success)\', error:\'var(--danger)\', warning:\'var(--accent)\' };\n"
        "        const el = document.createElement(\'div\');\n"
        "        el.className = \'toast\';\n"
        "        el.innerHTML = `<i class=\"fas ${icons[type]||icons.info}\" style=\"color:${colors[type]||colors.info}\"></i><span>${msg}</span>`;\n"
        "        ct.appendChild(el);\n"
        "        setTimeout(() => { el.classList.add(\'out\'); setTimeout(() => el.remove(), 300); }, 2800);\n"
        "    }\n"
        "\n"
        "    function showModal(html) {\n"
        "        const root = document.getElementById(\'modal-root\');\n"
        "        const overlay = document.createElement(\'div\');\n"
        "        overlay.className = \'modal-overlay\';\n"
        "        overlay.innerHTML = `<div class=\"modal-box\">${html}</div>`;\n"
        "        overlay.addEventListener(\'click\', e => { if (e.target === overlay) closeModal(); });\n"
        "        root.appendChild(overlay);\n"
        "        setTimeout(() => { const inp = overlay.querySelector(\'input, textarea\'); if (inp) inp.focus(); }, 100);\n"
        "    }\n"
        "\n"
        "    function closeModal() { document.getElementById(\'modal-root\').innerHTML = \'\'; }\n"
        "\n"
        "    /* Greeting */\n"
        "    function updateGreeting() {\n"
        "        const h = new Date().getHours();\n"
        "        let g = \'Good evening\';\n"
        "        if (h < 12) g = \'Good morning\';\n"
        "        else if (h < 17) g = \'Good afternoon\';\n"
        "        document.getElementById(\'greeting-text\').textContent = g;\n"
        "    }\n"
        "\n"
        "    function updateDate() {\n"
        "        document.getElementById(\'current-date\').textContent = new Date().toLocaleDateString(\'en-US\', { weekday:\'long\', month:\'long\', day:\'numeric\', year:\'numeric\' });\n"
        "    }\n"
        "\n"
        "    /* Navigation */\n"
        "    let currentView = \'dashboard\';\n"
        "    let taskFilter = \'all\';\n"
        "\n"
        "    document.querySelectorAll(\'.sidebar-btn\').forEach(btn => {\n"
        "        btn.addEventListener(\'click\', () => switchView(btn.dataset.view));\n"
        "    });\n"
        "\n"
        "    function switchView(v) {\n"
        "        currentView = v;\n"
        "        document.querySelectorAll(\'.sidebar-btn\').forEach(b => b.classList.toggle(\'active\', b.dataset.view === v));\n"
        "        document.querySelectorAll(\'.view\').forEach(el => el.classList.toggle(\'active\', el.id === \'view-\' + v));\n"
        "        render();\n"
        "    }\n"
        "\n"
        "    function render() {\n"
        "        switch(currentView) {\n"
        "            case \'dashboard\': renderDashboard(); break;\n"
        "            case \'focus\': renderFocus(); break;\n"
        "            case \'tasks\': renderTasks(); break;\n"
        "            case \'notes\': renderNotes(); break;\n"
        "            case \'habits\': renderHabits(); break;\n"
        "        }\n"
        "    }\n"
        "\n"
        "    /* ==================== DASHBOARD ==================== */\n"
        "    function renderDashboard() {\n"
        "        const active = state.tasks.filter(t => !t.done).length;\n"
        "        const done = state.tasks.filter(t => t.done).length;\n"
        "        const mins = state.pomodoro.totalMinutes;\n"
        "        const habits = state.habits.length;\n"
        "\n"
        "        document.getElementById(\'stats-row\').innerHTML = [\n"
        "            { icon:\'fa-list-check\', bg:\'var(--accent-dim)\', fg:\'var(--accent)\', glow:\'var(--accent)\', val:active, label:\'Active Tasks\' },\n"
        "            { icon:\'fa-check-double\', bg:\'rgba(61,184,106,0.12)\', fg:\'var(--success)\', glow:\'var(--success)\', val:done, label:\'Completed\' },\n"
        "            { icon:\'fa-clock\', bg:\'rgba(74,155,217,0.12)\', fg:\'var(--info)\', glow:\'var(--info)\', val:mins, label:\'Focus Minutes\' },\n"
        "            { icon:\'fa-fire\', bg:\'rgba(155,77,202,0.12)\', fg:\'#9B4DCA\', glow:\'#9B4DCA\', val:habits, label:\'Active Habits\' },\n"
        "        ].map(s => `\n"
        "            <div class=\"stat-card\">\n"
        "                <div class=\"stat-icon\" style=\"background:${s.bg};color:${s.fg}\"><i class=\"fas ${s.icon}\"></i></div>\n"
        "                <div class=\"stat-value\">${s.val}</div>\n"
        "                <div class=\"stat-label\">${s.label}</div>\n"
        "                <div style=\"position:absolute;top:0;right:0;width:80px;height:80px;background:${s.glow};border-radius:50%;filter:blur(40px);opacity:0.08;\"></div>\n"
        "            </div>\n"
        "        `).join(\'\');\n"
        "\n"
        "        /* Tasks preview */\n"
        "        const dt = document.getElementById(\'dashboard-tasks\');\n"
        "        if (state.tasks.length === 0) {\n"
        "            dt.innerHTML = \'<div class=\"empty-state\" style=\"padding:32px\"><i class=\"fas fa-plus-circle\"></i><p>Add tasks from the Tasks view to see them here.</p></div>\';\n"
        "        } else {\n"
        "            dt.innerHTML = state.tasks.slice(0, 5).map(t => `\n"
        "                <div class=\"task-item\">\n"
        "                    <div class=\"task-check ${t.done?\'checked\':\'\'}\" data-task-toggle=\"${t.id}\">\n"
        "                        ${t.done ? \'<i class=\"fas fa-check\"></i>\' : \'\'}\n"
        "                    </div>\n"
        "                    <span class=\"flex-1 ${t.done?\'task-text done\':\'\'}\" style=\"font-size:14px;\">${t.text}</span>\n"
        "                    <span class=\"tag tag-${t.category}\" style=\"font-size:11px;\">${t.category}</span>\n"
        "                    <i class=\"fas fa-circle priority-${t.priority}\" style=\"font-size:8px;\"></i>\n"
        "                </div>\n"
        "            `).join(\'\');\n"
        "            dt.querySelectorAll(\'[data-task-toggle]\').forEach(el => {\n"
        "                el.addEventListener(\'click\', () => toggleTask(parseInt(el.dataset.taskToggle)));\n"
        "            });\n"
        "        }\n"
        "\n"
        "        /* Activity chart */\n"
        "        const maxAct = Math.max(...state.activity, 1);\n"
        "        const todayIdx = (new Date().getDay() + 6) % 7;\n"
        "        document.getElementById(\'activity-chart\').innerHTML = state.activity.map((v, i) => {\n"
        "            const h = Math.max(4, (v / maxAct) * 140);\n"
        "            const isToday = i === todayIdx;\n"
        "            return `<div class=\"chart-bar\" style=\"width:100%;height:${h}px;background:${isToday ? \'var(--accent)\' : \'var(--border)\'};${isToday ? \'box-shadow:0 0 12px rgba(212,148,58,0.3);\' : \'\'}\"></div>`;\n"
        "        }).join(\'\');\n"
        "\n"
        "        /* Notes preview */\n"
        "        const dn = document.getElementById(\'dashboard-notes\');\n"
        "        if (state.notes.length === 0) {\n"
        "            dn.innerHTML = \'<div class=\"empty-state\" style=\"padding:32px\"><i class=\"fas fa-pen-fancy\"></i><p>Create notes from the Notes view.</p></div>\';\n"
        "        } else {\n"
        "            dn.innerHTML = state.notes.slice(0, 3).map(n => `\n"
        "                <div style=\"padding:10px 0;border-bottom:1px solid var(--border);display:flex;align-items:center;gap:10px;\">\n"
        "                    <div style=\"width:4px;height:32px;border-radius:2px;background:${n.color};flex-shrink:0;\"></div>\n"
        "                    <div style=\"flex:1;min-width:0;\">\n"
        "                        <div style=\"font-size:14px;font-weight:500;\">${n.title}</div>\n"
        "                        <div style=\"font-size:12px;color:var(--muted);white-space:nowrap;overflow:hidden;text-overflow:ellipsis;\">${n.content}</div>\n"
        "                    </div>\n"
        "                </div>\n"
        "            `).join(\'\');\n"
        "        }\n"
        "\n"
        "        /* Habits preview */\n"
        "        const dh = document.getElementById(\'dashboard-habits\');\n"
        "        if (state.habits.length === 0) {\n"
        "            dh.innerHTML = \'<div class=\"empty-state\" style=\"padding:32px\"><i class=\"fas fa-seedling\"></i><p>Track habits from the Habits view.</p></div>\';\n"
        "        } else {\n"
        "            dh.innerHTML = state.habits.map(h => {\n"
        "                const streak = h.days.filter(d => d).length;\n"
        "                return `<div style=\"display:flex;align-items:center;gap:12px;padding:10px 0;border-bottom:1px solid var(--border);\">\n"
        "                    <div style=\"width:32px;height:32px;border-radius:8px;background:${h.color}22;color:${h.color};display:flex;align-items:center;justify-content:center;font-size:14px;\"><i class=\"fas ${h.icon}\"></i></div>\n"
        "                    <span style=\"flex:1;font-size:14px;\">${h.name}</span>\n"
        "                    <span style=\"font-size:13px;font-weight:600;color:${h.color};\">${streak}/7</span>\n"
        "                </div>`;\n"
        "            }).join(\'\');\n"
        "        }\n"
        "    }\n"
        "\n"
        "    /* ==================== FOCUS TIMER ==================== */\n"
        "    let pomo = { running: false, timeLeft: 25*60, total: 25*60, mode: \'Focus\', interval: null };\n"
        "\n"
        "    function renderFocus() {\n"
        "        updatePomoDisplay();\n"
        "        renderPomoSessions();\n"
        "    }\n"
        "\n"
        "    function updatePomoDisplay() {\n"
        "        const m = Math.floor(pomo.timeLeft / 60);\n"
        "        const s = pomo.timeLeft % 60;\n"
        "        document.getElementById(\'pomo-time\').textContent = `${String(m).padStart(2,\'0\')}:${String(s).padStart(2,\'0\')}`;\n"
        "        document.getElementById(\'pomo-mode\').textContent = pomo.mode;\n"
        "        const circ = 2 * Math.PI * 115;\n"
        "        const progress = pomo.total > 0 ? 1 - (pomo.timeLeft / pomo.total) : 0;\n"
        "        document.getElementById(\'pomo-progress\').setAttribute(\'stroke-dashoffset\', circ * (1 - progress));\n"
        "        const btn = document.getElementById(\'pomo-toggle\');\n"
        "        btn.innerHTML = pomo.running ? \'<i class=\"fas fa-pause\"></i> Pause\' : \'<i class=\"fas fa-play\"></i> Start\';\n"
        "\n"
        "        document.querySelectorAll(\'.pomo-mode-btn\').forEach(b => {\n"
        "            const min = parseInt(b.dataset.minutes);\n"
        "            const active = pomo.total === min * 60;\n"
        "            b.style.background = active ? \'var(--accent-dim)\' : \'transparent\';\n"
        "            b.style.color = active ? \'var(--accent)\' : \'var(--fg2)\';\n"
        "            b.style.border = active ? \'1px solid transparent\' : \'1px solid var(--border)\';\n"
        "        });\n"
        "    }\n"
        "\n"
        "    function renderPomoSessions() {\n"
        "        const ct = document.getElementById(\'pomo-sessions\');\n"
        "        const n = state.pomodoro.sessionsToday;\n"
        "        if (n === 0) { ct.innerHTML = \'<span style=\"color:var(--muted);font-size:14px;\">No sessions completed yet today. Start focusing!</span>\'; return; }\n"
        "        let html = \'\';\n"
        "        for (let i = 0; i < n; i++) html += `<div style=\"width:36px;height:36px;border-radius:10px;background:var(--accent-dim);display:flex;align-items:center;justify-content:center;color:var(--accent);font-size:14px;\"><i class=\"fas fa-check\"></i></div>`;\n"
        "        ct.innerHTML = html;\n"
        "    }\n"
        "\n"
        "    function pomoTick() {\n"
        "        pomo.timeLeft--;\n"
        "        if (pomo.timeLeft <= 0) {\n"
        "            clearInterval(pomo.interval);\n"
        "            pomo.running = false;\n"
        "            if (pomo.total === 25 * 60) {\n"
        "                state.pomodoro.sessionsToday++;\n"
        "                state.pomodoro.totalMinutes += 25;\n"
        "                saveState();\n"
        "                toast(\'Focus session complete! Great work.\', \'success\');\n"
        "            } else {\n"
        "                toast(\'Break is over. Ready for another round?\', \'info\');\n"
        "            }\n"
        "            pomo.timeLeft = 0;\n"
        "            renderPomoSessions();\n"
        "        }\n"
        "        updatePomoDisplay();\n"
        "    }\n"
        "\n"
        "    document.getElementById(\'pomo-toggle\').addEventListener(\'click\', () => {\n"
        "        if (pomo.running) { clearInterval(pomo.interval); pomo.running = false; }\n"
        "        else { pomo.running = true; pomo.interval = setInterval(pomoTick, 1000); }\n"
        "        updatePomoDisplay();\n"
        "    });\n"
        "\n"
        "    document.getElementById(\'pomo-reset\').addEventListener(\'click\', () => {\n"
        "        clearInterval(pomo.interval); pomo.running = false; pomo.timeLeft = pomo.total; updatePomoDisplay();\n"
        "    });\n"
        "\n"
        "    document.getElementById(\'pomo-skip\').addEventListener(\'click\', () => {\n"
        "        clearInterval(pomo.interval); pomo.running = false;\n"
        "        if (pomo.total === 25 * 60) {\n"
        "            state.pomodoro.sessionsToday++; state.pomodoro.totalMinutes += 25; saveState();\n"
        "            toast(\'Session skipped and counted.\', \'warning\'); renderPomoSessions();\n"
        "        }\n"
        "        pomo.timeLeft = pomo.total; updatePomoDisplay();\n"
        "    });\n"
        "\n"
        "    document.querySelectorAll(\'.pomo-mode-btn\').forEach(btn => {\n"
        "        btn.addEventListener(\'click\', () => {\n"
        "            const min = parseInt(btn.dataset.minutes);\n"
        "            clearInterval(pomo.interval); pomo.running = false;\n"
        "            pomo.total = min * 60; pomo.timeLeft = min * 60;\n"
        "            pomo.mode = btn.textContent.trim(); updatePomoDisplay();\n"
        "        });\n"
        "    });\n"
        "\n"
        "    /* ==================== TASKS ==================== */\n"
        "    function renderTasks() {\n"
        "        let filtered = state.tasks;\n"
        "        if (taskFilter === \'active\') filtered = state.tasks.filter(t => !t.done);\n"
        "        if (taskFilter === \'completed\') filtered = state.tasks.filter(t => t.done);\n"
        "\n"
        "        document.querySelectorAll(\'.filter-btn\').forEach(b => {\n"
        "            const active = b.dataset.filter === taskFilter;\n"
        "            b.style.background = active ? \'var(--accent-dim)\' : \'transparent\';\n"
        "            b.style.color = active ? \'var(--accent)\' : \'var(--fg2)\';\n"
        "            b.style.border = active ? \'1px solid transparent\' : \'1px solid var(--border)\';\n"
        "        });\n"
        "\n"
        "        const list = document.getElementById(\'tasks-list\');\n"
        "        if (filtered.length === 0) {\n"
        "            const msgs = { all:\'No tasks yet. Add one to get started.\', active:\'All caught up! Nothing active.\', completed:\'No completed tasks yet.\' };\n"
        "            list.innerHTML = `<div class=\"empty-state\"><i class=\"fas fa-check-circle\"></i><p>${msgs[taskFilter]}</p></div>`;\n"
        "            return;\n"
        "        }\n"
        "\n"
        "        list.innerHTML = filtered.map(t => `\n"
        "            <div class=\"task-item\" style=\"border:1px solid var(--border);border-radius:12px;margin-bottom:8px;\">\n"
        "                <div class=\"task-check ${t.done?\'checked\':\'\'}\" data-task-toggle=\"${t.id}\">\n"
        "                    ${t.done ? \'<i class=\"fas fa-check\"></i>\' : \'\'}\n"
        "                </div>\n"
        "                <div class=\"flex-1 min-w-0\">\n"
        "                    <span class=\"${t.done?\'task-text done\':\'\'}\" style=\"font-size:15px;\">${t.text}</span>\n"
        "                    <div style=\"margin-top:4px;display:flex;align-items:center;gap:8px;\">\n"
        "                        <span class=\"tag tag-${t.category}\">${t.category}</span>\n"
        "                        <span style=\"font-size:11px;color:var(--muted);\"><i class=\"fas fa-circle priority-${t.priority}\" style=\"font-size:7px;margin-right:4px;\"></i>${t.priority}</span>\n"
        "                    </div>\n"
        "                </div>\n"
        "                <button class=\"btn btn-danger btn-sm\" data-task-delete=\"${t.id}\" aria-label=\"Delete task\"><i class=\"fas fa-trash-alt\"></i></button>\n"
        "            </div>\n"
        "        `).join(\'\');\n"
        "\n"
        "        list.querySelectorAll(\'[data-task-toggle]\').forEach(el => {\n"
        "            el.addEventListener(\'click\', () => toggleTask(parseInt(el.dataset.taskToggle)));\n"
        "        });\n"
        "        list.querySelectorAll(\'[data-task-delete]\').forEach(el => {\n"
        "            el.addEventListener(\'click\', () => deleteTask(parseInt(el.dataset.taskDelete)));\n"
        "        });\n"
        "    }\n"
        "\n"
        "    document.querySelectorAll(\'.filter-btn\').forEach(b => {\n"
        "        b.addEventListener(\'click\', () => { taskFilter = b.dataset.filter; renderTasks(); });\n"
        "    });\n"
        "\n"
        "    document.getElementById(\'add-task-btn\').addEventListener(\'click\', () => {\n"
        "        showModal(`\n"
        "            <h3 style=\"font-size:18px;font-weight:600;margin-bottom:20px;\">New Task</h3>\n"
        "            <div style=\"display:flex;flex-direction:column;gap:14px;\">\n"
        "                <input class=\"input\" id=\"m-task-text\" placeholder=\"What needs to be done?\" maxlength=\"200\">\n"
        "                <div>\n"
        "                    <label style=\"font-size:13px;color:var(--muted);margin-bottom:6px;display:block;\">Category</label>\n"
        "                    <select class=\"input\" id=\"m-task-cat\"><option value=\"work\">Work</option><option value=\"personal\">Personal</option><option value=\"health\">Health</option><option value=\"learning\">Learning</option></select>\n"
        "                </div>\n"
        "                <div>\n"
        "                    <label style=\"font-size:13px;color:var(--muted);margin-bottom:6px;display:block;\">Priority</label>\n"
        "                    <select class=\"input\" id=\"m-task-pri\"><option value=\"medium\">Medium</option><option value=\"high\">High</option><option value=\"low\">Low</option></select>\n"
        "                </div>\n"
        "                <div style=\"display:flex;gap:10px;justify-content:flex-end;margin-top:8px;\">\n"
        "                    <button class=\"btn btn-ghost\" id=\"m-task-cancel\">Cancel</button>\n"
        "                    <button class=\"btn btn-primary\" id=\"m-task-save\">Add Task</button>\n"
        "                </div>\n"
        "            </div>\n"
        "        `);\n"
        "        document.getElementById(\'m-task-cancel\').addEventListener(\'click\', closeModal);\n"
        "        document.getElementById(\'m-task-save\').addEventListener(\'click\', addTask);\n"
        "        document.getElementById(\'m-task-text\').addEventListener(\'keydown\', e => { if (e.key === \'Enter\') addTask(); });\n"
        "    });\n"
        "\n"
        "    function addTask() {\n"
        "        const text = document.getElementById(\'m-task-text\').value.trim();\n"
        "        if (!text) { toast(\'Please enter a task description.\', \'warning\'); return; }\n"
        "        state.tasks.unshift({ id: genId(), text, category: document.getElementById(\'m-task-cat\').value, priority: document.getElementById(\'m-task-pri\').value, done: false, created: Date.now() });\n"
        "        saveState(); closeModal(); toast(\'Task added!\', \'success\'); render();\n"
        "    }\n"
        "\n"
        "    function toggleTask(id) {\n"
        "        const t = state.tasks.find(t => t.id === id);\n"
        "        if (t) {\n"
        "            t.done = !t.done;\n"
        "            if (t.done) { state.activity[(new Date().getDay() + 6) % 7]++; }\n"
        "            saveState(); render();\n"
        "        }\n"
        "    }\n"
        "\n"
        "    function deleteTask(id) {\n"
        "        state.tasks = state.tasks.filter(t => t.id !== id);\n"
        "        saveState(); toast(\'Task deleted.\', \'info\'); render();\n"
        "    }\n"
        "\n"
        "    /* ==================== NOTES ==================== */\n"
        "    const noteColors = [\'#4A9BD9\',\'#9B4DCA\',\'#3DB86A\',\'#D4943A\',\'#D94848\',\'#E8A838\'];\n"
        "\n"
        "    function renderNotes() {\n"
        "        const grid = document.getElementById(\'notes-grid\');\n"
        "        const empty = document.getElementById(\'notes-empty\');\n"
        "        if (state.notes.length === 0) { grid.innerHTML = \'\'; empty.style.display = \'block\'; return; }\n"
        "        empty.style.display = \'none\';\n"
        "        grid.innerHTML = state.notes.map(n => `\n"
        "            <div class=\"note-card\" data-note-edit=\"${n.id}\">\n"
        "                <div style=\"display:flex;align-items:center;gap:8px;margin-bottom:10px;\">\n"
        "                    <div style=\"width:8px;height:8px;border-radius:50%;background:${n.color};\"></div>\n"
        "                    <span style=\"font-weight:600;font-size:15px;flex:1;\">${n.title}</span>\n"
        "                    <button class=\"btn btn-danger btn-sm\" data-note-delete=\"${n.id}\" aria-label=\"Delete note\"><i class=\"fas fa-trash-alt\"></i></button>\n"
        "                </div>\n"
        "                <p style=\"font-size:13px;color:var(--fg2);line-height:1.6;white-space:pre-wrap;max-height:100px;overflow:hidden;\">${n.content}</p>\n"
        "                <div style=\"font-size:11px;color:var(--muted);margin-top:12px;\">${new Date(n.created).toLocaleDateString()}</div>\n"
        "            </div>\n"
        "        `).join(\'\');\n"
        "\n"
        "        grid.querySelectorAll(\'[data-note-edit]\').forEach(el => {\n"
        "            el.addEventListener(\'click\', e => { if (!e.target.closest(\'[data-note-delete]\')) editNote(parseInt(el.dataset.noteEdit)); });\n"
        "        });\n"
        "        grid.querySelectorAll(\'[data-note-delete]\').forEach(el => {\n"
        "            el.addEventListener(\'click\', e => { e.stopPropagation(); deleteNote(parseInt(el.dataset.noteDelete)); });\n"
        "        });\n"
        "    }\n"
        "\n"
        "    document.getElementById(\'add-note-btn\').addEventListener(\'click\', () => showNoteModal(null));\n"
        "\n"
        "    function editNote(id) { const n = state.notes.find(n => n.id === id); if (n) showNoteModal(n); }\n"
        "\n"
        "    function showNoteModal(note) {\n"
        "        const isEdit = !!note;\n"
        "        const sel = isEdit ? note.color : noteColors[0];\n"
        "        showModal(`\n"
        "            <h3 style=\"font-size:18px;font-weight:600;margin-bottom:20px;\">${isEdit ? \'Edit Note\' : \'New Note\'}</h3>\n"
        "            <div style=\"display:flex;flex-direction:column;gap:14px;\">\n"
        "                <input class=\"input\" id=\"m-note-title\" placeholder=\"Note title\" value=\"${isEdit ? note.title.replace(/\"/g,\'&quot;\') : \'\'}\" maxlength=\"100\">\n"
        "                <textarea class=\"input\" id=\"m-note-content\" placeholder=\"Write your note...\" rows=\"5\">${isEdit ? note.content : \'\'}</textarea>\n"
        "                <div>\n"
        "                    <label style=\"font-size:13px;color:var(--muted);margin-bottom:8px;display:block;\">Color</label>\n"
        "                    <div style=\"display:flex;gap:8px;\" id=\"m-note-colors\">\n"
        "                        ${noteColors.map(c => `<div class=\"note-c-opt\" data-color=\"${c}\" style=\"width:28px;height:28px;border-radius:8px;background:${c};cursor:pointer;border:2px solid ${c===sel?\'white\':\'transparent\'};transition:border 0.2s;\"></div>`).join(\'\')}\n"
        "                    </div>\n"
        "                </div>\n"
        "                <div style=\"display:flex;gap:10px;justify-content:flex-end;margin-top:8px;\">\n"
        "                    <button class=\"btn btn-ghost\" id=\"m-note-cancel\">Cancel</button>\n"
        "                    <button class=\"btn btn-primary\" id=\"m-note-save\">${isEdit ? \'Save Changes\' : \'Create Note\'}</button>\n"
        "                </div>\n"
        "            </div>\n"
        "        `);\n"
        "        document.getElementById(\'m-note-cancel\').addEventListener(\'click\', closeModal);\n"
        "        document.getElementById(\'m-note-save\').addEventListener(\'click\', () => saveNote(isEdit ? note.id : 0));\n"
        "        document.querySelectorAll(\'.note-c-opt\').forEach(el => {\n"
        "            el.addEventListener(\'click\', () => {\n"
        "                document.querySelectorAll(\'.note-c-opt\').forEach(e => e.style.borderColor = \'transparent\');\n"
        "                el.style.borderColor = \'white\';\n"
        "            });\n"
        "        });\n"
        "    }\n"
        "\n"
        "    function saveNote(id) {\n"
        "        const title = document.getElementById(\'m-note-title\').value.trim();\n"
        "        const content = document.getElementById(\'m-note-content\').value.trim();\n"
        "        if (!title) { toast(\'Please enter a title.\', \'warning\'); return; }\n"
        "        const ac = document.querySelector(\'.note-c-opt[style*=\"white\"]\');\n"
        "        const color = ac ? ac.dataset.color : noteColors[0];\n"
        "        if (id) { const n = state.notes.find(n => n.id === id); if (n) { n.title = title; n.content = content; n.color = color; } }\n"
        "        else { state.notes.unshift({ id: genId(), title, content, color, created: Date.now() }); }\n"
        "        saveState(); closeModal(); toast(id ? \'Note updated!\' : \'Note created!\', \'success\'); render();\n"
        "    }\n"
        "\n"
        "    function deleteNote(id) { state.notes = state.notes.filter(n => n.id !== id); saveState(); toast(\'Note deleted.\', \'info\'); render(); }\n"
        "\n"
        "    /* ==================== HABITS ==================== */\n"
        "    const habitIcons = [\'fa-brain\',\'fa-dumbbell\',\'fa-book\',\'fa-ban\',\'fa-heart\',\'fa-moon\',\'fa-apple-whole\',\'fa-pen\',\'fa-music\',\'fa-bicycle\'];\n"
        "    const habitColors = [\'#4A9BD9\',\'#9B4DCA\',\'#3DB86A\',\'#D4943A\',\'#D94848\',\'#E8A838\',\'#3DB8B8\',\'#BD4DA8\'];\n"
        "    const dayLabels = [\'M\',\'T\',\'W\',\'T\',\'F\',\'S\',\'S\'];\n"
        "\n"
        "    function renderHabits() {\n"
        "        const list = document.getElementById(\'habits-list\');\n"
        "        const empty = document.getElementById(\'habits-empty\');\n"
        "        if (state.habits.length === 0) { list.innerHTML = \'\'; empty.style.display = \'block\'; return; }\n"
        "        empty.style.display = \'none\';\n"
        "        list.innerHTML = state.habits.map(h => {\n"
        "            const streak = h.days.filter(d => d).length;\n"
        "            return `\n"
        "            <div class=\"card\" style=\"margin-bottom:12px;\">\n"
        "                <div style=\"display:flex;align-items:center;gap:14px;margin-bottom:16px;\">\n"
        "                    <div style=\"width:40px;height:40px;border-radius:10px;background:${h.color}22;color:${h.color};display:flex;align-items:center;justify-content:center;font-size:16px;\"><i class=\"fas ${h.icon}\"></i></div>\n"
        "                    <div style=\"flex:1;\">\n"
        "                        <span style=\"font-weight:600;font-size:15px;\">${h.name}</span>\n"
        "                        <span style=\"font-size:13px;color:var(--muted);margin-left:8px;\">${streak}/7 this week</span>\n"
        "                    </div>\n"
        "                    <button class=\"btn btn-danger btn-sm\" data-habit-delete=\"${h.id}\" aria-label=\"Delete habit\"><i class=\"fas fa-trash-alt\"></i></button>\n"
        "                </div>\n"
        "                <div style=\"display:flex;align-items:center;gap:8px;\">\n"
        "                    ${h.days.map((d, i) => `\n"
        "                        <div style=\"text-align:center;\">\n"
        "                            <div style=\"font-size:11px;color:var(--muted);margin-bottom:4px;\">${dayLabels[i]}</div>\n"
        "                            <div class=\"habit-day ${d?\'done\':\'\'}\" data-habit-toggle=\"${h.id}|${i}\" style=\"${d ? \'background:\'+h.color+\';border-color:\'+h.color+\';\' : \'\'}\"></div>\n"
        "                        </div>\n"
        "                    `).join(\'\')}\n"
        "                    <div style=\"flex:1;\"></div>\n"
        "                    <div style=\"width:60px;height:6px;border-radius:3px;background:var(--border);overflow:hidden;\">\n"
        "                        <div style=\"height:100%;border-radius:3px;background:${h.color};width:${(streak/7)*100}%;transition:width 0.3s;\"></div>\n"
        "                    </div>\n"
        "                </div>\n"
        "            </div>`;\n"
        "        }).join(\'\');\n"
        "\n"
        "        list.querySelectorAll(\'[data-habit-toggle]\').forEach(el => {\n"
        "            el.addEventListener(\'click\', () => {\n"
        "                const [hid, di] = el.dataset.habitToggle.split(\'|\').map(Number);\n"
        "                toggleHabitDay(hid, di);\n"
        "            });\n"
        "        });\n"
        "        list.querySelectorAll(\'[data-habit-delete]\').forEach(el => {\n"
        "            el.addEventListener(\'click\', () => deleteHabit(parseInt(el.dataset.habitDelete)));\n"
        "        });\n"
        "    }\n"
        "\n"
        "    document.getElementById(\'add-habit-btn\').addEventListener(\'click\', () => {\n"
        "        showModal(`\n"
        "            <h3 style=\"font-size:18px;font-weight:600;margin-bottom:20px;\">New Habit</h3>\n"
        "            <div style=\"display:flex;flex-direction:column;gap:14px;\">\n"
        "                <input class=\"input\" id=\"m-habit-name\" placeholder=\"Habit name (e.g. Meditate)\" maxlength=\"50\">\n"
        "                <div>\n"
        "                    <label style=\"font-size:13px;color:var(--muted);margin-bottom:8px;display:block;\">Icon</label>\n"
        "                    <div style=\"display:flex;gap:6px;flex-wrap:wrap;\" id=\"m-habit-icons\">\n"
        "                        ${habitIcons.map((ic, i) => `<div class=\"h-i-opt\" data-icon=\"${ic}\" style=\"width:36px;height:36px;border-radius:8px;background:var(--bg);border:2px solid ${i===0?\'var(--accent)\':\'var(--border)\'};display:flex;align-items:center;justify-content:center;cursor:pointer;color:var(--fg2);font-size:14px;transition:all 0.15s;\"><i class=\"fas ${ic}\"></i></div>`).join(\'\')}\n"
        "                    </div>\n"
        "                </div>\n"
        "                <div>\n"
        "                    <label style=\"font-size:13px;color:var(--muted);margin-bottom:8px;display:block;\">Color</label>\n"
        "                    <div style=\"display:flex;gap:8px;\" id=\"m-habit-colors\">\n"
        "                        ${habitColors.map((c, i) => `<div class=\"h-c-opt\" data-color=\"${c}\" style=\"width:28px;height:28px;border-radius:8px;background:${c};cursor:pointer;border:2px solid ${i===0?\'white\':\'transparent\'};transition:border 0.2s;\"></div>`).join(\'\')}\n"
        "                    </div>\n"
        "                </div>\n"
        "                <div style=\"display:flex;gap:10px;justify-content:flex-end;margin-top:8px;\">\n"
        "                    <button class=\"btn btn-ghost\" id=\"m-habit-cancel\">Cancel</button>\n"
        "                    <button class=\"btn btn-primary\" id=\"m-habit-save\">Add Habit</button>\n"
        "                </div>\n"
        "            </div>\n"
        "        `);\n"
        "        document.getElementById(\'m-habit-cancel\').addEventListener(\'click\', closeModal);\n"
        "        document.getElementById(\'m-habit-save\').addEventListener(\'click\', addHabit);\n"
        "        document.querySelectorAll(\'.h-i-opt\').forEach(el => {\n"
        "            el.addEventListener(\'click\', () => {\n"
        "                document.querySelectorAll(\'.h-i-opt\').forEach(e => e.style.borderColor = \'var(--border)\');\n"
        "                el.style.borderColor = \'var(--accent)\';\n"
        "            });\n"
        "        });\n"
        "        document.querySelectorAll(\'.h-c-opt\').forEach(el => {\n"
        "            el.addEventListener(\'click\', () => {\n"
        "                document.querySelectorAll(\'.h-c-opt\').forEach(e => e.style.borderColor = \'transparent\');\n"
        "                el.style.borderColor = \'white\';\n"
        "            });\n"
        "        });\n"
        "    });\n"
        "\n"
        "    function addHabit() {\n"
        "        const name = document.getElementById(\'m-habit-name\').value.trim();\n"
        "        if (!name) { toast(\'Please enter a habit name.\', \'warning\'); return; }\n"
        "        const ai = document.querySelector(\'.h-i-opt[style*=\"var(--accent)\"]\');\n"
        "        const ac = document.querySelector(\'.h-c-opt[style*=\"white\"]\');\n"
        "        state.habits.push({ id: genId(), name, icon: ai ? ai.dataset.icon : habitIcons[0], color: ac ? ac.dataset.color : habitColors[0], days: [false,false,false,false,false,false,false] });\n"
        "        saveState(); closeModal(); toast(\'Habit added!\', \'success\'); render();\n"
        "    }\n"
        "\n"
        "    function toggleHabitDay(hid, di) {\n"
        "        const h = state.habits.find(h => h.id === hid);\n"
        "        if (h) { h.days[di] = !h.days[di]; saveState(); render(); }\n"
        "    }\n"
        "\n"
        "    function deleteHabit(id) { state.habits = state.habits.filter(h => h.id !== id); saveState(); toast(\'Habit removed.\', \'info\'); render(); }\n"
        "\n"
        "    /* ==================== PARTICLES ==================== */\n"
        "    function createParticles() {\n"
        "        const ct = document.getElementById(\'particles\');\n"
        "        for (let i = 0; i < 15; i++) {\n"
        "            const p = document.createElement(\'div\');\n"
        "            p.className = \'particle\';\n"
        "            p.style.left = Math.random() * 100 + \'vw\';\n"
        "            p.style.bottom = \'-10px\';\n"
        "            p.style.animationDuration = (8 + Math.random() * 12) + \'s\';\n"
        "            p.style.animationDelay = (Math.random() * 10) + \'s\';\n"
        "            const sz = (1 + Math.random() * 2) + \'px\';\n"
        "            p.style.width = sz; p.style.height = sz;\n"
        "            ct.appendChild(p);\n"
        "        }\n"
        "    }\n"
        "\n"
        "    /* ==================== INIT ==================== */\n"
        "    updateGreeting();\n"
        "    updateDate();\n"
        "    createParticles();\n"
        "    renderDashboard();\n"
        "    setInterval(() => { updateGreeting(); updateDate(); }, 60000);\n"
        "    </script>\n"
        "</body>\n"
        "</html>"""

if __name__ == "__main__":
    html = generate_html()
    print(html)
    # You can also write to a file:
    # with open("output.html", "w") as f:
    #     f.write(html)
