from random import choice
en = ["Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina", "Armenia", "Australia", "Austria", "Azerbaijan", ["The Bahamas", "Bahamas"], "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Cabo Verde", "Cambodia", "Cameroon", "Canada", ["Central African Republic", "CAR"], "Chad", "Chile", "China", "Colombia", "Comoros", ["Democratic Republic of the Congo", "DRC"], ["Republic of the Congo", "Congo"], "Costa Rica", "Cote d'Ivoire", "Croatia", "Cuba", "Cyprus", ["Czechia", "Czech Republic"], "Denmark", "Djibouti", "Dominica", "Dominican Republic", ["East Timor", "Timor‑Leste"], "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", ["Eswatini", "Swaziland"], "Ethiopia", "Fiji", "Finland", "France", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guinea‑Bissau", "Guyana", "Haiti", "Honduras", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Israel", "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "North Korea", "South Korea", "Kosovo", "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Mauritania", "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "Norway", "Oman", "Pakistan", "Palau", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland", "Portugal", "Qatar", "Romania", "Russia", "Rwanda", "Saint Kitts and Nevis", "Saint Lucia", "Samoa", "San Marino", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", "Sweden", "Switzerland", "Syria", "Tajikistan", "Tanzania", "Thailand", "Togo", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", ["United Arab Emirates", "UAE"], ["United Kingdom", "UK"], ["United States of America", "USA"], "Uruguay", "Uzbekistan", "Vanuatu", ["Vatican City", "Vatican"], "Venezuela", "Vietnam", "Yemen", "Zambia", "Zimbabwe"]
ru = ["Афганистан", "Албания", "Алжир", "Андорра", "Ангола", "Антигуа и Барбуда", "Аргентина", "Армения", "Австралия", "Австрия", "Азербайджан", "Багамские Острова", "Бахрейн", "Бангладеш", "Барбадос", "Беларусь", "Бельгия", "Белиз", "Бенин", "Бутан", "Боливия", "Босния и Герцеговина", "Ботсвана", "Бразилия", "Бруней", "Болгария", "Буркина‑Фасо", "Бурунди", "Кабо‑Верде", "Камбоджа", "Камерун", "Канада", "Центральноафриканская Республика", "Чад", "Чили", "Китай", "Колумбия", "Коморы", "Демократическая Республика Конго", "Конго", "Коста‑Рика", "Кот‑д’Ивуар", "Хорватия", "Куба", "Кипр", "Чехия", "Дания", "Джибути", "Доминика", "Доминиканская Республика", "Тимор‑Лесте", "Эквадор", "Египет", "Сальвадор", "Экваториальная Гвинея", "Эритрея", "Эстония", "Эсватини", "Эфиопия", "Фиджи", "Финляндия", "Франция", "Габон", "Гамбия", "Грузия", "Германия", "Гана", "Греция", "Гренада", "Гватемала", "Гвинея", "Гвинея‑Бисау", "Гайана", "Гаити", "Гондурас", "Венгрия", "Исландия", "Индия", "Индонезия", "Иран", "Ирак", "Ирландия", "Израиль", "Италия", "Ямайка", "Япония", "Иордания", "Казахстан", "Кения", "Кирибати", "Северная Корея", "Южная Корея", "Косово", "Кувейт", "Кыргызстан", "Лаос", "Латвия", "Ливан", "Лесото", "Либерия", "Ливия", "Лихтенштейн", "Литва", "Люксембург", "Мадагаскар", "Малави", "Малайзия", "Мальдивы", "Мали", "Мальта", "Мавритания", "Маврикий", "Мексика", "Микронезия", "Молдавия", "Монако", "Монголия", "Черногория", "Марокко", "Мозамбик", "Мьянма", "Намибия", "Науру", "Непал", "Нидерланды", "Новая Зеландия", "Никарагуа", "Нигер", "Нигерия", "Норвегия", "Оман", "Пакистан", "Палау", "Панама", "Папуа — Новая Гвинея", "Парагвай", "Перу", "Филиппины", "Польша", "Португалия", "Катар", "Румыния", "Россия", "Руанда", "Сент‑Китс и Невис", "Сент‑Люсия", "Самоа", "Сан‑Марино", "Саудовская Аравия", "Сенегал", "Сербия", "Сейшелы", "Сьерра‑Леоне", "Сингапур", "Словакия", "Словения", "Соломоновы Острова", "Сомали", "Южная Африка", "Южный Судан", "Испания", "Шри‑Ланка", "Судан", "Суринам", "Швеция", "Швейцария", "Сирия", "Таджикистан", "Танзания", "Таиланд", "Того", "Тринидад и Тобаго", "Тунис", "Турция", "Туркменистан", "Тувалу", "Уганда", "Украина", "Объединённые Арабские Эмираты", "Великобритания", "Соединённые Штаты Америки", "Уругвай", "Узбекистан", "Вануату", "Ватикан", "Венесуэла", "Вьетнам", "Йемен", "Замбия", "Зимбабве"]
print("Викторина по английскому. Я буду говорить страны, а ты должен напечатать их на английском. Печатай без дефисов и лишних знаков. Каждое слово (кроме and) должно быть с большой буквы.")

while True:
    cnt = 0
    for i in range(30):
        h = choice(list(range(190)))
        strr = "Как будет " + ru[h] + " по-английски? "
        new = input(strr)
        if (isinstance(en[h], list) and new in en[h]) or (isinstance(en[h], str) and new == en[h]):
            print("Правильно!")
            cnt += 1
        elif isinstance(en[h], list):
            print(f"Неправильно(\nПравильно: {en[h][0]}.")
        else:
            print(f"Неправильно(\nПравильно: {en[h]}.")
    print("У тебя", cnt, "баллов из 30!")
    if input("Если хочешь сыграть ещё раз, то нажми Enter, если хочешь закончить, то напиши что нибудь и нажми Enter: ") != "":
        break