print("создайте своего персонажа")
name = input("Как зовут твоего персонажа?")
age = input("Сколько лет вашему персонажу?")
strengths = input("Каковы сильные стороны вашего персонажа?")
weaknesses = input("Каковы слабые стороны вашего персонажа?")
print("Имя вашего персонажа", name)
print("Ваш персонаж", age, "лет")
print("Сильные стороны:", strengths)
print("Слабые стороны:", weaknesses)
print(name, "says, 'tThanks for creating me!'")